### ISSUE TITLE
Changing an instance name can cause a TypeError

### ISSUE THREAD

**Issue by rhendric** [purescript/purescript#4179] opened 2021-09-02 00:25 UTC
## Description

For user-provided code, PureScript is pretty good at statically ensuring that any recursive references are deferred until every definition in a recursive binding group has been defined. This doesn't prevent infinite loops, but it does prevent `TypeError: foo is undefined` problems.

However, when instances are involved, PureScript bends the rules a little bit: it's legal for PureScript to insert class dictionary expressions such that there are cyclic references between instances, even if some of those references are not in a deferred context, as long as at least one reference in each cycle is deferred. This is needed to support using `liftA1` and `ap` (without eta expansion) to define `Functor` and `Apply` instances in terms of `Applicative` and `Monad` instances, even though the latter depend on the former via deferred superclass references.

But this rule-bending comes at a cost: it's possible to write instances unwisely such that TypeErrors are thrown at run time, and PureScript won't catch it statically. This is bad enough, but at least the run-time error tips you off that you've done something sketchy and you can fix it.

The eye-opening discovery for me was that you can write a cyclic chain of instances that compiles to working code, and then do nothing but *change the name of one of the instances*, and the chain will now compile to code that throws a TypeError. If anyone were to be unlucky enough to encounter this in the wild, I wouldn't expect them to guess without a ton of sleuthing work that an instance name change caused the regression!

Right now, this is pretty hard to do. But I'm discovering that #3915 makes these situations more likely, and I need help figuring out what to do about it, starting with the existing behavior.

## To Reproduce

* Go to https://try.purescript.org/?gist=b066944c85a273c43c5b28d03d988393
* Observe that it correctly renders ‘[1]’
* Rename `deltaArray` to `adeltaArray`
* TypeError!

## Expected behavior

Honestly, I'm not sure, but not this.

I think our options, aside from the status quo, are:
1. Revoke the special privileges for instances. Anyone using the `liftA1`/`ap` pattern in their monad stacks will need to eta-expand those methods. **Edit:** Or we could change the representation of instance dictionaries (again...) so that members are always thunks, and the accessor functions generated for them call those thunks. That might be a significant deoptimization though?
2. Do more precise analysis of these cycles. The quartet of instances I've defined here differs structurally from the `Functor`-to-`Monad` stack when `liftA1` and `ap` are used, such that we can forbid the former and permit the latter. I've started down this road in #3915, but it is still a breaking change because it will reject some cyclic instances that are currently allowed.
3. Change the `Ord` key provided to the graph algorithm that orders these instances—right now it's the instance name. If, for example, we used the source position as the key, then this issue could be triggered by reordering the instances in the source file but not by renaming them. Maybe that's a more intuitive problem to have? This is basically just a cosmetic fix for a more fundamental issue.

## Additional context

Here's the approach I'm currently considering for option 2. Using `Effect`'s instances as an exemplar, the dependency graph between instances of the `Functor`-to-`Monad` classes looks like this:

<img alt="Monad stack dependency graph" src="https://user-images.githubusercontent.com/1570964/131759680-360b21b6-00af-49c6-be04-9c3d76f0eddb.png" width="166">

I'm omitting the `Bind` instance because it doesn't add anything interesting to the graph. Solid arrows are immediate dependencies, while dashed arrows are deferred dependencies.

As contrast, here's the `Alpha`-to-`Delta` cycle from my example:

<img alt="Repro example dependency graph" src="https://user-images.githubusercontent.com/1570964/131759736-90503e78-048f-4fd3-9e7f-fd2b4047dfe5.png" width="149">

Both of these graphs are currently allowed because there are no cycles when considering only the solid arrows.

We can do better if we take into account the fact that an immediate reference could cause deferred references of that reference to be forced. Taken literally, this doesn't seem to help, as these graphs are strongly connected when both types of arrow are considered. But we can apply an additional principle of trusting that the programmer has some intended order in which these instances can be defined; from that we can postulate that the code executed when defining instance X will not actually force any deferred references to X, or any deferred references to instances that must depend on X.

Using the previous principle, let's add edges to the graph from X to Y whenever there is a solid arrow from X to a third instance Z, and a path from Z to Y using solid or dashed arrows that does not contain any instances from which X is reachable by solid arrows alone (including X itself). The result for the `Monad` instances, with the new edges represented as zig-zags, is:

<img alt="Monad stack dependency graph with extra edges" src="https://user-images.githubusercontent.com/1570964/131761075-7e08b7d0-6ebd-4f58-8874-27146873a75a.png" width="166">

Considering the solid and zig-zag arrows, this graph is still acyclic, and the corresponding ordering of instances works with the optimizations introduced in #3915.

The result for the example instances is:

<img alt="Repro example dependency graph with extra edges" src="https://user-images.githubusercontent.com/1570964/131761258-a9509c81-d024-4482-bab7-9f874f4a9280.png" width="149">

Unlike the previous graph, this one now has a cycle when considering solid and zig-zag arrows. While it's still true that there is an ordering of these instances that results in success, determining that ordering requires knowing that the dashed arrow from `Delta` to `Alpha` (and consequently the zig-zag from `Charlie` to `Alpha`) is not followed by any of the code executed during the definition of any of these instances, and that fact hinges on the implementation of `useDelta`, which in the general case could be defined in a different module and could have an implementation that is non-trivial to analyze. So I would propose that there's no reasonable way for the compiler to determine that this cycle of instances is safe, and instead of creating a potential Heisenbug, the compiler should reject it.

I'm obliged to point out that one counterintuitive consequence of this proposal would be that *adding* an immediate dependency between `Alpha` and `Charlie` (in either direction) would *resolve* the cycle into something that the compiler would accept. I think this might be among the lesser of the available evils.

## PureScript version

0.14.4

**Comment by JordanMartinez** [comment] 2021-09-02 19:44
Renaming `deltaArray` to `deltaKArray` does not trigger the type error.

Actually renaming `deltaArray` so that it starts with `a` is the only way I can reproduce the issue:
- `adeltaArray` = issue
- `aeltaArray` = issue
- `af` = issue
- `b` = no issue

I think this is a symptom of another issue.

**Comment by rhendric** [comment] 2021-09-02 19:48
Any name which causes the formerly-known-as-`deltaArray` to precede `alphaArray` when sorted by name triggers the error. But you could also rename `deltaArray` to `b` and rename `alphaArray` to `balphaArray` and you'd see the issue. All that matters is how the instances are ordered after they're sorted by name.

**Comment by JordanMartinez** [comment] 2021-09-02 19:49
Ah! Thanks for clarifying that.

**Comment by rhendric** [comment] 2021-12-21 23:55
I hadn't realized before, but the problem is not limited to instances. Here's a simpler case:

```purs
force :: forall a. (Unit -> a) -> a
force f = f unit

alpha = force \_ -> bravo.x
bravo = { backref: \_ -> alpha, x: 1 }
```

Compiles and runs with no error on 0.14.5. Rename `bravo` to `abravo` (or anything that lexically precedes `alpha`, as before), and compilation still succeeds but execution fails with a TypeError.

In this case, it's at least clear what the ideal resolution should be. `bravo` should precede `alpha` regardless of their names, because `bravo` occurs in `alpha` in a position where it may (will, but the compiler can't know that without inspecting the implementation of `force`) be used, but `alpha` only occurs in `bravo` in a position where it is inert until `bravo` itself is used.

Then consider:
```purs
alpha = force \_ -> bravo.x
bravo = { backref: force \_ -> alpha, x: 1 }
```

Again, this compiles and runs with no error. But `bravo.backref` is undefined at run time, which can lead to other errors. No ordering of `alpha` and `bravo` would avoid this.

One last thing:

```purs
selfOwn = { a: 1, b: force \_ -> selfOwn.a }
```

Now ordering isn't a question. This can only compile to code that must result in a TypeError when run. Our only options are to disallow this currently-valid program, or conclude that `force` and any functions like it are unsafe, despite being, uh, extremely safe-looking.

---

I think we ought to be guided by the principle that the compiler will either reject your program or emit code that will not result in a TypeError (absent the user using FFI or doing anything with our explicitly unsafe functions). We can't protect against non-termination, but I think we can aim for this lower bar. 

To achieve it, we're going to have to reject some programs that currently compile—the question in my mind is just how far should we go in trying to minimize the set of programs thus impacted, keeping in mind that the cost of a more sophisticated scheme is measured both in implementation complexity and in the burden of understanding the language. On one end of the spectrum, we can simply forbid usage loops and do nothing else—this would allow mutually recursive functions, but disallow the `liftA1`/`ap` pattern as currently used.

I originally proposed doing more sophisticated graph analysis to try to find better orderings, but the heart of this problem is the `selfOwn` example above. I want to disallow that example, which means, I think, that fancy ordering strategies won't be sufficient on their own.

What would help would be eta expansion, where relevant. This could conceivably trade some TypeError problems for non-termination problems, which might not be an improvement. I don't yet have a coherent proposal for where to eta-expand and where to reject cycles, but right now that's the only real alternative I see to breaking probably a whole lot of monads.

Does anyone want to argue me out of declaring total war on TypeErrors?

**Comment by garyb** [comment] 2021-12-22 13:00
I've been thinking about this a bit since you wrote it up, but I don't really have a good answer. I'm definitely in favour of reducing the possibilities for runtime `TypeError`s due to this sort of thing, but I find it hard to assess how far to go without seeing what would be rejected by it. The best answer I can come up with in regards to that is "as long is it doesn't reject any of _my_ programs it sounds great" :smile: but that's not a very useful position.

I imagine use of things like `fix` (along with eta expansion, as you mentioned) would probably be able to mitigate the potentially rejected situations that are currently allowed, but the concern in understanding the language is a good one too. People already run into some difficulties there when implementing instances that use default methods, it seems.

So this is also vague, but I maybe a good barometer for how far to go would be to disallow "things that are easy to do by mistake that will result in runtime `TypeError`s", since although this is definitely a problem, I'm not aware of it occurring very often right now, so making it harder to write all programs for the sake of fixing some rarer cases is definitely a rough tradeoff. Also, probably whatever we come up with we'll be able to find more and more sophisticated ways to circumvent, resulting in rejecting even more programs to cover the new edge cases we come up with. Maybe I'm wrong there, but I feel like outside of a total language there are always going to be ways to sneak it in.

**Comment by rhendric** [comment] 2021-12-22 21:18
Hm, yeah....

How about this then: we change how recursive binding groups are translated into JavaScript (other backends left as an exercise for the reader), so that the following
```purs
a = f \_ -> c
b = g c \_ -> a
c = h a \_ -> b
```
would translate to, approximately,
```js
const $undef = {}, $indef = {};
let a = $undef, b = $undef, c = $undef;
function $init_a(lineNumber) {
  if (a === $indef) {
    throw new ReferenceError("a was needed before it finished initializing", "MyModule.purs", lineNumber);
  }
  if (a === $undef) {
    a = $indef;
    a = f(function () {
      return $init_c(12); // where 12 is the line number of `a = f \_ -> c`
    });
  }
  return a;
}
function $init_b(lineNumber) {
  if (b === $indef) {
    throw new ReferenceError("b was needed before it finished initializing", "MyModule.purs", lineNumber);
  }
  if (b === $undef) {
    b = $indef;
    b = g($init_c(13))(function () { // where 13 is the line number of `b = g c \_-> a`
      return $init_a(13);
    });
  }
  return b;
}
function $init_c(lineNumber) {
  if (c === $indef) {
    throw new ReferenceError("c was needed before it finished initializing", "MyModule.purs", lineNumber);
  }
  if (c === $undef) {
    c = $indef;
    c = h($init_a(14))(function () { // where 14 is the line number of `c = h a \_ -> b`
      return $init_b(14);
    });
  }
  return c;
}
$init_a(12);
$init_b(13);
$init_c(14);
```

It's a bit of a generated-code-splosion, but: ordering problems would be accurately sorted out at run time, with only a constant-factor performance penalty; nothing is made lazy via eta expansion, so users don't need to reason about the consequences of that and there's no opportunity to introduce infinite loops where there weren't any before; and the error messages are early and helpful, unlike the TypeErrors one gets if an `undefined` value slips into one's program. The only thing made lazy here is the initialization of variables in recursive binding groups; the variables themselves are still used in a call-by-value way, like anywhere else in PureScript.

The principle we can then apply to compile-time cycle checks is to reject a program if the compiler can prove that a ReferenceError would be thrown, and leave the rest for the generated cycle checks to sort out. I think this basically describes what is currently allowed—it allows the `liftA1`/`ap` pattern, the `Alpha`–`Delta` example I opened the issue with, and every example in my last comment.

The biggest downside I see, aside from code bloat, is that well-behaved self-references like
```purs
ones :: Lazy.List Int
ones = 1 Lazy.: defer \_ -> ones
```
are now going to be a little slower, since the inner reference needs to do an is-defined test on every invocation. But it's not as if we're giving up reference sharing; there's still only ever one `ones`.

How do we feel about that trade-off?

**Comment by JordanMartinez** [comment] 2021-12-23 14:58
Let's say we move forward with this. If we later added annotations, perhaps there could be one that disables this for those who "know what they're doing" and need the extra performance?

I'm a bit confused, however, about how your proposed implementation triggers the `ReferenceError`. Or is there some other analysis the compiler would do before accepting or rejecting the code?

**Comment by rhendric** [comment] 2021-12-23 19:13
> If we later added annotations, perhaps there could be one that disables this for those who "know what they're doing" and need the extra performance?

Perhaps! Might not even need anything as general as annotations; if we wanted to hack something in, a primitive function named `unsafeReference :: forall a. a -> a` or something could be a signal to CodeGen not to do the thing.

> I'm a bit confused, however, about how your proposed implementation triggers the `ReferenceError`. Or is there some other analysis the compiler would do before accepting or rejecting the code?

Not sure which part you're referring to, specifically, but there are three parts to this:
 * What the compiler checks: Right now, in a binding group, the compiler checks if every variable bound in the group is only used in deferred positions, like inside closures, and complains otherwise. This analysis doesn't need to change, though I think it could be refined in light of the rest of this proposal.
 * What the compiler generates: In a binding group, every reference to a variable `a` bound in the group is replaced with a call to <code>$init_a(<i>line number of the reference</i>)</code>, and then every declaration of such `a` is wrapped in machinery as in the above. We can carve out exceptions to this if references are known to be unused until after all identifiers are initialized; a binding group comprising only lambdas can be exempted from this rewrite, for example.
 * How the machinery works at run time: every variable in the binding group is first initialized to a sentinel `$undef`, then each variable's initialization function is called one by one. When an initialization function is called for the first time (as indicated by the presence of `$undef`), the variable points to a new sentinel `$indef`, which is used to determine if the initialization function is called a second time before finishing the first invocation. In that case, the ReferenceError is triggered. Otherwise, the variable finally gets assigned its final value, and subsequent calls to the initialization function just return that value.

**Comment by JordanMartinez** [comment] 2021-12-27 15:57
> if we wanted to hack something in, a primitive function named unsafeReference :: forall a. a -> a or something could be a signal to CodeGen not to do the thing.

Ah, that sounds like a good idea.

> Not sure which part you're referring to

I figured it out. I was misunderstanding how these two assignments functioned:
```javascript
a = $indef;
a = f(function () {
      return $init_c(12); // where 12 is the line number of `a = f \_ -> c`
    });
  }
```
The first sets `a` to `$indef`. I read the second line as immediately overwriting the `$indef` assignment to something else. So, I was confused how it would trigger the error. I now realize that we compute `$init_c` before assigning `a` to that value. So, if `$init_c` calls `$init_a` (because it references the `a` in PS code), then `a` would still be assigned to `$indef`, which would trigger the error.

**Comment by MonoidMusician** [comment] 2021-12-28 20:53
Would we need something like strictness analysis (not just dependency analysis) to determine what order to write the declarations in, is that what the issue is?

**Comment by rhendric** [comment] 2021-12-29 19:22
I guess so? I've not heard strictness analysis discussed in the context of already-strict languages, but it seems to be the same basic idea, yeah. The difference is that the primary goal here is determining initialization order, not optimizing away thunks. (Although come to think of it, I guess the `$init` functions I proposed are basically thunks for use only within that binding group.)

**Comment by MonoidMusician** [comment] 2022-01-01 06:48
I found some research in the area: https://arxiv.org/pdf/1811.08134.pdf

It's not clear to me yet if we could get all of what we need from it, particularly to answer the question of “what order should the declarations come in”. Some of the related research mentions graphs can be used to track it more granularly than what that particular paper gives.

**Comment by rhendric** [comment] 2022-01-01 21:39
That paper formalizes the intuitions I had when I was campaigning for rejecting a lot of programs, several comments ago, which will be useful if we go down that path (modulo the distinction between `Guard` and `Return` modes, which I don't think PureScript would make, having only strict data). But unfortunately, the algorithm described there doesn't permit this example:

```purs
ones :: Lazy.List Int
ones = 1 Lazy.: defer \_ -> ones
```

Typing `1 Lazy.: defer \_ -> ones` as `Return` means typing `defer \_ -> ones` as `Guard` (or `Return`, in a `Guard`-less language), means typing `\_ -> ones` as `Dereference`, means typing `ones` as `Dereference`, which is an error inside the binding group of `ones`. (This is just capturing the intuition that the compiler doesn't know that `defer` won't evaluate the lambda.)

I think if we don't want to reject a lot of programs like the above, we'd need to use something closer to one of the related approaches mentioned in the paper, like Boudol [2001], which would integrate deeper into the type system and annotate function parameters with information about how they're used. That would probably involve a change to the format of externs and CoreFn. And even then, there might be edge cases that we'd rather not reject, and we'd have to fall back on a dynamic approach.

**Comment by natefaubion** [comment] 2022-02-27 15:54
Regarding your example solution: you could let-bind the init functions, and replace them with const functions after initialization to avoid additional checks. You've essentially just inlined `Data.Lazy` then. I'm not saying "nay", but you're effectively taking what would happen in a language runtime and inlining it to avoid saying that PureScript requires a runtime 😆. It reminds me a bit of CoffeScript and the way it would duplicate it's runtime functions in every file that required it. I understand that this is fairly light-weight, if noisy. I personally find the language's "no runtime" claim dubious in general, so I'm not opposed to a small runtime for laziness, and then you could potentially have laziness (instead of CBN) for super classes (reducing allocations even more than your float PR).

**Comment by natefaubion** [comment] 2022-03-02 00:54
> I would like to solve this problem for the final 0.15 release, as it is ever-so-slightly breaking and it would free me to do more optimization work in a non-breaking way. Do you think we should try to implement a runtime also on the 0.15 timescale and then use that runtime for this solution? Or implement the solution without a runtime and abstract it into a runtime in future work? Or some other idea?

I think there are several questions that are unclear to me:
* How does the inlined approach affect bundle size?
* What about if it's injected once for every module that needs it (ie. how compact can it be without a runtime module)?
* What performance impact is there, if any (ie. is there any hot code that this might affect)?
* Are there compelling use cases for the "lack of runtime"?

**Comment by rhendric** [comment] 2022-03-02 01:27
Good questions. I can try implementing this without a runtime module (with both the once-per-module and the fully-inlined approaches) and doing some size and performance benchmarks, and then we can be in a better place to decide if the separate runtime module is worth it?

**Comment by rhendric** [comment] 2022-03-05 11:18
Here are some early data on a work-in-progress implementation!

The only variation I implemented so far is the runtime function, injected once per module. I'm testing this first with the benchmarking script from [`language-cst-parser`](https://github.com/natefaubion/purescript-language-cst-parser), using the preliminary 0.15.0 package set (modifying `minibench` to use ES exports).

In all the JS code produced by compiling the benchmark script and all its dependencies, there are 6547 variable declarations (not counting hand-written foreign JS). The implementation makes 142 of these declarations lazy, or about 2%. It converts 252 recursive references to lazy init function calls, or an average of about 1.8 per lazy declaration (this doesn't include the one call that is inserted after all lazy declarations to initialize the variable used by the rest of the program). It also currently suppresses 4 instances of tail-call optimization out of 85, and I haven't yet determined if this is avoidable. Impact on output size is as follows (bundling and minification performed by esbuild):

| | master | patched | change |
|-|---|---|---|
| raw output | 13512 KiB | 13560 KiB | +0.3% |
| minified bundles | 116 KiB | 120 KiB | +4% |
| gzipped minified bundles | 23410 B | 24400 B | +4% |

Using a runtime module might save us a KiB on the minified bundles; only six copies of the runtime function made it into the final bundle for this test, and I expect them to clock in at around 200 bytes each when minified.

Run-time performance does not appear to be impacted in any meaningful way on this test. Here are the raw numbers for two different input files:

| | master | patched |
|-|---|---|
|**PureScript/CST/Lexer.purs**| | |
|mean|40.46 ms|40.10 ms|
|stddev|14.79 ms|14.44 ms|
|min|30.69 ms|30.82 ms|
|max|142.08 ms|137.76 ms|
|**PureScript/CST/Parser.purs**| | |
|mean|69.96 ms|70.14 ms|
|stddev|20.66 ms|21.68 ms|
|min|56.56 ms|57.31 ms|
|max|211.85 ms|220.94 ms|

This was honestly better than I was expecting, and although I hope to try benchmarking this change on a few other tests, if I continue not to see any measurable degradation I will probably not even bother implementing and testing the inlined version.

---

As a second test, I'm looking at the output of the `es-modules` branch of [`halogen-template`](https://github.com/working-group-purescript-es/purescript-halogen-template/tree/es-modules). I don't have a way to measure the runtime performance on this project, but the output size results are as follows:

| | master | patched | change |
|-|---|---|---|
| raw output | 18344 KiB | 18392 KiB | +0.3% |
| minified bundles | 83525 B | 87435 B | +5% |
| gzipped minified bundles | 18533 B | 19446 B | +5% |

The proportions of declarations and references made lazy are comparable to the `language-cst-parser` test, so I won't bother detailing them.

**Comment by natefaubion** [comment] 2022-03-05 14:52
What were the cases where it removed TCO?

**Comment by rhendric** [comment] 2022-03-05 19:46
All four occurrences are in local functions inside the `Data.Map.Internal` module; this example is representative:

  ```purs
  maxNode :: Map k v -> { key :: k, value :: v }
  maxNode = unsafePartial \m -> case m of
    Two _ k' v Leaf -> { key: k', value: v }
    Two _ _ _ right -> maxNode right
    Three _ _ _ _ k' v Leaf -> { key: k', value: v }
    Three _ _ _ _ _ _ right -> maxNode right
  ```

All four local functions use `unsafePartial` in this way, which causes these definitions to be made lazy. We could probably fix this by inlining (erasing) `unsafePartial` before this transformation, though that'd be a little awkward because `unsafePartial` is currently inlined by a CoreImp transformation and the laziness transformation is easiest to write as a CoreFn transformation. Still fairly straightforward to do though, if desired.

Alternatively, I think this could be rewritten as `maxNode = let partialMaxNode m = ... in unsafePartial partialMaxNode` and that would preserve TCO.

**Comment by JordanMartinez** [comment] 2022-04-05 13:39
> Alternatively, I think this could be rewritten as maxNode = let partialMaxNode m = ... in unsafePartial partialMaxNode and that would preserve TCO.

Should this become its own PR?

**Comment by rhendric** [comment] 2022-04-05 18:51
#4283 includes a hack that specifically targets that case:
https://github.com/purescript/purescript/blob/d9324a9581ab563eda7252f5b5c764636f788c41/src/Language/PureScript/CoreFn/Laziness.hs#L111-L112.

I'm a little uncomfortable with how special-casey it is, but given the timing of this PR I didn't want to force additional coordination with the ecosystem. This way, we can decide whether hacks like this one are a good idea at our leisure, and if we decide not, submit the PR to `purescript-ordered-containers` at any time (it doesn't break anything to make that change) and then remove the hack afterwards.

(Also, there could well be other, similar TCO failures in libraries not included in the dependencies of the benchmark I'm running, and if so they would need PRs or their own hacks. If there's a full 0.15 package set ready for testing, I could extend my search to that.)

**Comment by JordanMartinez** [comment] 2022-04-05 19:44
>  If there's a full 0.15 package set ready for testing, I could extend my search to that.)

This one's pretty stable: https://raw.githubusercontent.com/purescript/package-sets/prepare-0.15/src/packages.dhall

**Comment by rhendric** [comment] 2022-04-05 23:57
Thanks! I can confirm that no TCO loops were harmed in the compilation of that package set.

**Closed** 2022-04-14 18:45 UTC
Labels: type: bug
