### ISSUE TITLE
psc-ide-server consuming excessive resources

### ISSUE THREAD

**Issue by garyb** [purescript/purescript#2249] opened 2016-07-25 19:44 UTC
Witness:

![psc-ide-server](https://cloud.githubusercontent.com/assets/693642/17114597/8a9ff79c-52a7-11e6-9f9f-d0b532628b7d.png)

"13" there is 100% usage of one core. I'd say that with 9 gig of RAM is probably excessive considering I'm not actually doing anything at the time this screenshot was taken.

I have no idea what's going on yet, here's all the info I have:
- This is ocurring after opening up a Halogen example in Atom, but doesn't happen with Halogen itself
- The example consists of one 44 line file, so it's not because there's a huge amount of extra stuff present
- There's only one instance of `psc-ide-server` running
- It does appear to still be working - the rebuild is running and errors get highlighted, etc

**Comment by kRITZCREEK** [comment] 2016-07-25 20:01
Which of the examples is it? I can try to reproduce it on linux.

**Comment by garyb** [comment] 2016-07-25 20:17
It's something I'm working on rather than `master`. I just pushed where I'm at with this commit/branch:

https://github.com/garyb/purescript-halogen/tree/90e656f487ba026ee780e2622d7ff6d6a6437c8a

- I encountered the issue with the "intro" example
- I'm using a bower link setup, maybe that's contributing: `bower link` in the main Halogen dir then `bower link purescript-halogen` in `examples/intro`
- This doesn't happen with `pscid`, so maybe it's something specifically that the Atom plugin is doing (I'm on 0.14.6 - the latest)
- The CPU core goes straight to 100%, but it takes a while for the memory usage to build up. Saving bumps it up by a gig or so each time.

The memory usage only ever increases while using `pscid` too, although it doesn't rise as drastically with each save or consume an entire core, so there's some kind of space leak even if the Atom plugin is doing something "wrong".

**Comment by nwolverson** [comment] 2016-07-31 14:28
The one difference that springs to mind in usage of `psc-ide` is that the server is started with source globs. I'd try with the config for source globs set to empty

Otherwise on save I think it just does rebuild of that file, and list imports.

**Comment by sudhirvkumar** [comment] 2016-10-16 05:08
@paf31 @nwolverson 

I use emacs (spacemacs) and psc-ide-server... it works fine for sometime and then it consumes a lot of memory and slows the machine to a grind.. and I have to quit the psc-ide-server and then start it again. would love if this is solved soon

**Comment by sudhirvkumar** [comment] 2017-03-31 22:10
I didn't see psc-ide-server crash or consume excess memory with 0.10.7 and we use PureScript every day/all day! Is this issue still relevant? Is anybody else having this issue?

**Comment by nwolverson** [comment] 2017-04-14 12:17
Noticed with 0.11.3, I had 3 purs executables sitting at 10% cpu each doing nothing at all (again that seems like it could be high usage of one core).

**Comment by cebaa** [comment] 2017-05-02 16:37
Confirmed, right now idling purs.exe (v0.11.4) consumes ~40%. This is across all 12 HT cores, so much more than 1 core. This is with a single instance, used for the editor, `purs ide server ...`, with mem usage relatively constant ~300m. It all seems to work otherwise (completion, building, etc.)

Haphazardly assigning this as a problem showing on Windows only - `pulp build` takes one third of a minute. It has a few deps sure:

```
    "purescript-prelude": "^3.0.0",
    "purescript-console": "^3.0.0",
    "purescript-argonaut": "^3.0.0",
    "purescript-arrays": "^4.0.1",
    "purescript-lists": "^4.1.0",
    "purescript-integers": "^3.0.0",
    "purescript-affjax": "^4.0.0",
    "purescript-string-parsers": "^3.0.1",
    "purescript-node-fs": "^4.0.0",
    "purescript-random": "^3.0.0",
    "purescript-free": "^4.0.0",
    "purescript-node-child-process": "^4.0.0"
```

but still snailish that lad. Remove all the source, same thing. Open the editor, now build takes a whole minute (purs and pulp competing for cpu?)

**Comment by kRITZCREEK** [comment] 2017-05-02 16:46
@cebaa if you add the `--polling` flag to the `purs ide server` invocation, does the idle usage go away? That flag actually turns polling off on Windows.

**Comment by cebaa** [comment] 2017-05-02 17:58
@kRITZCREEK Yes, `--polling` fixes it :100:

I guess a flag is needed for polling in https://github.com/kRITZCREEK/purescript-psc-ide/blob/master/src/PscIde/Server.purs to have this available via editor plugins? 

> It's not a real solution though

It cuts the build time in half, hi5 from me

`pulp psci` also gives some idle cpu usage, about 1/4 to 1/2 of a core looks like.

**Comment by kRITZCREEK** [comment] 2018-02-02 21:02
The last problem mentioned in this issue has been fixed through the introduction of editor-mode, and I don't think I've seen any of the CPU hogging problems for a long time now so I'll close this issue and wait for more specific issues about performance problems.

**Closed by kRITZCREEK** 2018-02-02 21:02 UTC
Labels: bug, needs info, psc-ide

**Comment by fsoikin** [comment] 2018-11-18 01:29
@kRITZCREEK this is happening for me as well. I have tried `--polling`, and it does not seem to create any difference. `purs.bin` CPU usage bounces between 8% and 13% of my 8 cores (meaning 60% to 100% of a single core) with no user activity at all. 

![image](https://user-images.githubusercontent.com/4219105/48667581-6e8d6b80-eaa7-11e8-866f-61e0c8fb6dbd.png)

I'd be happy to gather any sort of diagnostic info or conduct experiments to help resolve this.

**Comment by fsoikin** [comment] 2019-05-14 17:00
How do I resurrect this? Should I file a new issue?

**Comment by hdgarrood** [comment] 2019-05-14 17:19
I think the best way of getting us to look at things is to provide enough information so that it's easy to follow up on; in this case that probably means identifying what diagnostic info would be useful to have and then collecting it.

**Comment by fsoikin** [comment] 2019-05-14 17:38
@hdgarrood that's exactly what I offered to do in the previous comment back in November, but got no response until now.

IDE server doesn't come with any sort of debugging/troubleshooting guidelines (that I could find), but let me try my best just based on my general understanding of what may be helpful:

* This happens on _all_ my projects - big/small, different dependencies, bower/psc-package (haven't tried Spago, because https://github.com/spacchetti/spago/issues/187 - still need to respond to that), with FFI and without, etc. I couldn't find a single configuration where this doesn't happen.
* This has been happening forever, since I had IDE support at all - from 11.7 up to 12.5
* The OS is Windows (as in the original post), the IDE is VSCode
* The same thing happens with the `purs.bin` instance that runs as part of Webpack watcher, via `purs-loader`, with `pscIde: true`.

As I mentioned in my previous post 6 months ago, I'd be happy to gather any sort of diagnostic info or conduct experiments to help resolve this.

**Comment by fsoikin** [comment] 2019-05-14 18:08
More info: I just inspected what the process is actually doing, and discovered that it's just constantly polling every file under `output/` in order. Not reading them, just querying metadata. Presumably to get the "last write" time.

**Comment by garyb** [comment] 2019-05-14 18:48
Hmm, aside from the changes to polling and such that originally fixed this for me, there's "editor mode" now which I think most things use, where it shouldn't be doing anything like what you're describing. 

With "editor mode" it becomes the responsibility of the editor plugin to notify `purs ide` of changes rather than relying on filesystem methods.

**Comment by hdgarrood** [comment] 2019-05-14 18:50
@fsoikin Yes, I did see your comment back in November. To clarify, what I was trying to communicate is that simply offering to collect information will usually not be enough to revive activity; if you want a response it's usually more effective to take the initiative and start actually investigating.

**Comment by fsoikin** [comment] 2019-05-14 19:10
That doesn't seem very fair. With no prior knowledge of how the thing works, I have few options but to ask those who do have such knowledge at least where to start.

**Comment by hdgarrood** [comment] 2019-05-14 19:30
I don't think fairness really comes into it; the fact is that as a maintainer of even a moderately successful OSS project, it's absolutely necessary to be very selective about what you spend your time and attention on. (Of course we all try to help whenever we can, and obviously it would be nice if we could help everyone with everything, but that's just not realistic.)

**Comment by nwolverson** [comment] 2019-05-14 19:38
For reference vscode has an "editor mode" config option which is mapped directly to the flag @garyb mentions. I claimed it would become the default in the future but it seems that future has been a long tim coming

**Comment by mjarosie** [comment] 2020-05-13 00:11
Hi @nwolverson could you give more details on how do you switch on the "editor mode" option in vscode? I'm having exactly the same issue of high CPU usage when I've got vscode with purescript project opened.

**Comment by fsoikin** [comment] 2020-05-13 00:58
@mjarosie it's a setting that is literally called "Editor Mode":

![image](https://user-images.githubusercontent.com/4219105/81759623-31831900-9493-11ea-9336-e1100af42a78.png)

Or in JSON:

```json
{
    "purescript.editorMode": true,
}
```
