### ISSUE TITLE
inferKind: unkinded forall binder

### ISSUE THREAD

**Issue by MonoidMusician** [purescript/purescript#4101] opened 2021-06-04 03:48 UTC
## Description

Getting an internal error while porting dhall-purescript to 0.14.

```
Compiling Dhall.Core.AST.Types
purs: An internal error occurred during compilation: inferKind: unkinded forall binder
Please report this at https://github.com/purescript/purescript/issues
CallStack (from HasCallStack):
  error, called at src/Language/PureScript/Crash.hs:24:3 in purescript-ast-0.1.1.0-BLTG9STKhgqLSa4aQ0dlin:Language.PureScript.Crash
  internalError, called at src/Language/PureScript/TypeChecker/Kinds.hs:221:11 in purescript-0.14.1-C7f9TWdcdK9E6BDMrsSz8r:Language.PureScript.TypeChecker.Kinds
  inferKind, called at src/Language/PureScript/TypeChecker/Kinds.hs:298:25 in purescript-0.14.1-C7f9TWdcdK9E6BDMrsSz8r:Language.PureScript.TypeChecker.Kinds
[etc....................]
purs: thread blocked indefinitely in an MVar operation
```

## To Reproduce

Create a new project with `bower install purescript-newtype`.

In file `src/Aux.purs`:
```purescript
module Aux where

newtype Const :: forall k. Type -> k -> Type
newtype Const a b = Const a

data Unit = Unit

type CONST = Const
type UNIT = CONST Unit
```

In file `src/Main.purs`:
```purescript
module Main where

import Data.Newtype (class Newtype)
import Aux (UNIT)

data VariantF (fs :: Row (Type -> Type))

type Test =
  ( "Foo" :: UNIT
  )

newtype Expr = Expr (VariantF Test)
derive instance newtypeExpr :: Newtype Expr _
```

Then `pulp build` will result in the error:
```
Compiling Aux
Compiling Main
purs: An internal error occurred during compilation: inferKind: unkinded forall binder
Please report this at https://github.com/purescript/purescript/issues
CallStack (from HasCallStack):
  error, called at src/Language/PureScript/Crash.hs:24:3 in purescript-ast-0.1.1.0-BLTG9STKhgqLSa4aQ0dlin:Language.PureScript.Crash
  internalError, called at src/Language/PureScript/TypeChecker/Kinds.hs:221:11 in purescript-0.14.1-C7f9TWdcdK9E6BDMrsSz8r:Language.PureScript.TypeChecker.Kinds
  inferKind, called at src/Language/PureScript/TypeChecker/Kinds.hs:298:25 in purescript-0.14.1-C7f9TWdcdK9E6BDMrsSz8r:Language.PureScript.TypeChecker.Kinds
  checkKind, called at src/Language/PureScript/TypeChecker/Kinds.hs:207:31 in purescript-0.14.1-C7f9TWdcdK9E6BDMrsSz8r:Language.PureScript.TypeChecker.Kinds
  inferKind, called at src/Language/PureScript/TypeChecker/Kinds.hs:298:25 in purescript-0.14.1-C7f9TWdcdK9E6BDMrsSz8r:Language.PureScript.TypeChecker.Kinds
  checkKind, called at src/Language/PureScript/TypeChecker/Kinds.hs:251:13 in purescript-0.14.1-C7f9TWdcdK9E6BDMrsSz8r:Language.PureScript.TypeChecker.Kinds
  inferAppKind, called at src/Language/PureScript/TypeChecker/Kinds.hs:213:7 in purescript-0.14.1-C7f9TWdcdK9E6BDMrsSz8r:Language.PureScript.TypeChecker.Kinds
  inferKind, called at src/Language/PureScript/TypeChecker/Kinds.hs:298:25 in purescript-0.14.1-C7f9TWdcdK9E6BDMrsSz8r:Language.PureScript.TypeChecker.Kinds
  checkKind, called at src/Language/PureScript/TypeChecker/Kinds.hs:251:13 in purescript-0.14.1-C7f9TWdcdK9E6BDMrsSz8r:Language.PureScript.TypeChecker.Kinds
  inferAppKind, called at src/Language/PureScript/TypeChecker/Kinds.hs:213:7 in purescript-0.14.1-C7f9TWdcdK9E6BDMrsSz8r:Language.PureScript.TypeChecker.Kinds
  inferKind, called at src/Language/PureScript/TypeChecker/Kinds.hs:298:25 in purescript-0.14.1-C7f9TWdcdK9E6BDMrsSz8r:Language.PureScript.TypeChecker.Kinds
  checkKind, called at src/Language/PureScript/TypeChecker/Kinds.hs:857:12 in purescript-0.14.1-C7f9TWdcdK9E6BDMrsSz8r:Language.PureScript.TypeChecker.Kinds
purs: thread blocked indefinitely in an MVar operation
```

## Details

Factors that appear significant:
- `UNIT` is defined in terms of `CONST` (the type synonym) not `Const`
- They appear in a different file
- The newtype deriving declaration seems to trigger the error

If you change any one of these things, the error no longer appears. (Instead, you usually get an error about a kind variable `k`, either that it is undefined or that it doesn't unify with `Type`.)

Suffice it to say it is very much an edge case, and easy to work around! Hopefully no one else will run into it. Just wanted to record it.

## PureScript version

0.14.1

**Comment by artemisSystem** [comment] 2021-06-04 15:54
Adding the error i was getting onto here as well, as it seems related and is perhaps the same thing you are describing happens when you change one of the significant factors you mention. (error about `k` not unifying with `Type`). Another notable thing here is that the error gets reported from the wrong file.

## Code To Reproduce

```
module Main where

import Prelude

import Data.Newtype (class Newtype)
import Run (EFFECT, Run)
import Run.Except (EXCEPT)
import Type.Row (type (+))


newtype What = What (Run (EFFECT + EXCEPT Int + ()) Unit)

derive instance what ∷ Newtype What _
```

Resulting error (reported from the `Run.Except` module:
```
Compiling What
[1/1 KindsDoNotUnify] .spago/run/v4.0.0/src/Run/Except.purs:43:41
  43  type EXCEPT e r = (except :: Except e | r)
                                              ^
  Could not match kind
    Type
  with kind
    k
  while checking that type Except @k Int
    has kind t0
  while inferring the kind of ( effect :: Effect
                              , except :: Except @k Int
                              )
  while inferring the kind of Run
                                ( effect :: Effect
                                , except :: Except @k Int
                                )
                                Unit
  while inferring the kind of Newtype What
                                (Run
                                   ( effect :: Effect
                                   , except :: ... Int
                                   )
                                   Unit
                                )
  in type class instance
    Data.Newtype.Newtype What
                         (Run
                            ( effect :: Effect
                            , except :: Except @k Int
                            )
                            Unit
                         )
  where t0 is an unknown type
           Src   Lib   All
Warnings   0     0     0  
Errors     0     1     1  
[error] Failed to build.
```

Removing `EFFECT +` will move the error into the current module, on the Run constructor.
Removing `EXCEPT err + ` solves the error completely.

(+ @MonoidMusician, does the error above look similar to what you're getting when the error is that `k` isn't unifying with `Type`?)

**Comment by MonoidMusician** [comment] 2021-06-04 18:18
Yes this looks related to the second set of errors, thank you!

**Comment by natefaubion** [comment] 2021-06-04 21:38
The examples I've seen here and on Slack seem to all involve Coercible/Newtype as well as deriving. To potentially narrow it down:
* Is this reproducible without involving Coercible?
* Is this reproducible without deriving?

**Comment by artemisSystem** [comment] 2021-06-05 06:46
Yes, looks like it's reproducible without deriving (unless the derived instances in `Run` make a difference):
https://try.purescript.org/?gist=0c1290b31794cb706b6194391e01fbf3

This time, the error is about `k` being undefined. In the earlier example with the derived newtype instance (https://try.purescript.org/?gist=0560c716849e25d706bbb3fd1bc7ebb3), the error is that `k` cannot unify with `Type`

**Comment by natefaubion** [comment] 2021-06-05 15:57
> Yes, looks like it's reproducible without deriving (unless the derived instances in Run make a difference):

I mean a minimal example that does not involve deriving anywhere.

**Comment by natefaubion** [comment] 2021-06-05 16:00
As a point of reference, the original example all in a single file seems to compile fine.

```purescript
module Main where

import Data.Newtype

newtype Const :: forall k. Type -> k -> Type
newtype Const a b = Const a

data Unit = Unit

type CONST = Const
type UNIT = CONST Unit

data VariantF (fs :: Row (Type -> Type))

type Test =
  ( "Foo" :: UNIT
  )

newtype Expr = Expr (VariantF Test)
derive instance newtypeExpr :: Newtype Expr _
```

So I wonder if there's something going on related to externs.

**Comment by JordanMartinez** [comment] 2021-06-06 13:42
Since Nate mentioned a possible externs issue, is the below problem another symptom of the bug's root cause? Or is this a separate issue entirely?

On Pursuit, I was looking at [Type.Data.Symbol](https://pursuit.purescript.org/packages/purescript-typelevel-prelude/6.0.0/docs/Type.Data.Symbol). I then clicked on the `Prim.Symbol` link as found in the "Re-exports from `Prim.Symbol`" header. It led me to this [404 page](https://pursuit.purescript.org/packages/purescript-typelevel-prelude/6.0.0/docs/Prim.Symbol).

**Comment by artemisSystem** [comment] 2021-06-17 16:51
Looks like i'm reproducing this without any deriving now. Here's a minimal example with no dependencies:
```hs
module Aux where

newtype Const :: forall k. Type -> k -> Type
newtype Const a b = Const a

data Unit = Unit

type CONST = Const
type UNIT = CONST Unit
```
```hs
module Main where

import Prim.Coerce (class Coercible)
import Aux (UNIT)

class Newtype :: Type -> Type -> Constraint
class Coercible t a <= Newtype t a | t -> a

data VariantF (fs :: Row (Type -> Type))

type Test =
  ( "Foo" :: UNIT
  )

newtype Expr = Expr (VariantF Test)
instance Newtype Expr (VariantF Test)
```
Here's the error i get:
```

  8  type CONST = Const
                  ^^^^^
  
  Type variable k is undefined.
  
  while inferring the kind of k
  while checking that type k
    has kind Type
  while inferring the kind of Const @k @k Unit
  while inferring the kind of ( "Foo" :: Const @k @k Unit
                              )
  while inferring the kind of VariantF
                                ( "Foo" :: ... @k Unit
                                )
  while inferring the kind of Coercible Expr
                                (VariantF
                                   ( "Foo" :: ... Unit
                                   )
                                )
  while checking that expression #dict Coercible
    has type Coercible$Dict @Type Expr
               (VariantF
                  ( "Foo" :: ... Unit
                  )
               )
  in value declaration $_NewtypeExprVariantFTest_0
```
(0.14.2)

**Comment by artemisSystem** [comment] 2021-06-18 17:27
Ah! I feel like i'm narrowing it down quite a bit here. It doesn't have anything to do with coercible, the problem is with subclasses (But Newtype is a subclass of Coercible). Here's another repro without deriving and without Coercible, no dependencies:
```
module Aux where

newtype Const :: forall k. Type -> k -> Type
newtype Const a b = Const a

data Unit = Unit

type UNIT :: forall k. k -> Type
type UNIT = Const Unit
```
```
module Main where

import Prim.Coerce (class Coercible)
import Aux

class ClassA :: Type -> Type -> Constraint
class ClassA t a | t -> a

class ClassB :: Type -> Type -> Constraint
class ClassA t a <= ClassB t a | t -> a

data VariantF :: Row (Type -> Type) -> Type
data VariantF fs
data Expr

instance ClassA Expr (VariantF ("Foo" :: UNIT))
instance ClassB Expr (VariantF ("Foo" :: UNIT))
```
Error:
```
  8  type UNIT :: forall k. k -> Type
                            ^
  
  Type variable k is undefined.
  
  while inferring the kind of k
  while checking that type k
    has kind Type
  while inferring the kind of Const @k Unit
  while inferring the kind of ( "Foo" :: Const @k Unit
                              )
  while inferring the kind of VariantF
                                ( "Foo" :: Const @k Unit
                                )
  while inferring the kind of ClassA Expr
                                (VariantF
                                   ( "Foo" :: ... Unit
                                   )
                                )
  while checking that expression #dict ClassA
    has type Record (() @Type)
  in value declaration $_ClassBExprVariantFRow_1
```
Looks like functional dependencies need to be there for this to occur

**Comment by MonoidMusician** [comment] 2021-06-20 02:55
Thanks for the examples! Here's a more minified version of `Main.purs`. The fundeps were a red herring, they just resulted in a different error being thrown first when using rows, but I removed the rows:
```purescript
module Main where

import Prim.Coerce (class Coercible)
import Aux

class ClassA :: Type -> Type -> Constraint
class ClassA t a

class ClassB :: Type -> Type -> Constraint
class ClassA t a <= ClassB t a

data VariantF :: (Type -> Type) -> Type
data VariantF fs
data Expr

instance a :: ClassA Expr (VariantF UNIT)
instance b :: ClassB Expr (VariantF UNIT)
```

When I comment out the second instance, or make other changes so it should compile (such as inlining `UNIT` in the second instance), I get a weird crash, I guess I'll file a separate issue for it later, once I've verified it with latest `purs`:
```
purs: An internal error occurred during compilation: Unknown super class in TypeClassDeclaration
Please report this at https://github.com/purescript/purescript/issues
CallStack (from HasCallStack):
  error, called at src/Language/PureScript/Crash.hs:24:3 in purescript-ast-0.1.0.0-Gtmwmu4N43KCxo7Qi9BiwQ:Language.PureScript.Crash
  internalError, called at src/Language/PureScript/TypeChecker.hs:176:20 in purescript-0.14.0-7Hhf71YbBduFTQoNCniNIc:Language.PureScript.TypeChecker
purs: thread blocked indefinitely in an MVar operation
```

**Comment by toastal** [comment] 2021-07-02 06:26
I'm trying to upgrade to v0.14 and ran into this issue. I'm not as wise as y'all, so is there any info on even where to start with troubleshooting and attacking this? I don't get a line number or anything

```console
$ spago build
...
Compiling Forms.BookShowing
purs: An internal error occurred during compilation: inferKind: unkinded forall binder
Please report this at https://github.com/purescript/purescript/issues
CallStack (from HasCallStack):
  error, called at src/Language/PureScript/Crash.hs:23:3 in purescript-cst-0.2.0.0-34LnaRhFexNFoVuKr2bzgC:Language.PureScript.Crash
  internalError, called at src/Language/PureScript/TypeChecker/Kinds.hs:220:11 in purescript-0.14.2-AI3cTNrOsn67i4llhGt6w2:Language.PureScript.TypeChecker.Kinds
  inferKind, called at src/Language/PureScript/TypeChecker/Kinds.hs:297:25 in purescript-0.14.2-AI3cTNrOsn67i4llhGt6w2:Language.PureScript.TypeChecker.Kinds
  checkKind, called at src/Language/PureScript/TypeChecker/Kinds.hs:207:19 in purescript-0.14.2-AI3cTNrOsn67i4llhGt6w2:Language.PureScript.TypeChecker.Kinds
  inferKind, called at src/Language/PureScript/TypeChecker/Kinds.hs:297:25 in purescript-0.14.2-AI3cTNrOsn67i4llhGt6w2:Language.PureScript.TypeChecker.Kinds
  checkKind, called at src/Language/PureScript/TypeChecker/Kinds.hs:250:13 in purescript-0.14.2-AI3cTNrOsn67i4llhGt6w2:Language.PureScript.TypeChecker.Kinds
  inferAppKind, called at src/Language/PureScript/TypeChecker/Kinds.hs:212:7 in purescript-0.14.2-AI3cTNrOsn67i4llhGt6w2:Language.PureScript.TypeChecker.Kinds
  inferKind, called at src/Language/PureScript/TypeChecker/Kinds.hs:297:25 in purescript-0.14.2-AI3cTNrOsn67i4llhGt6w2:Language.PureScript.TypeChecker.Kinds
  checkKind, called at src/Language/PureScript/TypeChecker/Kinds.hs:250:13 in purescript-0.14.2-AI3cTNrOsn67i4llhGt6w2:Language.PureScript.TypeChecker.Kinds
  inferAppKind, called at src/Language/PureScript/TypeChecker/Kinds.hs:212:7 in purescript-0.14.2-AI3cTNrOsn67i4llhGt6w2:Language.PureScript.TypeChecker.Kinds
  inferKind, called at src/Language/PureScript/TypeChecker/Kinds.hs:297:25 in purescript-0.14.2-AI3cTNrOsn67i4llhGt6w2:Language.PureScript.TypeChecker.Kinds
  checkKind, called at src/Language/PureScript/TypeChecker/Kinds.hs:206:31 in purescript-0.14.2-AI3cTNrOsn67i4llhGt6w2:Language.PureScript.TypeChecker.Kinds
  inferKind, called at src/Language/PureScript/TypeChecker/Kinds.hs:297:25 in purescript-0.14.2-AI3cTNrOsn67i4llhGt6w2:Language.PureScript.TypeChecker.Kinds
  checkKind, called at src/Language/PureScript/TypeChecker/Kinds.hs:250:13 in purescript-0.14.2-AI3cTNrOsn67i4llhGt6w2:Language.PureScript.TypeChecker.Kinds
  inferAppKind, called at src/Language/PureScript/TypeChecker/Kinds.hs:212:7 in purescript-0.14.2-AI3cTNrOsn67i4llhGt6w2:Language.PureScript.TypeChecker.Kinds
  inferKind, called at src/Language/PureScript/TypeChecker/Kinds.hs:297:25 in purescript-0.14.2-AI3cTNrOsn67i4llhGt6w2:Language.PureScript.TypeChecker.Kinds
  checkKind, called at src/Language/PureScript/TypeChecker/Kinds.hs:250:13 in purescript-0.14.2-AI3cTNrOsn67i4llhGt6w2:Language.PureScript.TypeChecker.Kinds
  inferAppKind, called at src/Language/PureScript/TypeChecker/Kinds.hs:212:7 in purescript-0.14.2-AI3cTNrOsn67i4llhGt6w2:Language.PureScript.TypeChecker.Kinds
  inferKind, called at src/Language/PureScript/TypeChecker/Kinds.hs:297:25 in purescript-0.14.2-AI3cTNrOsn67i4llhGt6w2:Language.PureScript.TypeChecker.Kinds
  checkKind, called at src/Language/PureScript/TypeChecker/Kinds.hs:856:12 in purescript-0.14.2-AI3cTNrOsn67i4llhGt6w2:Language.PureScript.TypeChecker.Kinds
purs: thread blocked indefinitely in an MVar operation

[info] Build succeeded.
```

**Comment by MonoidMusician** [comment] 2021-07-02 15:45
What I did was literally remove chunks of code from the offending file (the last one being compiled) in order to narrow down which section was causing it. Of course you have to be careful to not cause other errors that overshadow it, but with enough patience you should be able to narrow it down like I did.

But if you don’t need the polykinds, you could start by fixing all the warnings about signatures without polykinds by defaulting to `Type` (as was done before polykinds), and that would probably fix the issue too.

**Comment by toastal** [comment] 2021-07-02 16:26
So far the big issue has been a lack of kind signatures for my Formless stuff, but even still it's a mess to debug, and there's no "kind holes" I believe.

**Comment by rhendric** [comment] 2021-07-02 17:10
I second the recommendation to inline type synonyms, and I would narrow your search to:
* type synonyms defined in another module
* that are used somehow in a class instance
  * including, if the instance is derived, any code that the compiler would generate (so look inside newtypes if deriving a newtype instance, e.g.)
* where the class has a superclass

**Comment by rhendric** [comment] 2021-07-02 17:12
And if you discover that the issue is caused by something that doesn't fall in the above description, please let me know, because it'll mean I need to add another test case to my pending fix for this issue!

**Comment by toastal** [comment] 2021-07-03 09:24
Another issue I found was empty rows

```purs
-- Don’t forget this kind signature
type ChildSlots = () ∷ Row Type
```

Originally I was keeping these aliases around to make some things easier to extend in the future. I substituted most of these with `()` now knowing I'd likely never _actually_ change this. Now the syntax reminds me of Dhall.

**Closed** 2021-07-26 05:40 UTC
Labels: bug
