### ISSUE TITLE
Types with the same name should use module prefix in error messages

### ISSUE THREAD

**Issue by user471** [purescript/purescript#1897] opened 2016-02-23 14:46 UTC
```
import ModuleA as A
import ModuleB as B

test :: A.X
test = B.Bar

module ModuleA where

data X = Foo

module ModuleB where

data X = Bar
```
```
 Could not match type

    X

  with type

    X
```
should be 
```
 Could not match type

    ModuleA.X

  with type

    ModuleB.X
```

**Comment by AppShipIt** [comment] 2016-02-23 14:58
This is kinda valuable feedback for what I want to tackle. Could we tag these something like `messages`?

**Comment by hdgarrood** [comment] 2016-02-23 15:28
There is an `error-message` tag already. I think this is a dupe of #1647.

**Comment by garyb** [comment] 2016-02-23 15:32
Yep, this is #1647 again

**Closed by garyb** 2016-02-23 15:32 UTC

**Comment by AppShipIt** [comment] 2016-02-23 15:37
Thanks for the heads up @hdgarrood!
