### ISSUE TITLE
Memory usage on low memory devices

### ISSUE THREAD

**Issue by kika** [purescript/purescript#2259] opened 2016-07-31 02:23 UTC
Reported by @codec-abc and reproduced by me.
1. Go to https://c9.io and create a Node.js workspace .It will have 512MB of memory and 2G of disk space
2. Log onto you workspace and open the terminal (bottom panel)
3. `git clone https://github.com/c-j-s/hello-purescript.git`
4. `npm install -g purescript bower pulp`
5. `bower install`
6. `time pulp build`  It should take from 1m30s to 2m30s 
7. `time pulp build +RTS -A1g -RTS` takes a few seconds, **pulp reports "Build successful" but in fact the `psc` process has been killed by OOM (Out Of Memory) killer.**
8. Instead of `1g` I went all the way down to `200m` and the result is that it takes longer and longer (up to 13min at `200m`) but the `psc` process is still being killed by OOM.

These spikes from left to right - `480m`, `400m`, `300m` and finally `200m` which is still running:
![image](https://cloud.githubusercontent.com/assets/207889/17274207/de042476-568a-11e6-8b79-1cd83b458a8a.png)

This is a full 13 minutes of `200m` run:
![image](https://cloud.githubusercontent.com/assets/207889/17274208/1034bde8-568b-11e6-9cbc-32db589ab914.png)

**Comment by TRManderson** [comment] 2016-08-14 10:19
Using psc 0.9.3, nodejs 4.4.7, I ran:

`pulp init && pulp build`

I'm on a Joyent SmartDC zone running Ubuntu 14.04 with 1GB of RAM.

I'm currently 140 CPU-minutes into the build, with no sign of the build completing any time soon.

**Comment by paf31** [comment] 2016-10-01 22:33
Does it help to run with `+RTS -N1` at all? Maybe this is related to the Trusty issue in Travis.

**Comment by TRManderson** [comment] 2016-10-02 13:48
Yes, using that RTS option appears to make the issue disappear entirely. It dropped our purescript build time on CircleCI from 5 minutes to 5 seconds. (https://circleci.com/gh/UQComputingSociety/uqcs-hubot/22).

**Comment by gbaz** [comment] 2016-11-08 15:10
related? https://github.com/purescript/purescript/issues/1880

**Comment by hdgarrood** [comment] 2019-02-17 15:23
I can't reproduce this with v0.12.2. Running

```
$ purs compile 'src/**/*.purs' 'bower_components/*/src/**/*.purs' 
```

either locally or in a cloud 9 workspace in that project succeeds in around one second. Even when I limit the maximum heap size to 50MB and limit the allocation area to 100KB via the following command it still succeeds:

```
$ purs compile 'src/**/*.purs' 'bower_components/*/src/**/*.purs' +RTS -A100k -M50m
```

I think this may have been fixed by the performance and memory usage improvements I contributed to the Glob library a while back. I'm going to close for now but please do continue to open issues if you're seeing any performance issues like this.

**Closed by hdgarrood** 2019-02-17 15:23 UTC
Labels: bug, needs info
