### ISSUE TITLE
Compiler crashes when provided with an incorrect type rather than providing error message

### ISSUE THREAD

**Issue by smartermaths** [purescript/purescript#4550] opened 2024-08-03 09:59 UTC
## Description

purs: An internal error occurred during compilation: unifyTypes: unspecified skolem scope
Please report this at https://github.com/purescript/purescript/issues
CallStack (from HasCallStack):
  error, called at src/Language/PureScript/Crash.hs:10:3 in purescript-0.15.15-A1Hsm5jzdq3K6f9tg0KeFN:Language.PureScript.Crash
  internalError, called at src/Language/PureScript/TypeChecker/Unify.hs:124:12 in purescript-0.15.15-A1Hsm5jzdq3K6f9tg0KeFN:Language.PureScript.TypeChecker.Unify

## To Reproduce

```
import GraphQL.FunDeps (GraphQLClientAff)

type Env2 = { graphQLClientAff :: GraphQLClientAff }
newtype AppM a = AppM (ReaderT Env2 Aff a)  

runAppM :: Env2 -> AppM ~> Aff
runAppM e (AppM m) = runReaderT m e
 
derive newtype instance functorAppM :: Functor AppM
--derive instance newtypeAppM :: Newtype (AppM a) _
```

Note: this crash will also happen when deriving Apply, Monad, and others, but not when deriving Newtype - see expected behaviour.

## Expected behavior

The compiler should provide an error message, rather than crash.  And in fact if I comment out the Functor (or Apply, Monad, etc) derivation and derive the Newtype, the compiler does not crash, but does indeed provide an error message:

[1/1 InvalidInstanceHead] src/Type/CreateUser.purs:60:1

      derive instance newtypeAppM :: Newtype (AppM a) _
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  Type class instance head is invalid due to use of type
    forall operation gql i o. GraphQLReqRes operation gql i o => IsSymbol gql => WriteForeign (Record i) => ReadForeign (Record o) => Gql operation -> Record i -> Aff ...
  All types appearing in instance declarations must be of the form T a_1 .. a_n, where each type a_i is of the same form, unless the type is fully determined by other type class arguments via functional dependencies.
  in type class instance
    Data.Newtype.Newtype (AppM a)
                         (ReaderT Env2 Aff a)

## Additional context

None

## PureScript version

0.15.15

**Comment by garyb** [comment] 2024-08-03 13:24
Is `GraphQLClientAff ` a synonym for the
```
forall operation gql i o. GraphQLReqRes operation gql i o => IsSymbol gql => WriteForeign (Record i) => ReadForeign (Record o) => Gql operation -> Record i -> Aff ...
```
mentioned in the other error?

**Comment by smartermaths** [comment] 2024-08-03 15:17
Yes!  I didn't write it - it is from the package [purescript-graphql-fundeps](https://github.com/rowtype-yoga/purescript-graphql-fundeps).  

```
GraphQLClientAff :: ∀ (operation ∷ GraphQL) (gql ∷ Symbol) (i ∷ Row Type) (o ∷ Row Type). GraphQLReqRes operation gql i o ⇒ IsSymbol gql ⇒ WriteForeign (Record i) ⇒ ReadForeign (Record o) ⇒ Gql operation → Record i → Aff (Record o)
```

**Comment by rhendric** [comment] 2024-08-03 16:58
I think this is a dupe of #3681?

**Comment by garyb** [comment] 2024-08-03 17:35
> I think this is a dupe of #3681?

Yeah :+1: looks like the same issue, a `forall` in the type synonym.

Thanks for the report! I'm not aware of a workaround for it unfortunately.

**Closed by garyb** 2024-08-03 17:35 UTC
Labels: type: bug
