### ISSUE TITLE
pass 3rd party JS static checkers

### ISSUE THREAD

**Issue by raould** [purescript/purescript#1939] opened 2016-03-10 00:24 UTC
It would be super hyper intergalactically keen in my mind if the JS generated from PureScript passed some other static checkers with flying colors. This would help greatly in supporting the idea of including PureScript in already existing JS based projects. The top 2 in my personal opinion are:
1) [Facebook Flow](http://flowtype.org/) 
2) [ESLint](http://eslint.org/)

**Comment by AppShipIt** [comment] 2016-03-10 00:30
I think this is effectively a dupe of purescript/roadmap#42. I can't remember where I commented but the hurdle seems to be that JavaScript types are structural (expose a `length` member) whereas PS types are behavioral (accepted by a `length` function). Perhaps it might work with marker interfaces? Regardless it's best discussed in roadmap.

**Comment by kRITZCREEK** [comment] 2016-03-10 00:30
I don't think trying to pass the Flow typechecker makes a lot of sense for PureScript output. 

Because the compiler can use the type information available at compile time it doesn't need to keep the information around for runtime. It can also make assumptions about the potential input to functions which would usually not be possible for handwritten js.

**Comment by paf31** [comment] 2016-03-10 00:30
Does it not? Do you have some example failing output from those static checkers?

I'm not concerned about Flow, but I'd like the output to pass ES Lint.

**Comment by AppShipIt** [comment] 2016-03-10 00:33
> I'd like the output to pass ES Lint.

Ah thanks for the clarification! @raould Perhaps an example repo with config and output might help.

**Comment by raould** [comment] 2016-03-10 00:36
Pretty much ll I did was try to flow check the output of the getting started hello world example. You have to put "// @flow" at the top of the generated .js file and then you can do "flow code.js" and it will spit out a lot of errors. Ditto only more so if you use e.g. the "eslint-config-standard" with eslint on the file.

e.g. first error from Flow:
```
/Volumes/OS/Users/jonslenk/Dev/purescript/purescript/Test/code.js:3:194,199: assignment of property `code`
Error:
/Volumes/OS/Users/jonslenk/Dev/purescript/purescript/Test/code.js:3:196,199: property `code`
Property not found in
/private/tmp/flow/flowlib_3ab00c67/core.js:279:1,284:1: Error
```

**Comment by paf31** [comment] 2016-03-10 00:37
Can you please also paste the JS?

**Comment by raould** [comment] 2016-03-10 00:38
It is on line 3, not 200. :-)
```
// @flow

(function e(t,n,r){function s(o,u){if(!n[o]){if(!t[o]){var a=typeof require=="function"&&require;if(!u&&a)return a(o,!0);if(i)return i(o,!0);var f=new Error("Cannot find module '"+o+"'");throw f.code="MODULE_NOT_FOUND",f}var l=n[o]={exports:{}};t[o][0].call(l.exports,function(e){var n=t[o][1][e];return s(n?n:e)},l,l.exports,e,t,n,r)}return n[o].exports}var i=typeof require=="function"&&require;for(var o=0;o<r.length;o++)s(r[o]);return s})({"/Volumes/OS/Users/jonslenk/Dev/purescript/purescript/Test/output/Control.Monad.Eff.Console/foreign.js":[function(require,module,exports){
/* global exports, console */
"use strict";
```

**Comment by raould** [comment] 2016-03-10 00:41
And ESLint with "standard" rules:
```
eslint /Volumes/OS/Users/mehithere/Dev/purescript/purescript/Test/code.js |head

/Volumes/OS/Users/mehithere/Dev/purescript/purescript/Test/code.js
     3:12   error  Missing space before function parentheses                                                                                                   space-before-function-paren
     3:14   error  A space is required after ','                                                                                                               comma-spacing
     3:16   error  A space is required after ','                                                                                                               comma-spacing
     3:19   error  Missing space before opening brace                                                                                                          space-before-blocks
     3:19   error  Requires a space after '{'                                                                                                                  block-spacing
     3:30   error  Missing space before function parentheses                                                                                                   space-before-function-paren
     3:32   error  A space is required after ','                                                                                                               comma-spacing
     3:35   error  Requires a space after '{'                                                                                                                  block-spacing
events.js:141
      throw er; // Unhandled 'error' event
      ^
```

**Comment by paf31** [comment] 2016-03-10 00:41
That's browserify code.

**Comment by raould** [comment] 2016-03-10 00:44
Ah, ok re: Browserify. That's a fine point technically probably, but I dunno where to go with it. 
"As a regular Dev trying to use PureScript /
and maybe hoping to get fellow Devs to use it at work /
I probably need it to Just Work with Flow or ESLint or something /
And I don't want to have to know the inner organization or finger pointing /
I just want The Output to pass."

:-)

**Comment by paf31** [comment] 2016-03-10 00:46
I understand the concern, but this isn't a compiler issue. The fault lies in one of Browserify, Flow or the configuration, so I think the issue belongs there.

Try running the direct output of `psc` through `flow`, you'll probably have more success.

**Closed by paf31** 2016-03-10 00:46 UTC

**Comment by raould** [comment] 2016-03-10 00:47
Thanks, I see what you mean.

**Comment by AppShipIt** [comment] 2016-03-10 00:49
I'd reiterate if you still encounter warnings and could provide a separate repo perhaps we could create tickets for specific ESLint rules.

**Comment by hdgarrood** [comment] 2016-03-10 13:04
I'm not sure I understand why this is an issue; the way I see it, things like ESLint and Flow are designed to be run on code written by humans, not compiler output. Is it feasible to ask those tools to check just your project's hand-written JavaScript, and ignore `psc` output?

**Comment by joneshf** [comment] 2016-03-10 15:15
@hdgarrood I think there are at least a few times when it's appropriate to check the output of the compiler:

* Changing the compiler version.
* If I remember right, there have also been one or two bugs with the generated output over the years. So maybe a little piece of mind there is worth it.
* It also lets you ensure your interop is still good. If you're bringing bits of ps into the project (which it sounds like @raould is doing), you can keep some sanity if you know your handwritten code interacts properly with the compiler generated code.

**Comment by natefaubion** [comment] 2016-03-10 15:22
ESLint is a highly configurable linter, though. I don't think its practical to assume we can make the compiler output match everyone's ESLint settings. "Standard" is just one opinionated configuration (and hardly the standard). Single quotes vs double quotes, semicolons, indentation, spaces around braces, etc. There are so many rules that are organization specific, and the ones listed in the above report have no impact on code quality. If you are linting compiler output, I think it's just best to just configure it to ignore those kinds of lints and focus on important ones (like using an undefined variable).

**Comment by joneshf** [comment] 2016-03-10 15:41
Yeah, exactly.

**Comment by paf31** [comment] 2016-03-10 16:16
See the core libraries, I think we use ESLint there.

**Comment by hdgarrood** [comment] 2016-03-10 16:18
Only on the FFI files though, right?

**Comment by paf31** [comment] 2016-03-10 16:19
I'm not sure, I just know I've seen it in the build scripts.

**Comment by hdgarrood** [comment] 2016-03-10 16:20
Prelude uses jscs and jshint but only on the FFI files, we don't do any linting of the `psc` output. See: https://github.com/purescript/purescript-prelude/blob/a2155867cb2f6542aca789aadd907a6466f41814/package.json. I am fairly sure that all the other core libraries are the same too.

**Comment by garyb** [comment] 2016-03-10 16:41
Yep, just on the FFI files, not the compilation products.
