### ISSUE TITLE
Feature request: an option to fully qualify type names when explaining 'types do not unify'

### ISSUE THREAD

**Issue by jjl** [purescript/purescript#3252] opened 2018-02-24 19:46 UTC
It's a bit mad trying to debug things like
```
 Could not match type
         
    Query
         
  with type
         
    Query
```

**Comment by garyb** [comment] 2018-02-24 19:54
Duplicate of #1647 🙂

**Closed by garyb** 2018-02-24 19:54 UTC

**Comment by jjl** [comment] 2018-02-24 19:55
Haha, I love that you were having this problem with the exact same name as me, presumably because Halogen :)

**Comment by garyb** [comment] 2018-02-24 19:56
Yep, exactly 😆

**Comment by i-am-the-slime** [comment] 2018-05-24 14:36
Me too :rofl:
