### ISSUE TITLE
Inferred types of record fields should not be polymorphic

### ISSUE THREAD

**Issue by csabahruska** [purescript/purescript#1110] opened 2015-05-09 00:14 UTC
``` purescript
module Bug where

-- from purescript-maps
foreign import data StrMap :: * -> *
foreign import empty "" :: forall a. StrMap a
foreign import singleton "" :: forall a. String -> a -> StrMap a

-- from my code
type R = {f :: StrMap Number}

funA :: forall m . (Monad m) => m R
--funA = return {f:singleton "" 0} -- GOOD
funA = return {f:empty} -- BUG with this message:
```

``` text
Error in module Bug:
Error in value declaration funA:
Error checking that type
  u1499 u1498
subsumes type
  m1497 { f :: Bug.StrMap Prim.Number }
Error at bug2.purs line 17, column 1 - line 17, column 23:
  Cannot unify type
    a1501
  with type
    Prim.Number
See https://github.com/purescript/purescript/wiki/Error-Code-ErrorUnifyingTypes for more information, or to contribute content related to this error.
```

**Comment by paf31** [comment] 2015-11-14 18:44
Moving to 0.9.

**Comment by coot** [comment] 2017-02-09 18:54
I analyzed the bug.  Here is a printout of `unify` calls:

```
unifyTypes
	TypeConstructor (Qualified (Just (ModuleName [ProperName {runProperName = "Prim"}])) (ProperName {runProperName = "Function"}))
	TypeConstructor (Qualified (Just (ModuleName [ProperName {runProperName = "Prim"}])) (ProperName {runProperName = "Function"}))

unifyTypes
	TypeApp (TypeConstructor (Qualified (Just (ModuleName [ProperName {runProperName = "Prim"}])) (ProperName {runProperName = "Record"}))) (RCons (Label {runLabel = "f"}) (ForAll "a" (TypeApp (TypeConstructor (Qualified (Just (ModuleName [ProperName {runProperName = "Bug"}])) (ProperName {runProperName = "StrMap"}))) (TypeVar "a")) (Just (SkolemScope {runSkolemScope = 2}))) REmpty)
	TUnknown 1

unifyTypes
	TypeApp (TUnknown 0) (TUnknown 1)
	TypeApp (Skolem "m" 0 (SkolemScope {runSkolemScope = 1}) (Just (SourceSpan {spanName = "/home/marcin/purescript/rec-error/src/Main.purs", spanStart = SourcePos {sourcePosLine = 20, sourcePosColumn = 1}, spanEnd = SourcePos {sourcePosLine = 20, sourcePosColumn = 27}}))) (TypeApp (TypeConstructor (Qualified (Just (ModuleName [ProperName {runProperName = "Prim"}])) (ProperName {runProperName = "Record"}))) (RCons (Label {runLabel = "f"}) (TypeApp (TypeConstructor (Qualified (Just (ModuleName [ProperName {runProperName = "Bug"}])) (ProperName {runProperName = "StrMap"}))) (TypeConstructor (Qualified (Just (ModuleName [ProperName {runProperName = "Prim"}])) (ProperName {runProperName = "Number"})))) REmpty))

unifyTypes
	TUnknown 0
	Skolem "m" 0 (SkolemScope {runSkolemScope = 1}) (Just (SourceSpan {spanName = "/home/marcin/purescript/rec-error/src/Main.purs", spanStart = SourcePos {sourcePosLine = 20, sourcePosColumn = 1}, spanEnd = SourcePos {sourcePosLine = 20, sourcePosColumn = 27}}))

unifyTypes
	TypeApp (TypeConstructor (Qualified (Just (ModuleName [ProperName {runProperName = "Prim"}])) (ProperName {runProperName = "Record"}))) (RCons (Label {runLabel = "f"}) (ForAll "a" (TypeApp (TypeConstructor (Qualified (Just (ModuleName [ProperName {runProperName = "Bug"}])) (ProperName {runProperName = "StrMap"}))) (TypeVar "a")) (Just (SkolemScope {runSkolemScope = 2}))) REmpty)
	TypeApp (TypeConstructor (Qualified (Just (ModuleName [ProperName {runProperName = "Prim"}])) (ProperName {runProperName = "Record"}))) (RCons (Label {runLabel = "f"}) (TypeApp (TypeConstructor (Qualified (Just (ModuleName [ProperName {runProperName = "Bug"}])) (ProperName {runProperName = "StrMap"}))) (TypeConstructor (Qualified (Just (ModuleName [ProperName {runProperName = "Prim"}])) (ProperName {runProperName = "Number"})))) REmpty)

unifyTypes
	TypeConstructor (Qualified (Just (ModuleName [ProperName {runProperName = "Prim"}])) (ProperName {runProperName = "Record"}))
	TypeConstructor (Qualified (Just (ModuleName [ProperName {runProperName = "Prim"}])) (ProperName {runProperName = "Record"}))

unifyTypes
	RCons (Label {runLabel = "f"}) (ForAll "a" (TypeApp (TypeConstructor (Qualified (Just (ModuleName [ProperName {runProperName = "Bug"}])) (ProperName {runProperName = "StrMap"}))) (TypeVar "a")) (Just (SkolemScope {runSkolemScope = 2}))) REmpty
	RCons (Label {runLabel = "f"}) (TypeApp (TypeConstructor (Qualified (Just (ModuleName [ProperName {runProperName = "Bug"}])) (ProperName {runProperName = "StrMap"}))) (TypeConstructor (Qualified (Just (ModuleName [ProperName {runProperName = "Prim"}])) (ProperName {runProperName = "Number"})))) REmpty

unifyTypes
	ForAll "a" (TypeApp (TypeConstructor (Qualified (Just (ModuleName [ProperName {runProperName = "Bug"}])) (ProperName {runProperName = "StrMap"}))) (TypeVar "a")) (Just (SkolemScope {runSkolemScope = 2}))
	TypeApp (TypeConstructor (Qualified (Just (ModuleName [ProperName {runProperName = "Bug"}])) (ProperName {runProperName = "StrMap"}))) (TypeConstructor (Qualified (Just (ModuleName [ProperName {runProperName = "Prim"}])) (ProperName {runProperName = "Number"})))

unifyTypes
	TypeApp (TypeConstructor (Qualified (Just (ModuleName [ProperName {runProperName = "Bug"}])) (ProperName {runProperName = "StrMap"}))) (Skolem "a" 1 (SkolemScope {runSkolemScope = 2}) Nothing)
	TypeApp (TypeConstructor (Qualified (Just (ModuleName [ProperName {runProperName = "Bug"}])) (ProperName {runProperName = "StrMap"}))) (TypeConstructor (Qualified (Just (ModuleName [ProperName {runProperName = "Prim"}])) (ProperName {runProperName = "Number"})))

unifyTypes
	TypeConstructor (Qualified (Just (ModuleName [ProperName {runProperName = "Bug"}])) (ProperName {runProperName = "StrMap"}))
	TypeConstructor (Qualified (Just (ModuleName [ProperName {runProperName = "Bug"}])) (ProperName {runProperName = "StrMap"}))

unifyTypes
	Skolem "a" 1 (SkolemScope {runSkolemScope = 2}) Nothing
	TypeConstructor (Qualified (Just (ModuleName [ProperName {runProperName = "Prim"}])) (ProperName {runProperName = "Number"}))

Error found:
in module Bug
at /home/marcin/purescript/rec-error/src/Main.purs line 20, column 12 - line 20, column 27

  Could not match type
      
    a1
      
  with type
          
    Number
          

while trying to match type StrMap a1
  with type StrMap Number
while checking that expression pure { f: empty
                                    }         
  has type m0                    
             { f :: StrMap Number
             }                   
in value declaration funError

where m0 is a rigid type variable
        bound at line 20, column 1 - line 20, column 27
      a1 is a rigid type variable

See https://github.com/purescript/documentation/blob/master/errors/TypesDoNotUnify.md for more information,
or to contribute content related to this error.
```

The problem is that `Skolem` does not unify with any other type, while in this case it should specialize according to the last line:
```
unifyTypes
	Skolem "a" 1 (SkolemScope {runSkolemScope = 2}) Nothing
	TypeConstructor (Qualified (Just (ModuleName [ProperName {runProperName = "Prim"}])) (ProperName {runProperName = "Number"}))
```

As a solution we could add `Skolem` resolutions to the `Environment` and unify them.  I might not understand the type checker in its full depth yet: maybe the errors lies in the fact the `unifyTypes` function should receive `TUnknown` instead of `Skolem`.

**Comment by paf31** [comment] 2017-02-09 19:56
Thanks for the report. I'll summarize the problem as best I can:

- Inferring the type of a record literal involves inferring the type of its properties.
- If a property is a `Var`, i.e. the name of a polymorphic function, then its inferred type might be polymorphic.
- We generally don't want to have the inferred types of properties be polymorphic, unless the user explicitly requests it, by adding a type annotation for example.
- If we infer a polymorphic type, and that type gets unified with some other type, then it will be skolemized, hence the error.

So the solution is to add a special case for the `Var` constructor, which is the only way in which a polymorphic type can be inferred for a property. That's what I've done in my PR.

**Comment by coot** [comment] 2017-02-09 21:03
@paf31 thanks, that makes it clear. I'll look into the patch.

**Closed** 2017-02-11 20:49 UTC
Labels: bug, typechecker
