### ISSUE TITLE
Installing purescript 0.12.5 via npm hangs

### ISSUE THREAD

**Issue by nmaehlmann** [purescript/purescript#3697] opened 2019-07-08 17:23 UTC
The behaviour can be observed when trying to install a 0.12.x version of purescript via npm, for example by using this template:
https://github.com/slamdata/purescript-halogen-template/blob/master/package.json
and calling `npm install` or just calling `npm install purescript@0.12.5 -g`.
During installation the process hangs at the:
`Check if a prebuilt 0.12.5 binary is provided for <OS>`
stage.

I experienced this behaviour on:
Ubuntu 18.04
npm 3.5.2
nodejs v8.10.0

As well as on:
Windows 10
(I don't have the npm & nodejs version at hand right now, but I can provide them later if relevant).

A workaround for me was, to install and download purescript manually.

**Comment by hdgarrood** [comment] 2019-07-09 09:28
Thanks for the report. This is a duplicate of https://github.com/purescript/npm-installer/issues/12.

**Closed by hdgarrood** 2019-07-09 09:28 UTC
