### ISSUE TITLE
Allow provision of friendly names for operators

### ISSUE THREAD

**Issue by garyb** [purescript/purescript#688] opened 2014-11-07 12:20 UTC
This is mainly for an improvement to the generated JS, similar to the way we introduced named instances - being able to have `bind` rather than `$greater$greater$eq` in the generated code would help a great deal, and also might be useful for documentation purposes as then people would know what to call some of these symbols!

I'm not exactly sure how this would be notated, perhaps as an extension to the fixity declaration?

Just a thought.

**Comment by paf31** [comment] 2015-01-11 05:24
Duplicate of #806 which provides some more ideas and discussion.

**Closed by paf31** 2015-01-11 05:24 UTC
Labels: codegen, duplicate, enhancement, syntax
