### ISSUE TITLE
psci: multiple imports fail

### ISSUE THREAD

**Issue by alexchandel** [purescript/purescript#1003] opened 2015-03-26 14:53 UTC
Compare
```purs
:? shows help
> import Signal.Channel (send)
> import Signal.Channel (send, channel)
> :t channel
Error in module $PSCI:
Error at  line 1, column 1 - line 1, column 2:
  Unknown value channel
See https://github.com/purescript/purescript/wiki/Error-Code-UnknownValue for more information, or to contribute content related to this error.

>
```
versus
```purs
:? shows help
> import Signal.Channel (send, channel)
> :t channel
forall a e. a -> Control.Monad.Eff.Eff (chan :: Signal.Channel.Chan | e) (Signal.Channel.Channel a)
> 
```

After running two imports in an interpreter, I would expect the namespace to be the *union* of the two, not the first.

**Comment by garyb** [comment] 2015-03-26 14:55
This might not just be `psci`, #817 is another issue with multiple import.

**Comment by paf31** [comment] 2015-03-30 18:54
Closing as duplicate of #817.

**Closed by paf31** 2015-03-30 18:54 UTC
Labels: duplicate
