### ISSUE TITLE
Purescript Package broken when installing via npm

### ISSUE THREAD

**Issue by cruhl** [purescript/purescript#3678] opened 2019-06-14 16:34 UTC
![image](https://user-images.githubusercontent.com/4983357/59524007-5f816700-8e98-11e9-95e2-cad253bea10e.png)

**Comment by garyb** [comment] 2019-06-14 16:35
Duplicate of #3677 🙂 

It can be resolved by updating to a newer node version.

**Closed by garyb** 2019-06-14 16:35 UTC

**Comment by cruhl** [comment] 2019-06-14 16:39
Gotcha, thanks. You might consider adding some note about this to the getting started guide :)
