### ISSUE TITLE
Type inferred proxy literal

### ISSUE THREAD

**Issue by kcsongor** [purescript/purescript#3075] opened 2017-09-16 16:33 UTC
The new proxy syntax makes specifying types inline a lot nicer, but there are still situations where it would be preferable to lift the proxy out of the context to a top-level definition, e.g.:

```purescript
p :: @"Some long string"
p = @
```

However, the bare `@` is a syntax error, currently - and having to copy the type would be a little inconvenient.

My current workaround is a little clunky:

```purescript

p :: SProxy "Some long string"
p = SProxy

fromSProxy :: forall a. SProxy a -> @a
fromSProxy _ = @a
```

and then using `fromSProxy p` when I need `p` in a context that expects a `@`

/cc @rightfold

**Comment by LiamGoodacre** [comment] 2017-09-16 16:50
I have no idea how this is working and I don't think it should be, but this compiles:

```purescript
proxy :: forall a. @a
proxy = @a

eg0 :: @"eg0"
eg0 = proxy

eg1 :: @Int
eg1 = proxy
```

**Comment by rightfold** [comment] 2017-09-16 16:53
We already have syntax for "infer this type". It should work with proxies too.
```purescript
p :: @"Some long string"
p = @_
```

**Comment by LiamGoodacre** [comment] 2017-09-16 16:53
That's not quite the same thing though, it also raises a warning.

**Comment by rightfold** [comment] 2017-09-16 16:54
The warning could be inhibited in this case.

**Comment by kcsongor** [comment] 2017-09-16 16:54
@LiamGoodacre Neat, that's a lot better workaround than mine!

@rightfold I did try that, but I get the following:

```purescript
  Could not match type

    _

  with type

    "hello, world"


while trying to match type @_
  with type @"hello, world"
while checking that expression @_
  has type @"hello, world"
in value declaration p
```

**Comment by rightfold** [comment] 2017-09-16 16:55
What @LiamGoodacre wrote is I think a nice way to do it:

```purescript
proxy :: forall a. @a
proxy = @a
```

This is totally safe; for any `a`, `@a` is isomorphic to `Unit`.

**Comment by rightfold** [comment] 2017-09-16 16:55
@kcsongor maybe this error has to do with #3072.

**Comment by kcsongor** [comment] 2017-09-16 16:57
Like I said, that's a nice workaround, but I still think having the type of `@` inferred would be desirable.

**Comment by rightfold** [comment] 2017-09-16 17:02
Scrutinizing it, @LiamGoodacre's `proxy` function has one flaw, and indeed it should not work: `a` is of kind `Type`. Instantiating its type should retain this kinding.

**Comment by LiamGoodacre** [comment] 2017-09-16 17:03
It gets even weirder (although same issue):

```purescript
proxy :: forall a. @a
proxy = @a

eg0 :: @"eg0"
eg0 = proxy

eg1 :: @Int
eg1 = proxy

data A (s :: Symbol) = A
data B (a :: Symbol -> Type) = B

p0 :: forall a b. @a -> @b -> @(a b)
p0 _ _ = proxy
ap = p0 @A @"Hi"
bp = p0 @B @A

g0 :: forall a b. @a -> @b -> a b -> a b
g0 _ _ ab = ab
ag = g0 @A @"Hi"
bg = g0 @B @A
```

**Comment by kcsongor** [comment] 2017-09-16 17:05
@rightfold what makes `a` kind `Type`?

**Comment by LiamGoodacre** [comment] 2017-09-16 17:06
We don't have polykinds yet, so the `forall a.` is defaulting to `a :: Type` - or rather, it tries to figure out the specific kind based on usage, and then defaults to Type if it's not used.  But I don't know how the proxy syntax affects any of that.

**Comment by LiamGoodacre** [comment] 2017-09-16 17:11
Wow wait a minute!  Did this always work this way?

```purescript
data A (s :: Symbol) = A
data B (a :: Symbol -> Type) = B

banana :: forall a b. a b -> a b
banana ab = ab

bananaA :: _
bananaA = banana A

bananaB :: _
bananaB = banana B
```

**Comment by LiamGoodacre** [comment] 2017-09-16 17:13
The above also works in try-purescript... so that's interesting

**Comment by kcsongor** [comment] 2017-09-16 17:18
Well, that's as poly-kinded as it gets

**Comment by kcsongor** [comment] 2017-09-16 17:25
Wait, this also compiles just fine:
```purescript
data A (s :: Symbol) = A

banana :: forall a b. a b -> @b -> a b
banana ab _ = ab

bananaA :: _
bananaA = banana A @Int
```

But it definitely shouldn't.

**Comment by LiamGoodacre** [comment] 2017-09-16 17:27
Seems to less poly-kinded and more un-kinded 😄

**Comment by paf31** [comment] 2017-09-18 16:32
This seems to be the same issue as in the other "kind unification" issue - namely that only the kinds of written types get checked. Wildcards are not checked, in particular.

**Comment by LiamGoodacre** [comment] 2017-12-25 17:45
This ticket is actually a question about changes to proxy syntax, not a bug report.  The actual bug is https://github.com/purescript/purescript/issues/3077

**Comment by kcsongor** [comment] 2017-12-25 18:14
That's right, thanks!

**Comment by LiamGoodacre** [comment] 2018-01-22 09:00
Closing, given that we've removed proxy syntax.

**Closed by LiamGoodacre** 2018-01-22 09:00 UTC
Labels: enhancement, question, syntax
