### ISSUE TITLE
Aliases for operators

### ISSUE THREAD

**Issue by paf31** [purescript/purescript#806] opened 2015-01-10 05:26 UTC
Suggested by @jdegoes

We could write e.g. (suggested syntax, open to change):

```purescript
infixl 4 <$> as fmap
```

and then use `fmap` instead of `(<$>)` in code. Also `<$>` would be codegen'd as `fmap`, instead of having to generate a name.

Should this be mandatory even?

**Comment by vendethiel** [comment] 2015-01-10 09:39
Would `fmap` be automatically exported when `(<$>)` is?
Except for codegen, what's the advantage compared to `fmap = (<$>)` (does this not work in ps)?

**Comment by garyb** [comment] 2015-01-10 11:25
Is this different from #688?

**Comment by garyb** [comment] 2015-01-10 11:28
Perhaps the infix delcaration would read better the other way around actually?

``` haskell
infixl 4 fmap as <$>
```

Also I suppose we can use this to define the fixity of backticked-functions too, so if someone uses `x `fmap` y` it also uses `infixl 4` when regrouping.

**Comment by jdegoes** [comment] 2015-01-10 17:10
:+1: :+1: :+1: :+1: :+1: :+1: 

Nearly all backend targets will have poor support for non-alphanumeric identifiers. For example, the JVM has zero support for operator symbols (outside `$`), which means that Scala has to mangle all operator names, producing unintelligible and unusable identifiers from other languages.

Purescript has the same problem. Simultaneously, people seem to want both (a) named versions of all operators, and (b) prefix versions of all infix operators (I personally don't care but I suppose I'd sometimes use them if they existed and it made the code more readable).

This solution would allow squeaky clean code generation on most backends (right now all the symbol encoding is, perhaps, the number one complaint about generated JS), as well as allow people to use prefix named identifiers for all symbols.

I like both the suggested syntaxes, no real preference between them. Among the issues that need resolving:

1. **Are aliases automatically exported?** No. You have to export them manually. This ensures backward compatibility and allows you to export one and not the other when convenient.
2. **Is the fixity declaration applied to backticked aliases?** Yes. The alias should behave in the same way as the operator, the only difference should be that one is an infix operator and the other is, by default, a prefix function.
3. **Are aliases required?** Yes. Aliases are required because nearly all targets for Purescript do not have clean ways of dealing with non-alphanumeric names, similar to how instances are required to be named primarily for code generation reasons (secondarily for error reporting reasons).
4. **Are aliases always used in code-generation?** Yes, but only for Javascript. Aliases are used for declaration and reference. While Purescript code may freely mix them, the generated code for Javascript has a single way to refer to them, and it's by name and not operator.
5. **Is there a performance overhead for using one versus the other?** No, not for Javascript. They have identical cost and overhead.
6. **If only the symbol is exported, what shows up in the generated code?** In Javascript, the alias. What you export only affects Purescript binding, it does not affect the generated Javascript code. The alias of the operator is propagated all the way to imperative core, where the Javascript code generator uses the alias.
7. **What about name conflicts?** In the module in which the operator is defined, you may not define any other function or value with the alias name. Because the alias can always be fully qualified, there is no potential for any other kind of conflict.

Etc.

**Comment by michaelficarra** [comment] 2015-01-10 21:46
I like it, and prefer @garyb's syntax. But I don't buy the argument  about backend identifier support given we [allow `'` in our identifiers](https://github.com/purescript/purescript/blob/e29cdb0a7c7bf2923b5f1499e6940fc54178bac3/src/Language/PureScript/Parser/Lexer.hs#L221), which many languages do not support.

**Comment by jdegoes** [comment] 2015-01-10 21:58
I had forgotten about `'`, but in any case, the generated code would be a *lot* easier if that were the only symbol that had to be mangled (note that `'` could be robustly compiled to `$` in both Javascript and the JVM assuming all operators had aliases; my preferred solution would be compiling `foo'` into `foo2`, etc., although that raises the possibility of name collision which would make it difficult to integrate with module compilation).

**Comment by michaelficarra** [comment] 2015-01-11 04:26
You also have to worry about conflicts with reserved words in the target language that aren't reserved in PureScript. Still, I don't think that takes away from (or adds anything to) this proposal.

**Comment by paf31** [comment] 2015-01-11 05:23
@garyb I'll combine this with #688.

**Comment by paf31** [comment] 2015-02-12 01:00
Another question - what happens if an operator doesn't have a corresponding fixity declaration?

**Comment by jdegoes** [comment] 2015-02-12 03:49
Added 8: **What happens if an operator does not have a fixity declaration?** Then its alias, as well as the operator itself, assume the default fixity.

**Comment by paf31** [comment] 2015-02-12 03:53
My point is that the alias is defined with the fixity. So is it an error if an operator doesn't have an alias? _Edit_: sorry, I see that point 3 answers that.

**Comment by paf31** [comment] 2015-02-12 03:53
Ok, part 2: what does an alias without a fixity declaration look like?

**Comment by jdegoes** [comment] 2015-02-12 04:01
Ah yes, the problem is really that the alias is attached to the fixity, when it should in fact be attached to the operator.

```purescript
alias (<$>) as fmap
```

Or other more suitable syntax.

Since the type declaration is not required, and neither is the fixity declaration, one could also choose the syntax to attach to the definition -- albeit it's not really consistent with the fixity declaration and might add noise (also what would an unambiguous syntax be?).

**Comment by garyb** [comment] 2015-02-12 14:22
Would it be a bad idea to require fixity declarations for operators? Or even more drastic - maybe functions have to be defined with a name and the only way of introducing operators is through infix/alias syntax.

Also how does all of the above play with arguments that are operators (e.g. `\(<>) a b -> a <> b`)? We can only define fixity at the module level now, right? That makes point 3 a little bit tricky as it stands.

**Comment by jdegoes** [comment] 2015-02-12 14:42
I've always thought Haskell's method of declaring fixity / associativity was rather ad hoc... the above example is a good one (`\(<>) -> a <> b`) because it demonstrates the loss of control over fixity that occurs, somewhat arbitrarily, simply because an operator is free.

It would be nice if operator parameters could be compiled down to something sane (e.g. the above is compiled down to `function(append){return append(a, b);}`).

One can imagine an `alias` statement requiring that *any use of the specified operator or function name* should be compiled down to the specified alias, *regardless of where it occurs*. Then one needn't try to have an "inline alias syntax", but one can instead define aliases at the module level. This leads to a few other issues:

1. **Can aliases be hidden in a module or are they always exported?**
2. **What happens if code imports two conflicting aliases for the same name or operator?** 

Even the above solution suggested by @garyb (functions always have names, aliases are required for operators -- which I kind of like because it's a simple rule to follow that biases towards clean code generation) runs into these two issues. It seems almost like solving them would require making aliases first-class things, such that you could export them, hide them, etc.

If an alias were the only way to introduce operators, one can imagine combining the introduction of the operator alias with the fixity declaration, as per the original proposal:

```
infixl 4 fmap as <$>
```

i.e. this is taken to mean, the function `fmap` has an operator alias with the specified fixity, which may be used by callers, but which does not affect code generation.

Then one still has to decide: is an alias bound to a specific function, or can you use the operator anywhere and it's a mere alias for any function in scope having the specified name? If the former, then one needs, at minimum, a way to import/export the alias independently of the function. If the latter, then alias seems to become a kind of first-class entity which can be exported/imported like type classes, data constructors, and function names.

**Comment by paf31** [comment] 2015-02-12 17:41
I don't really like the idea of a name being given a global fixity. There seems to be a use case for let-bound operators with redefined fixities. Consider something like `<?>` from QuickCheck - you might like to redefine it in a where clause to use it for something else.

I'd prefer to roll the fixity and alias declarations into the type declaration:

```purescript
infixl 5 (<?>) as fromMaybe :: forall a. Maybe a -> a -> a
(<?>) (Just a) _ = a
(<?>) _ a = a
```

or something similar, deprecating the old fixity declarations, but keeping them around for now, and desugaring them into this new form.

This brings up another issue though - what to do about the scope of a let-bound aliased operator? It seems obvious, but this will require big changes to the current approach in `Sugar/Operators.hs`.

**Comment by paf31** [comment] 2015-02-12 17:45
One nice thing that comes from requiring aliases is that we can remove operators from the core functional representation entirely.

**Comment by jdegoes** [comment] 2015-02-12 17:47
That's a big win, will make compilation to other targets much easier.

**Comment by garyb** [comment] 2015-02-12 18:50
They're not explicitly represented already, aside from the `Op` flavour of `Ident`... or is that what you meant? :)

**Comment by paf31** [comment] 2015-02-12 19:00
Yep, that's what I mean. Identifiers can just become a `newtype` for `String`.

**Comment by paf31** [comment] 2015-02-16 05:30
How about this as an alternative:

- Operators only exist before desugaring. A desugaring step turns every operator into a named function.
- The fixity declaration associates an operator with a fixity and the function it desugars into.
- It is an error if an operator is not bound to a function/fixity in the current scope.
- Fixity declarations can appear in `let` bindings.

This breaks every fixity declaration right now, so as a workaround, we can show a warning, and make the default identifier the mangled name from codegen (`$less$greater` or whatever).

Thoughts?

**Comment by jdegoes** [comment] 2015-02-16 14:05
Sounds good to me. One can think of the "fixity" declaration as "all the stuff not captured by the type signature or declaration".

It seems like we'd have to disallow operators in parameter bindings, e.g. `\(<>) -> a <> b`. Since otherwise, you can't specify an operator name, fixity, etc. Unless one were to invent new syntax for that case.

**Comment by garyb** [comment] 2015-02-16 14:18
Disallowing operator named arguments is perhaps less of a problem when allowing fixities in `let` as then you could have something like `\join a b -> let infixr 6 join as <> in a <> b`.

I suppose that works better if operators can only be introduced with the `infix fn as op` syntax - so for example, we'd have to rename `(<$>)` to `map` in the `Functor` class definition, and then introduce the operator afterwards.

**Comment by paf31** [comment] 2015-03-04 21:26
I'll suggest something drastic.

A common complaint seems to be that the operators we use make the language hard to read. I think I remember someone saying PureScript looked like Perl, which can't possibly be a compliment :)

So, given that we're going to change things in a major way in 0.8, should we also change or remove some of the standard operators? `fmap` or `map` as an alias for `<$>` (or the other way round) is one thing, but the readability of `<$>` itself is another. 

Should we consider just removing them entirely?

We would still be able to assign fixities to function names, and code would start to look like:

```purescript
x = f `fmap` foo `ap` bar `ap` baz
```

Not as nice in my opinion, but we should probably be encouraging the use of things like `liftN` anyway, or implementing things like idiom brackets eventually.

**Comment by jdegoes** [comment] 2015-03-04 21:33
Not a fan of removing operators. Operators make code easier to read, because they reduce the amount of pseudo-information communicated in the text (i.e. bits which do not actually have any semantic content beyond disambiguation from other symbols). Also many concepts in FP do not have useful names; `bind` is common for `>>=` but it doesn't describe the operation in any meaningful sense. Operators are really good at representing abstract, foundational algebras -- for which we can produce names, but for which names will always and necessarily fail to communicate the algebras.

**Comment by garyb** [comment] 2015-03-04 21:33
I can't say I'm crazy about that idea. I think applicative form using `<$>` and `<*>` only looks strange if you don't know what it means. I probably use those operators more than the arithmetic operators when writing PureScript and Haskell, and I'd argue the wordy infix version is harder to read as it makes less visually distinct blocks than the `<?>` operators, and the words themselves are no easier to understand if you're not familiar with the operations.

**Comment by paf31** [comment] 2015-03-04 21:36
Yeah, I think I agree with both of you. I just don't know how to address the issue that people don't understand the standard operators. The aliases will probably help a lot. I wonder if allowing unicode operators would be good (since you have a larger library of single characters to pick from) or terrible (greater potential for abuse, editor support is bad, etc.).

**Comment by jdegoes** [comment] 2015-03-04 21:41
:+1: for unicode.

People won't understand `>>=` anymore if it's called `bind`, in fact that might be worse because they might think they actually understand it based on the meaning of the name (which is erroneous).

Basically, people are always gonna hate on operators. I think the best solution is to spend quality time in explaining the concepts behind those operators. Also, from a library perspective, it's important not to use operators just to be cute -- operators are best used for algebras whose operations have no good names, not as poor man's syntax sugar to create weird-looking DSLs.

**Comment by michaelficarra** [comment] 2015-03-04 23:41
+1000 for unicode operators.

**Comment by jasonkuhrt** [comment] 2015-09-26 01:12
Related http://www.haskellforall.com/2015/09/how-to-make-your-haskell-code-more.html

**Comment by paf31** [comment] 2015-11-14 22:27
This was going to be the breaking change in 0.8, right? We should discuss it some more.

**Comment by garyb** [comment] 2015-11-20 12:15
If I remember rightly where we'd arrived at in the various discussion before was:

- Operators cannot be declared directly
- Operators are introduced with fixity declarations like `infixl 4 map as <$>`
- Fixity also applies to the function when used infix
- Fixity declarations can be specified in `let` (or `where`) to allow for custom operators in lambdas, etc
- Operators are purely syntactic, codegen uses the aliased function name

**Comment by michaelficarra** [comment] 2015-11-20 15:26
@garyb I'm not sure about fixity applying to the function when written in infix form, since we now allow more complex expressions in that position. Plus, it would be easier to remember a single precedence/associativity for this form. I would drop that part of it.  Otherwise, :+1:.

**Comment by garyb** [comment] 2015-11-20 15:28
Fair enough, it's much easier _not_ to do that anyway :smile:. Haskell does allow setting fixity of named functions, but it's not something I think I've ever used.

**Comment by paf31** [comment] 2015-11-21 19:05
I'd also prefer if we didn't implement "Fixity declarations can be specified in `let`" in the first version. I think this is going to be a fairly radical change as it is, and scoping issues are always a pain to deal with.

In fact, I'd be willing to bet the wrong fixity gets assigned to a shadowed operator in the current code.

**Comment by garyb** [comment] 2015-11-21 19:10
Sure, that makes sense. I think "enhance the type of definitions allowed in `let`" already has its own issue too actually, from way back, mentioning let-scoped type synonyms and things like that too, so we could perhaps look at all that stuff all at once.

I assume that means we lose the ability to have local operators (`\(<>) x y -> x <> y`) at all in the first version then? I'm fine with that, just checking assumptions.

**Comment by michaelficarra** [comment] 2015-11-21 19:56
@garyb: You might be referring to my scoped foreign imports issue: https://github.com/purescript/purescript/issues/460

**Comment by garyb** [comment] 2015-11-22 11:35
#255 was the one I had in mind actually.

**Comment by paf31** [comment] 2015-11-25 05:04
Is there any way we can implement this in a backwards compatible way?

**Comment by garyb** [comment] 2015-11-25 10:31
I guess so - we'd need to add support for the `infix x as y` syntax while preserving what we have now, and then not disallow functions named as operators. I thought we wanted to do it the breaking way though? Or are you thinking follow the deprecation warning model we have with the `qualified` syntax first?

**Comment by zudov** [comment] 2015-11-25 10:33
:+1: for deprecation model

**Closed** 2015-12-13 15:58 UTC
Labels: codegen, enhancement, syntax
