### ISSUE TITLE
Automatic Show and Eq instances for records

### ISSUE THREAD

**Issue by dvdsgl** [purescript/purescript#970] opened 2015-03-17 05:23 UTC
I'd be able to simplify my codebase significantly by using type aliases and records rather than creating new types, but I'm prevented from doing this because I want to use `show` and `==` on my values, and I don't see how I can add records to `Show` or `Eq`.

I'd love it if closed record types were given automatic `Show` or `Eq` instances if all of their fields were already in `Show` or `Eq`.

**Comment by dvdsgl** [comment] 2015-03-17 05:26
Honestly, I don't even want automatic instances, just the ability to add closed records to classes. Is this possible?

**Comment by paf31** [comment] 2015-03-17 05:31
You can probably do this with `purescript-reflection`. Not the automatic part, just defining the instances.

**Comment by alexchandel** [comment] 2015-03-19 14:56
There is a middle ground. We need something similar to Rust's `#[derive(Eq)]` syntax.

**Comment by paf31** [comment] 2015-03-19 17:29
No, the issue is that record instances aren't allowed at the top-level.

**Comment by paf31** [comment] 2015-07-15 03:09
This will be covered by generic deriving soon, so I'll close this.

**Closed by paf31** 2015-07-15 03:09 UTC

**Comment by paf31** [comment] 2015-08-12 15:22
Generic deriving will be in 0.7.3, FYI.
