### ISSUE TITLE
psc-make generates invalid externs file in presence of un-exported synonyms

### ISSUE THREAD

**Issue by qxjit** [purescript/purescript#1179] opened 2015-06-18 11:53 UTC
When a module exports a type synonym but fails to export synonyms used in its definition, psc-make generates an externs file with references to the un-exported synonyms. On subsequent psc-make runs the un-exported synonym is reported as an unknown type since it is not found in the externs file.

Presumably the first build should fail because of the un-exported synonym in the first place?

**Comment by garyb** [comment] 2015-06-18 11:55
Yep, if it fails on subsequent builds it should fail the first time too. 

Just checking I understand correctly, it's when you have something like this:

``` purescript
module Test (X()) where

type X = Y
type Y = String

```

?

**Comment by qxjit** [comment] 2015-06-18 11:55
You're too fast! Here's a minimal example: https://github.com/flipstone/purescript_issue_1179

**Comment by garyb** [comment] 2015-06-18 11:56
Ah perfect, thanks!

**Comment by paf31** [comment] 2015-09-25 03:37
Possible duplicate of #1318?

**Comment by paf31** [comment] 2015-10-28 23:48
Can we close this now?

**Comment by garyb** [comment] 2015-10-28 23:55
Yep!

**Closed by garyb** 2015-10-28 23:55 UTC
Labels: bug
