### ISSUE TITLE
Automatic instance naming error

### ISSUE THREAD

**Issue by mikesol** [purescript/purescript#4347] opened 2022-05-31 10:17 UTC
## Description

It looks like auto-instance naming is not working in some scenarios. Unfortunately, as I'm working in a very large codebase, it'll be a while before I can make a minimal repro, but I can put screenshots of the naming & error in hopes that someone that knows this part of the compiler can spot what the bug might be.
<img width="815" alt="Screen Shot 2022-05-31 at 1 14 46 PM" src="https://user-images.githubusercontent.com/525350/171151352-68d7473c-5e43-4d9a-8cc9-2928756d3f26.png">
<img width="803" alt="Screen Shot 2022-05-31 at 1 14 36 PM" src="https://user-images.githubusercontent.com/525350/171151366-3dd0cfce-54d4-4415-8a3e-f7c594cdfd19.png">

Manually naming the instances fixed the problem.

## PureScript version

0.15.0

**Comment by JordanMartinez** [comment] 2022-05-31 13:23
Pretty sure this is a duplicate of https://github.com/purescript/purescript/issues/4310

**Comment by JordanMartinez** [comment] 2022-05-31 13:23
Which was fixed in `0.15.2`.

**Closed** 2022-06-02 23:40 UTC
Labels: type: bug
