### ISSUE TITLE
Qualified names aren't qualified in the errors/warnings 

### ISSUE THREAD

**Issue by zudov** [purescript/purescript#1842] opened 2016-01-21 10:58 UTC
For example:

```haskell
module Main where

import Foo.Bar.Baz as Baz

foo :: Baz.MyInt
foo = 0

module Foo.Bar.Baz where

newtype MyInt = MyInt Int
```

Results in:

```
  Could not match type
    Int
  with type
    MyInt
while trying to match type Int
  with type MyInt
while checking that expression 0
  has type MyInt
in value declaration foo
```

It would be much nicer if it referred to `Foo.Bar.Baz.MyInt` in the same way as I did (`Baz.MyInt`)

**Comment by garyb** [comment] 2016-01-21 11:33
Duplicate of #1647 :)

**Closed by garyb** 2016-01-21 11:33 UTC

**Comment by zudov** [comment] 2016-01-21 11:36
Agrh, tried, but failed to find it.
