### ISSUE TITLE
Poor performance in single-threaded (CI) builds

### ISSUE THREAD

**Issue by tfausak** [purescript/purescript#1880] opened 2016-02-10 13:47 UTC
The build for [Batteries](https://github.com/tfausak/purescript-batteries) started failing when I upgraded to PureScript 0.8.0: https://travis-ci.org/tfausak/purescript-batteries/builds/107790470#L767

> No output has been received in the last 10 minutes, this potentially indicates a stalled build or something wrong with the build itself.

This was not the case with PureScript 0.8.0-rc.1, which finished in around 7 minutes: https://travis-ci.org/tfausak/purescript-batteries/builds/101410203

I don't mind the build taking a while, but it would be nice to have some incremental output so that it doesn't time out. Also, I suspect that once the warnings are fixed, this won't be a problem anymore.

**Comment by garyb** [comment] 2016-02-10 13:59
We've recently been encountering this problem on Travis too, but even with 0.7.6. It's not clear what the problem is, as it seems like the build has stalled sometimes, as this also happens for things that take no where near 10 minutes to build when they succeed.

/cc @jonsterling

**Comment by hdgarrood** [comment] 2016-02-10 15:47
Could be to do with re-exports in psc-publish? That was added after the RC, IIRC. How long does psc-publish take to run locally?

**Comment by hdgarrood** [comment] 2016-02-10 15:49
There is intermediate output, by the way - psc prints one line for each module it compiles. Pulp swallows that, but you could try running the build using psc directly.

**Comment by garyb** [comment] 2016-02-10 15:53
@hdgarrood that wouldn't explain it affecting 0.7.6 compiled projects too, and in the case we saw it's make rather than publish that hangs.

**Comment by tfausak** [comment] 2016-02-10 16:07
Everything runs pretty quickly locally.

``` sh
purescript-batteries> time npm install
...
120.95 real        47.60 user         7.70 sys

purescript-batteries> time npm test
...
7.15 real        15.12 user         4.97 sys

purescript-batteries> time npm run psc-publish
...
2.55 real         2.28 user         0.22 sys
```

**Comment by jonsterling** [comment] 2016-02-10 16:51
Is there concurrency going on in `psc`? I wonder if something is deadlocking...

**Comment by garyb** [comment] 2016-02-10 16:54
There is, yeah, at the compile-modules level. I would be surprised if deadlocking was "possible" though, given that module graph is toposorted and does not allow for circular hierarchies.

**Comment by jonsterling** [comment] 2016-02-10 16:55
Hmm, yeah... Might be a place to look though (but I don't know this codebase, so I could be wrong)—my experience is that in any code that combines humans, MVars, laziness and asynchronous exceptions, there's *something* bad lurking in there, even if we haven't found it yet.

**Comment by garyb** [comment] 2016-02-10 16:59
Haha, good point!

I did add an option that allows you to set RTS options when using `gulp-purescript` by passing a `--psc-rts-opts` when running `gulp`, so we could try `gulp --psc-rts-opts -N1` on that build that was persistently failing yesterday?

When `psc` was made concurrent it became _much_ slower on travis (Halogen's full compile went from 5mins to 50), but the improvement for "normal" setups was similiarly drastic. Unfortunately `-N1` was only a little faster than leaving the thread limit unspecified, so up to now I've not been using it.

**Comment by jonsterling** [comment] 2016-02-10 17:31
@garyb I've tried with that option and it didn't help...

**Comment by paf31** [comment] 2016-03-10 05:33
Is this a duplicate of #1889 or something else?

**Comment by garyb** [comment] 2016-03-10 11:55
It's probably something else, sometimes even with small libraries Travis will hang, @jonsterling can probably provide a couple of examples.

There's definitely something very odd about how `psc` behaves on Travis now (since it was made parallel, not 0.8.x, and unfortunately -N1 doesn't help) specifically. It takes nearly 9 minutes to compile Halogen, over 10 minutes to compiles some of the Halogen component libraries we use in SlamData, but when we build SlamData itself which includes Halogen, many components, and a ton of other stuff it finishes in less than 6 minutes. We use a different container distribution to compile SlamData which is probably why it's much faster, but it's still pretty weird.

**Comment by paf31** [comment] 2016-03-10 16:23
Well, the compiler is definitely slower on one core now, since it has the overhead of reading and writing externs files to/from disk. We could optimize for the single core case with a bit of work though, by keeping externs in memory instead. I'd like to still use the externs for passing data through the pipeline though, since that way we don't end up with weird bugs which only happen on single core machines :smile:

**Comment by garyb** [comment] 2016-03-10 16:44
It's not just slower, it seems that sometimes it's deadlocked or something (even with `-N1`).

It's also a lot slower, not just a bit :wink:, more than IO should account for. Halogen went from building with all of its examples in 5 minutes to building in 50+ when we went from 0.7.5 to 0.7.6.

**Comment by paf31** [comment] 2016-03-10 16:48
Ok, I'll have a think about it, thanks. I'll move this up to 0.9 too.

**Comment by paf31** [comment] 2016-08-01 00:55
Any updates on this from those who reported it?

**Comment by garyb** [comment] 2016-08-01 00:56
It was still broken with 0.8.5, we accidentally had a (simple) module building with that on Travis and it wouldn't complete. I've not tried with 0.9.x since the trusty image makes it all good.

**Comment by tfausak** [comment] 2016-08-10 13:02
[The Batteries build failed](https://travis-ci.org/tfausak/purescript-batteries/builds/145348000) with PureScript 0.9.1.

**Comment by rgrempel** [comment] 2016-09-09 19:34
There has been some discussion in the Elm community of what may be a similar problem, with a workaround.

It appears that the problem may be that Travis (and perhaps other CI environments) reports more CPUs as being available than it actually makes available. So, it's not single-threaded performance as such that is the problem -- it is performance where the compiler thinks it has more CPUs available than it actually does.

Here's the link to the Elm dicussion:

https://github.com/elm-lang/elm-compiler/issues/1473

Of course, this may not actually be the same issue as here, but it looks promising.

**Comment by paf31** [comment] 2016-10-02 17:41
If `-N1` fixes this, then I'd like to close this.

**Comment by paf31** [comment] 2017-03-19 22:48
Any updates on this? If not, I'll close it with `-N1` as the recommended solution.

**Comment by garyb** [comment] 2017-03-19 23:19
`-N1` wasn't really the fix, it sometimes just hangs forever with that. Switching to use `dist: trusty, sudo: required` was the fix for Travis. 

It doesn't really explain what's going on, but we've not had any problems with slow / stalling builds since switching to that, and AppVeyor seems fine too, so yeah this can probably be closed.

**Comment by paf31** [comment] 2017-03-19 23:55
Thanks for clarifying!

**Closed by paf31** 2017-03-19 23:55 UTC
Labels: bug, needs info
