### ISSUE TITLE
Have module reexports appear in generated code

### ISSUE THREAD

**Issue by ssadler** [purescript/purescript#1888] opened 2016-02-16 00:53 UTC
```
$ psc --version
0.8.0.0
```

To reproduce, `pulp init` a new project, then:

``` haskell
--src/Main.purs
module Main 
  ( module A
  , main
  ) where

import A
import Control.Monad.Eff
import Prelude

main :: Eff () Unit
main = pure unit

--src/A.purs
module A 
  ( foo
  ) where

foo :: String
foo = "Hello thar"
```

```
$ psc src/Main.purs
```

Contents of output/Main/index.js:

``` Javascript
// Generated by psc version 0.8.0.0                                     
"use strict";                                                           
var A = require("A");                                                   
var Control_Monad_Eff = require("Control.Monad.Eff");                   
var Prelude = require("Prelude");                                       
var main = Prelude.pure(Control_Monad_Eff.applicativeEff)(Prelude.unit);
module.exports = {                                                      
    main: main                                                          
};                                                                      
```

Would expect `foo: A.foo` to appear next to `main` in the exports. I believe this was working in 0.7.6.1, I was using re-exported modules in the browser.

**Comment by paf31** [comment] 2016-02-16 00:55
If this is not a Pulp issue, could you please recreate it using `psc` and `psc-bundle`?

**Comment by libscott** [comment] 2016-02-16 01:09
Sure, done. Hope the remaining use of `pulp init` is OK.

**Comment by paf31** [comment] 2016-02-16 01:17
I see now. I don't think module reexports get represented in the generated code, which does bother me a little, but I think it is by design.

**Comment by garyb** [comment] 2016-02-16 01:20
I don't think it was working in 0.7.6.1, re-exports have only ever existed as an artifact during name desugaring.

**Comment by garyb** [comment] 2016-02-16 01:22
It's "by design" in that I made no effort to codegen the re-exports, yes. They would be considered dead code by `psc-bundle` as we import values from their original location. Desugaring by elaborating the member's modules has an additional set of challenges in that we'd need some kind of internal value that the compiler can look at and go "this A.x is a re-export of B.x, so they're both the same value" to avoid scope conflicts.

**Comment by libscott** [comment] 2016-02-16 01:24
> I don't think it was working in 0.7.6.1, re-exports have only ever existed as an artifact during name desugaring.

It may have been that `pulp build --modules X --to ...` was enough to include other modules reexported by X in the resulting output bundle, and not that re-exported values would be put in `X`'s exports.

**Comment by libscott** [comment] 2016-02-16 01:41
> Desugaring by elaborating the member's modules has an additional set of challenges in that we'd need some kind of internal value that the compiler can look at and go "this A.x is a re-export of B.x, so they're both the same value" to avoid scope conflicts.

Out of curiosity, isn't this already implemented somewhere? Importing a value exported via two different modules does work.

**Comment by garyb** [comment] 2016-02-16 01:44
Yeah, it currently works but only because we _don't_ elaborate modules to include values that they are re-exporting, that was what I was trying to explain. :smile:

Currently the names are all resolved during desugaring, and every reference is replaced with a fully-qualified reference, so if you import `x` into `C` from `B`, and it is re-exported from `A`, the code in `C` where you use `x` will refer to `A.x`, not `B.x`, even if `A` was never imported into `C` at all.

**Comment by libscott** [comment] 2016-02-16 02:25
I'd say that, since PS does interface with CommonJS, it's reasonable to want to use re-exports to build an API.

**Comment by libscott** [comment] 2016-02-16 02:43
Looking at the code, trying to guess what the solution might be...

https://github.com/purescript/purescript/blob/master/src/Language/PureScript/AST/Declarations.hs#L86

```Haskell
  | PositionedDeclarationRef SourceSpan [Comment] DeclarationRef
  -- |
  -- A declaration reference with provenance attached
  --
  | ImportedDeclerationRef Module DeclarationRef
```

... is probably not what you'd want to do :D.

**Comment by paf31** [comment] 2016-02-20 21:07
@garyb So is this a `wontfix`, or do you think there is a way to solve this?

**Comment by garyb** [comment] 2016-02-22 10:03
There is a way, and I think you've mentioned in the past that you'd prefer re-exports to exist in the JavaScript too, there are just some questions about how best to achieve it. And it's not entirely trivial, since we need to introduce some new kind of value/declaration that represents a re-exported value so we can determine they are not conflicting when resolving scope.

I do think there are a lot of other things that are higher priority though, so I'd suggest adding this to the backlog for now.

**Comment by hdgarrood** [comment] 2019-01-06 16:47
@garyb I noticed that this issue doesn't seem to have been updated since https://github.com/purescript/purescript/pull/2191 was merged. Would the changes in #2191 be relevant to this, or make it much easier to implement?

**Comment by garyb** [comment] 2019-01-07 13:44
I think that should definitely help this, yeah - we probably "just" need to codegen based off the export list rather than the module members.

I'm also somewhat amazed that export elaboration was done back in 2016... time flies! 😬

**Comment by citizengabe** [comment] 2020-04-28 15:51
In service of moving #3724 forward, I'm investigating what needs to be done to codegen the reexports. Does anyone have any pointers on how [`ReExportRef`](https://github.com/purescript/purescript/blob/e164eaa279e9f019a0bf9e6f61239c75f887bf56/lib/purescript-ast/src/Language/PureScript/AST/Declarations.hs#L182) threads down to [`moduleToJs`](https://github.com/purescript/purescript/blob/e164eaa279e9f019a0bf9e6f61239c75f887bf56/src/Language/PureScript/CodeGen/JS.hs#L53)?

Right now, it looks like the export list is composed of [regular exports and foreign exports](https://github.com/purescript/purescript/blob/e164eaa279e9f019a0bf9e6f61239c75f887bf56/src/Language/PureScript/CodeGen/JS.hs#L71-L72). Are the reexports included in `exps`?

**Comment by gabejohnson** [comment] 2020-04-28 15:53
In service of moving #3724 forward, I'm investigating what needs to be done to codegen the reexports. Does anyone have any pointers on how [`ReExportRef`](https://github.com/purescript/purescript/blob/e164eaa279e9f019a0bf9e6f61239c75f887bf56/lib/purescript-ast/src/Language/PureScript/AST/Declarations.hs#L182) threads down to [`moduleToJs`](https://github.com/purescript/purescript/blob/e164eaa279e9f019a0bf9e6f61239c75f887bf56/src/Language/PureScript/CodeGen/JS.hs#L53)?

Right now, it looks like the export list is composed of [regular exports and foreign exports](https://github.com/purescript/purescript/blob/e164eaa279e9f019a0bf9e6f61239c75f887bf56/src/Language/PureScript/CodeGen/JS.hs#L71-L72). Are the reexports included in `exps`?

**Comment by garyb** [comment] 2020-04-29 12:56
No, they're gone by that point. Re-export elaboration happens entirely in the name resolution part of the codebase at the moment. Or I'm pretty sure that was the case the last time I touched it anyway. :smile:

**Comment by hdgarrood** [comment] 2020-04-29 13:54
Didn't you change that in #2191?

**Comment by garyb** [comment] 2020-04-29 13:56
Hmm, I guess so! Those are definitely gone by the time it reaches `moduleToJs` though, because `exps` in `Module` only contains `Ident`s. Maybe it's the desugar-to-corefn stage they get discarded at now then.

**Comment by hdgarrood** [comment] 2020-04-29 13:58
Ah yes, looks like `exportToCoreFn` in `CoreFn/Desugar` is discarding them now.

**Comment by garyb** [comment] 2020-04-29 14:00
I'm not sure the change I made in that PR will necessarily help here too, as I assume we probably want to re-export from the module that imports are specifically made from, whereas I think the re-exports point to the module the definition originated in (so, bypassing any chains of re-exports).

Maybe that doesn't matter though, since it still works out the same module-dependency-wise.

**Comment by hdgarrood** [comment] 2020-04-29 14:02
I think we have both now; I added the module things are imported from in https://github.com/purescript/purescript/pull/3521

**Comment by hdgarrood** [comment] 2020-04-29 14:03
I think we will want to change that specific bit again and only store the module from which something was imported eventually, as part of #3724

**Comment by garyb** [comment] 2020-04-29 14:04
Ah yeah, I should maybe stop talking on this issue, since I don't seem to know what's going on anymore :smile:

**Comment by gabejohnson** [comment] 2020-05-12 13:58
It looks like the definition of [Module.moduleExports](https://github.com/purescript/purescript/blob/df3170f5bb0ba21517e2ca72db6aee5c479c99df/src/Language/PureScript/CoreFn/Module.hs#L22) would have to change to incorporate the information from [ExportSource.exportSourceImportedFrom](https://github.com/purescript/purescript/blob/df3170f5bb0ba21517e2ca72db6aee5c479c99df/lib/purescript-ast/src/Language/PureScript/AST/Declarations.hs#L198) so the information could be threaded from [moduleToCoreFn](https://github.com/purescript/purescript/blob/df3170f5bb0ba21517e2ca72db6aee5c479c99df/src/Language/PureScript/CoreFn/Desugar.hs#L34) to [moduleToJs](https://github.com/purescript/purescript/blob/df3170f5bb0ba21517e2ca72db6aee5c479c99df/src/Language/PureScript/CodeGen/JS.hs#L53). This would be a breaking change as `CoreFn` is part of the public API.

**Comment by gabejohnson** [comment] 2020-05-12 14:04
And it looks like using `exportSourceImportedFrom` instead of `exportSourceDefinedIn` [here](https://github.com/purescript/purescript/blob/b20aa4c46108eb83f5c92810644f8187389b4642/src/Language/PureScript/Sugar/Names/Imports.hs#L224) would take care of things on the import side of things.

**Comment by gabejohnson** [comment] 2020-05-12 17:10
> And it looks like using exportSourceImportedFrom instead of exportSourceDefinedIn here would take care of things on the import side.

I suppose this is a separate concern.

**Comment by hdgarrood** [comment] 2020-05-12 20:52
So I suppose there are two options: either we make re-exports an explicit part of the corefn module data type, perhaps by doing something like `moduleExports :: [Either Ident (ModuleName, Ident)]`, or instead we add an item to `moduleDecls` for each re-export so that re-exports look the same as local declarations (which just happen to have the same name as something from an upstream module). Being able to avoid breaking the format seems preferable to me, since there are a few tools which rely heavily on it (most alternate backends, zephyr).

One problem with the non-breaking approach is that if a module Lib exports a value `foo`, and a separate module Main re-exports all of Lib and also defines a module-private value `foo` which it does not export, we would end up with multiple declarations of `foo` in Main. I think we might be forced to mangle the local `foo` in that case, but that could be a bit awkward as we'd have to do it throughout the module.

**Comment by gabejohnson** [comment] 2020-05-12 21:16
> either we make re-exports an explicit part of the corefn module data type, perhaps by doing something like `moduleExports :: [Either Ident (ModuleName, Ident)]`

I currently have (what I believe to be) a working draft which makes the change `moduleExports :: [(Maybe ModuleName, Ident)]` which is essentially the same.

> or instead we add an item to moduleDecls for each re-export so that re-exports look the same as local declarations (which just happen to have the same name as something from an upstream module).

Wouldn't that result in an explicit binding for each export in a reexported module? That seem like overkill.  The approach I took results in something like:

```hs
--src/Main.purs
module Main
  ( module A
  , main
  ) where

import A
import Effect
import Prelude

main :: Effect Unit
main = pure unit

--src/A.purs
module A
  ( foo
  ) where

foo :: String
foo = "Hello thar"
```
with an output of
```js
// Generated by purs version 0.13.6
"use strict";
var A = require("../A/index.js");
var Control_Applicative = require("../Control.Applicative/index.js");
var Data_Unit = require("../Data.Unit/index.js");
var Effect = require("../Effect/index.js");
var main = Control_Applicative.pure(Effect.applicativeEffect)(Data_Unit.unit);
module.exports = {
    foo: A.foo,
    main: main
};
```

**Comment by hdgarrood** [comment] 2020-05-12 21:19
Yes, but breaking corefn is a _really_ big deal.

**Comment by garyb** [comment] 2020-05-12 21:32
Well, a major bump like 0.14 would be the time to do it.

**Comment by gabejohnson** [comment] 2020-05-12 21:35
> Yes, but breaking corefn is a really big deal.

I understand that. I guess it's a trade-off between:
1. a breaking (though relatively minor) change in `CoreFn`
2. a potentially enormous increase in non-optimized generated code and mangling of local declarations

While the break to `CoreFn` would affect alternative backends and tools such as `zephyr`, the changes necessary to deal with those changes would be minor. Most of the alternative backend projects I've looked at have forked the `Language.PureScript.CodeGen.JS`. All of my changes to that module have been confined to `moduleToJs` and are relatively straightforward.

@hdgarrood what if I open a PR and ping the authors/maintainers of some of the affected projects to get feedback?

> Well, a major bump like 0.14 would be the time to do it.

@garyb that was my thinking as well.

**Comment by hdgarrood** [comment] 2020-05-12 21:57
Yeah, true, being able to avoid having to insert those extra declarations would definitely be good. I think Discourse would be a good place to announce the intention to change the format.

**Comment by hdgarrood** [comment] 2020-05-15 11:41
I made a Discourse post: https://discourse.purescript.org/t/intention-of-breaking-change-handling-re-exports-in-corefn/1405

**Closed** 2020-06-13 22:41 UTC
Labels: codegen, enhancement
