### ISSUE TITLE
purs bundle breaks purescript-avar

### ISSUE THREAD

**Issue by coot** [purescript/purescript#3082] opened 2017-09-20 08:44 UTC
I am [cross](https://github.com/slamdata/purescript-avar/issues/4) posting. 
I was hit by this yesterday when compiling a project that depends on `purescript-aff#4.0.0` which depends on `purescript-avar`.  This might break a lot of code. 

[zephyr](https://github.com/coot/zephyr) does not suffer from this (even when it preforms DCE in foreign modules).

**Comment by paf31** [comment] 2017-09-21 18:27
`psc-bundle` is very fragile when it comes to foreign dependencies, unfortunately, because of the way it looks for declarations to remove during dead code elimination.

**Comment by rhendric** [comment] 2020-12-26 22:55
I'm closing this as a probable duplicate of #2290; given that purescript-contrib/purescript-avar#4 was closed as fixed by purescript-contrib/purescript-avar#6, the original statement of the issue is no longer true, and between #2290 and #3259 we have easier STR than trying to test `purescript-aff#4.0.0` on a modern PureScript. Please reopen if I'm wrong.

**Closed by rhendric** 2020-12-26 22:55 UTC
Labels: bug, purs bundle
