### ISSUE TITLE
"Getting Started" Tutorial Produces Errors Too Often

### ISSUE THREAD

**Issue by cjs-cynic-net** [purescript/purescript#2175] opened 2016-06-02 10:51 UTC
I've tried again and again, with different versions of Node.js, to get through the [Getting Started](http://www.purescript.org/learn/getting-started/) tutorial, and I'm constantly running into problems. With Node.js v6 it was related to the current release (at that time) not working; with Node.js v4 it's now a mysterious `Unable to parse foreign module: .../bower_components/purescript-foldable-traversable/src/Data/Foldable.js`.

It would be nice to have some sort of automated testing system in place to check that the tutorial actually works as described with new versions of PureScript as they come out. I'd be happy to help with something like this, though at this point I can't even get through the tutorial so I can learn PureScript....

**Comment by garyb** [comment] 2016-06-02 12:50
I think you've stumbled on just about the worst possible time to try and get things working, sorry for that. Hopefully I can clear a few things up with what the current situation/mess is:

- As you already surmised: the 0.8.5 version of `purescript` on npm was published in a way that means it fails to install on node 6, due to command line flags having being removed.
- You can acquire a node 6 compatible version of purescript 0.8.5 by `npm install`ing the version `0.8.6-rc.1`. This unfortunate name is because you can't update a published version on `npm`, and we never released an actual compiler version 0.8.6, so we didn't want to confuse matters by making the latest npm release 0.8.6 while having `psc --version` state 0.8.5. We figured the 0.9.x release would be ready soon enough that it wouldn't affect too many people (we were wrong, people jumped on it on day 1 of the node release).
- The currently published version of pulp is not compatible with the new purescript 0.9.1 release. That update will happen this weekend I think, so if you want to use pulp, you have to use the 0.8.x releases.
- The core libraries have been updated and released for the 0.9.1 compiler, so if you `bower install` them without specifying a version, you'll get the new versions which are not compatible with 0.8.x - this is the cause of the "Unable to parse foreign module" error you're seeing.

We are holding off on releasing the 0.9.1 compiler via npm until pulp is also out there, as if you're on node 4 or 5 and using pulp, everything should work out at the moment, as `pulp init` creates a project with suitable dependency versions for the 0.8.5 prelude, etc.

**Comment by cjs-cynic-net** [comment] 2016-06-02 13:03
Actually, I'm a little bit familiar with the node 6 issues, and I did get PureScript itself to successfully install after finding a (closed) ticket about this. But I was still running into issues there,which is what prompted me to go back and try to work under node 4 (which up to now I'd never used or considered using).

I'm pretty sure I've been using 0.8.x releases of PureScript all along, under both Node.js 4 and 6. I'm guessing the 1.0.x Prelude and friends are the ones for the 0.9.x compiler, and the 0.1.x Prelude and friends are the ones for the 0.8.x compiler? I do believe that I've tried both sets, when prompted by Bower to choose one or the other, under both versions of Node.js, and not had any luck. (But I may have missed something along the way, given how many different options it seems that there are to play with.) But is `pulp init` even setting things up correctly if I'm getting messages to choose between Prelude 0.1 and Prelude 1.0?

One further question I'd like to check about here: the tutorial asks one to do a global install of PureScript, pulp and Bower; it it reasonable to do a local install instead, and just run the programs out of `node_modules/.bin`? Being able to do that would make life considerably easier when testing out various versions of various packages.

I don't mind (in fact I like) that PureScript is under aggressive development, but a page linked off `http://www.purescript.org/` that explained the current state of things, with perhaps a little FAQ for how to deal with likely problems in the current development world, would be really, really helpful. Again, this is an area where automated testing on regular basis could help with such things (otherwise these problems can be hard to spot without a lot of tedious manual re-installs), and I'd be happy to help set up something for that.

**Comment by garyb** [comment] 2016-06-02 13:14
Ah! So bower is pretty terrible at dealing with things when you already have some stuff in your `bower_components`, that's when it starts asking you to make unnecessary resolutions rather than taking the version that the `bower.json` dictates - so it may be worth a try to delete `bower_components` and then `bower install` with your `pulp init` provided setup, I _think_ that should work without asking you any questions about which version to install.

And yes, you're right, the v1.0.0 release are for PS 0.9.1, the pre-1.0.0 version for 0.8.x.

Local installs are perfectly fine, for both `purescript` and `pulp`, although you may need to run things via npm scripts that way to ensure that `pulp` can pick up the purescript executables from the PATH. Bower can also be installed locally, but it starts complaining when the installed version falls behind the most recent release, so if you have it installed locally in a bunch of places you'll have to update each of them - but again there's nothing that will stop you from using it that way.

We perhaps jumped the gun a little on the 0.9.1 psc/v1 library releases due to not updating everything in one fell swoop, but this release process has dragged on for so long (0.9.1 is what we intended to release as 0.8... we thought we were pretty much done back in December!) we were just eager to get it done I think. It's slightly complicated by the fact I'm on holiday this week, and Harry who mostly maintains Pulp these days (and Pursuit... that also needs updating) is unavailable until the weekend. If it's not all sorted out by then, yeah, I'll write some kind of WTF FAQ explaining the current options.

**Comment by cjs-cynic-net** [comment] 2016-06-02 13:56
Oh, I usually start out my testing with an `rm -rf bower_components`. The `bower.json` that pulp sets up right now always seems to lead me to a place where I have to decide between the 0.1 and 1.0 Prelude as soon as I `bower install` anything beyond the one `purescript-console` package that's in there by default.

Just running through this whole thing again on a Windows machine at home (I was doing this earlier this evening on a Linux machine elsewhere): I start with installing the latest Node.js 4.x, then in a fresh directory do an `npm init` followed by `npm install --save purescript pulp bower`. Then I set my PATH to include the fully qualified path to my `node_modules/.bin` directory and `pulp init --force`.

This leaves me with a `bower.json` that includes `purescript-console` at version `^0.1.0`. Checking it out on my home Linux laptop and Windows desktop, at this point I can `pulp psci` and `import Prelude`, and things seem ok.

The next step from the Getting Started is where things go bad. For some reason, on my Windows box I can `bower install purescript-lists --save` and I still seem ok after that, but on my Linux box I end up with a conflict for `purescript-eff` and it asks me to choose between 0.1.2 as required by `purescript-console#0.1.1` and 1.0.0 as required by `purescript-st#1.0.0`.

**Comment by cjs-cynic-net** [comment] 2016-06-02 23:47
Ah, so I finally understand what's going on with the libraries; it's this bit I missed the first time around: 

> The core libraries have been updated and released for the 0.9.1 compiler, so if you bower install them without specifying a version, you'll get the new versions which are not compatible with 0.8.x....

I'm not sure what the correct lessons to take from this are, but it seems that releasing libraries before the compiler that can build them is sub-optimal.

One area of difficulty for me, having a reasonably extensive Haskell and DevOps background, and basic knowledge of Node.js and npm, is that the tutorials seem to be more focused on initially learning the language than my main concern, which is "how does producing builds and doing deployment within this environment work"? I'm not sure whether that's something others are concerned with or if I just happen to be weird.

**Comment by cjs-cynic-net** [comment] 2016-06-03 04:41
I'd like to offer some patches for [Getting Started](http://www.purescript.org/learn/getting-started/). Is this in a repo somewhere that I can fork?

**Comment by AppShipIt** [comment] 2016-06-03 04:46
purescript/purescript.github.io but we never automated deployment. CC @tfausak

**Comment by cjs-cynic-net** [comment] 2016-06-03 04:49
Thanks! Automated deployment doesn't matter; I'll want my changes reviewed before they go in anyway.

**Comment by Risto-Stevcev** [comment] 2016-06-05 14:51
The stackage version needs to be updated too, it's still at 0.8.5

**Comment by hdgarrood** [comment] 2016-06-05 15:00
@Risto-Stevcev Do you mean the version you get by following the instructions under "Stack" on http://www.purescript.org/download/ ? I do have a plan for fixing that, as it happens.

@cjs-cynic-net Did you see http://harry.garrood.me/blog/purescript-why-bower/ ?

**Comment by paf31** [comment] 2016-06-05 18:09
Can this be moved to the purescript.github.io issues board please, if it's still an open issue?

**Comment by Risto-Stevcev** [comment] 2016-06-05 20:08
@hdgarrood I actually only tried `stack install purescript` without `--resolver=nightly`. I need to upgrade my GHC version to 8 in order to get the nightly, I'll keep you posted if it works

**Comment by hdgarrood** [comment] 2016-06-05 21:13
I think it's better to either use the binaries, or if you're building from source, use the same stack.yaml as what we're using. https://github.com/purescript/purescript.github.io/pull/94 should have resolved the stackage snapshot issue. There isn't anything we can do about `stack install purescript` giving you an old version beyond what we're doing currently, as far as I can tell.

**Comment by Risto-Stevcev** [comment] 2016-06-05 22:15
I'm using Arch Linux, and before Stackage the way they kind of dealt all the annoyances of cabal (similarly) is to just have a curated list of packages from a separate haskell repo they use that work together. They haven't upgraded ghc to 8 yet, so I either have to wait or install or uninstall everything and then maintain of my haskell stuff with stack (which is probably the best way to go). I tried the binary but I had some weird permissions issues with cabal (superuser or not, it fails w/ different errors on both).

I have a Docker image up running Debian that uses the binary version. I think this might be a good angle to take since Purescript is dependent on Haskell, and cabal isn't really very friendly, and Docker is good practice anyway.

I think it would be a good idea to have an official Docker image for Purescript.

I want to try to setup a Dockerfile that does it with Alpine since it's way smaller, but currently there's no GHC package for Alpine yet, so I might try to get Stack working on it first and go from there.

**Comment by hdgarrood** [comment] 2016-06-05 22:22
If you download a binary bundle from the releases tab, they should not have any dependency on cabal at all. I'd like to work out what problem you had with the binaries if possible, and fix it if we can; Docker seems a bit overkill to me right now.

**Comment by jplatte** [comment] 2016-06-05 22:30
@Risto-Stevcev If you're okay with installing the binaries instead of building PureScript yourself, you can also install `purescript-bin` from the AUR.

**Comment by Risto-Stevcev** [comment] 2016-06-05 23:24
@hdgarrood Yeah... now I can't find where I saw that issue with cabal permissions, sorry about that. I've haven't been near my computer much today because I've been doing other stuff all day, and I don't remember what I was working on since I was also doing a lot of Docker stuff with Alpine and Debian.

But if I try the binary right now, it gives this error:

```bash
$ ./psci: error while loading shared libraries: libtinfo.so.5: cannot open shared object file: No such file or directory
```
The process of using the binary would just end up being the same as this AUR package: https://aur.archlinux.org/packages/purescript-bin/

But the main issue with why I didn't want to use the AUR package was because the symlink for the ncuses library seemed like quite a hack. Installing via stack has no such issues. And I wanted to get it set up with Docker with an Alpine base image (most of what I did today), which I felt like was a better alternative than using a cabal sandbox.

I think using stack is a better way to go than the binary, because for Alpine, for example, it won't even tell you which shared object is missing for the binary. I remember having to read the elf header to find out, and I think I realized that Alpine doesn't have all of those in it's repos so I gave up on it.

And plus stack is part of the main package repository for Arch Linux (as well as other distros AFAIK), so it's as easy as:

```bash
$ sudo pacman -S stack
$ stack setup
$ stack install purescript
```

**Comment by Risto-Stevcev** [comment] 2016-06-05 23:26
Are there any plans to rewrite the compiler in Purescript eventually? that would make all of these problems nonexistent.

**Comment by hdgarrood** [comment] 2016-06-05 23:36
> Installing via stack has no such issues

Are you sure? I would have expected that installing via stack still requires you to install libtinfo yourself, at least on linux (this is what causes the psci error you're seeing). Is this not the case?

**Comment by Risto-Stevcev** [comment] 2016-06-05 23:45
Apparently not, unless I'm not seeing something. Here's the install from stack:

```bash
[velvet@arch purescript]$ ~/.local/bin/psci 
 ____                 ____            _       _   
|  _ \ _   _ _ __ ___/ ___|  ___ _ __(_)_ __ | |_ 
| |_) | | | | '__/ _ \___ \ / __| '__| | '_ \| __|
|  __/| |_| | | |  __/___) | (__| |  | | |_) | |_ 
|_|    \__,_|_|  \___|____/ \___|_|  |_| .__/ \__|
                                       |_|        

:? shows help
PSCi requires the purescript-console module to be installed.
For help getting started, visit http://wiki.purescript.org/PSCi

> 
See ya!
[velvet@arch purescript]$ 
```

Here it is with the binaries (using the same version as the stack one, 0.8.5):

```bash
[velvet@arch purescript]$ ./psci 
./psci: error while loading shared libraries: libtinfo.so.5: cannot open shared object file: No such file or directory
```

The npm one fails for reasons already known/mentioned. And I don't have `libtinfo.so.5` installed AFAIKT:

```bash
[velvet@arch purescript]$ find /usr -type f -name libtinfo.so.5
[velvet@arch purescript]$ 
```

**Comment by hdgarrood** [comment] 2016-06-05 23:57
Ah ok - that's not what I would have expected. If you're able to find out what's going on here, I think that could be quite helpful.

**Comment by jplatte** [comment] 2016-06-06 00:07
@hdgarrood This is how it's always been. I think `libncurses.so` in arch has the symbols of both the `libncurses.so` and `libtinfo.so` in Debian-based distributions. Or something like that. But every `libtinfo` seems to always just be a symlink on arch, and if you build something using `haskeline` on arch you'll get it linked against ncurses directly.

**Comment by Risto-Stevcev** [comment] 2016-06-06 00:10
@jplatte Yeah, that's what I was about to say :smile:

https://github.com/Valloric/YouCompleteMe/issues/778

> In some distributions, like Arch Linux, libtinfo.so is compiled as a part of libncurses.so.

**Comment by Risto-Stevcev** [comment] 2016-06-06 00:11
That's why I think it's better to use `stack` rather than precompiled binaries. There's just too many factors to consider. What if someone wants to use a non-standard distro like Alpine? it might compile the shared objects completely differently. There might even be differences if the kernel is linux-grsec.

**Comment by hdgarrood** [comment] 2016-06-06 00:15
Oh, I see, cool. Thanks :) In that case I guess I'd recommend compiling from source too, yeah. The newest version of the instructions on the website (i.e. `stack unpack purescript` followed by `stack install .` instead of `stack install purescript`) on the website should make compiling from source easy, hopefully.

**Comment by hdgarrood** [comment] 2016-06-06 01:45
Oh, also, yes, there was a plan to rewrite the PureScript compiler in PureScript. It was too slow when compiled to JS, though, which was why it was put on hold. The C++ backend seems like a promising alternative, although I suppose if we compiled a hypothetical self-hosted PureScript compiler by going via C++ we'd be similarly likely to suffer from these sorts of issues.

**Comment by Risto-Stevcev** [comment] 2016-06-06 02:52
Yeah, C++ doesn't have the same kind of safety and might potentially introduce more bugs, but gcc and g++ is usually already installed and node has an FFI for it, so it would just be able to compile it all. Right now the only way the npm package works is by running a precompiled binary, and that's not going to work well across different systems.

Maybe something like LLVM would help? you could have GHC compile it to C and then have the npm package compile the source

**Comment by hdgarrood** [comment] 2016-06-06 03:18
Hm, perhaps, although it seems like there's a lot to go wrong there. I much prefer the look of @jplatte's purescript-stack AUR package: https://github.com/purescript/purescript/issues/2176#issuecomment-223856816.

@paf31 is right, this issue is getting a bit confused, so I'm going to close this. If purescript-stack doesn't address your problem, could you please open a new issue? Likewise, @cjs-cynic-net, please feel free to open issues or PRs on https://github.com/purescript/purescript.github.io/.

**Closed by hdgarrood** 2016-06-06 03:18 UTC
Labels: documentation
