### ISSUE TITLE
spago run: Print compilation messages to stderr

### ISSUE THREAD

**Issue by Profpatsch** [purescript/purescript#3706] opened 2019-07-28 22:34 UTC
`spago run` should be the same as running the program manually, meaning it shouldn’t print build information to `stdout`, but `stderr`.

Related: https://github.com/spacchetti/spago/issues/256

**Comment by LiamGoodacre** [comment] 2019-07-29 09:03
duplicate of https://github.com/purescript/purescript/issues/3672 ?

**Comment by hdgarrood** [comment] 2019-07-29 14:32
We currently print errors and warnings to stderr, but as described in #3672, I think we should print them to stdout. (I also think that the "Compiling Prelude" messages should go to stderr, while they currently go to stdout.)

I don't think the compiler should completely avoid printing to stdout just for the purpose of tools like `spago run`; if it is desired that `spago run` prints only program output to stdout, then I think it ought to be spago's responsibility to ensure that happens.

**Comment by Profpatsch** [comment] 2019-07-29 14:53
> duplicate of #3672 ?

No, this doesn’t mean #3672 needs to be implemented.

> I don't think the compiler should completely avoid printing to stdout just for the purpose of tools like `spago run`;

Not even other parts of spago have to avoid `stdout`, only `spage run` should not print to it.

**Comment by Profpatsch** [comment] 2019-07-29 14:54
Ah, my bad, I thought I opened this issue in the `spago` repository.

**Closed** 2019-07-29 14:54 UTC
