### ISSUE TITLE
Main fails silently when unsafePartial isn't employed 

### ISSUE THREAD

**Issue by jasonzoladz** [purescript/purescript#2211] opened 2016-06-27 21:28 UTC
This code will compile, but `main` will not run in a browser.  There is no error in the console.

```purescript
import Prelude
import Data.Maybe
import Control.Monad.Eff (Eff)
import Control.Monad.Eff.Console (logShow, CONSOLE, log)


main :: forall e. (Partial) => Eff (console :: CONSOLE | e) Unit
main = do
  log "Hello sailor!"
  let aMaybeValue = Just "Hello"
  logShow aMaybeValue

  let ifThenElseString =
        if (isJust aMaybeValue)
        then fromJust aMaybeValue
        else "It's Nothing"
  log ifThenElseString
```

This compiles and runs.

```purescript

import Prelude
import Data.Maybe
import Control.Monad.Eff (Eff)
import Control.Monad.Eff.Console (logShow, CONSOLE, log)
import Partial.Unsafe (unsafePartial)

main :: forall e. (Partial) => Eff (console :: CONSOLE | e) Unit
main = do
  log "Hello sailor!"
  let aMaybeValue = Just "Hello"
  logShow aMaybeValue

  let ifThenElseString =
        if (isJust aMaybeValue)
        then unsafePartial $ fromJust aMaybeValue
        else "It's Nothing"
  log ifThenElseString
```

Perhaps add a warning upon compilation that points to [this](https://github.com/purescript/purescript/wiki/The-Partial-type-class)?

**Comment by hdgarrood** [comment] 2016-06-27 21:43
This is admittedly very unfortunate, but it's not fully clear how to address it. See also #2086 (which this is a duplicate of).

**Closed by hdgarrood** 2016-06-27 21:43 UTC

**Comment by jasonzoladz** [comment] 2016-06-27 21:46
It's worse than described in #2086.  That is, you can add a `Partial` constraint like in the first example above and it still fails silently.  You *must* use `unsafePartial` for `main` to work.

**Comment by hdgarrood** [comment] 2016-06-27 21:53
The example I used in the original issue description is different, but this is the same issue. Note that `Partial => Eff a b` is a different type from `Eff a b`.

**Comment by hdgarrood** [comment] 2016-06-27 21:53
Also, I do understand the severity of this issue. It's bitten me too, even: https://github.com/purescript/purescript/issues/2086#issuecomment-220777054
