### ISSUE TITLE
Annotation only required for function within let block

### ISSUE THREAD

**Issue by milesfrain** [purescript/purescript#3922] opened 2020-08-27 19:18 UTC
## Description

Some code fails to compile with an un-annotated function in a `let` block; however, the same code _will_ compile if the un-annotated function is moved outside of the let block.

## To Reproduce

```purs
map3 :: forall a b c d. (a -> b -> c -> d) -> Array a -> Array b -> Array c -> Array d
map3 fn a b c =
  let
    -- Annotation is required if toZip is defined in let block
    --toZip :: forall x. Array x -> ZipList x
    toZip = ZipList <<< LazyList.fromFoldable
    la = toZip a
    lb = toZip b
    lc = toZip c
  in
    Array.fromFoldable $ lift3 fn la lb lc

-- It's fine to define without annotation globally
--toZip = ZipList <<< LazyList.fromFoldable
```
https://try.ps.ai/?gist=87e51987560be0007e7291699afcacd4

There is no compilation issue with an un-annotated `toZip` within a `let` block if it can be monomorphic throughout the `let` block. Thanks to @3ddyy for discovering this.
```purs
-- Annotation not required for ?monomorphic? toZip
map3mono :: forall a. (a -> a -> a -> a) -> Array a -> Array a -> Array a -> Array a
map3mono fn a b c =
  let
    toZip = ZipList <<< LazyList.fromFoldable
    la = toZip a
    lb = toZip b
    lc = toZip c
  in
    Array.fromFoldable $ lift3 fn la lb lc
```

## Expected behavior

I expect the version with an un-annotated `toZip` in the `let` block to compile.

## PureScript version

0.13.8

**Comment by natefaubion** [comment] 2020-08-27 19:21
This is intended behavior. It's because PureScript does not do let-generalization. We only implicitly generalize at the top-level of a module. See https://www.microsoft.com/en-us/research/wp-content/uploads/2016/02/tldi10-vytiniotis.pdf for the motivation.

**Comment by natefaubion** [comment] 2020-08-27 19:50
I'm going to close this, but I'll also note that while we will generalize at the top-level, we emit a warning to add the signature.

**Closed by natefaubion** 2020-08-27 19:50 UTC
Labels: bug

**Comment by milesfrain** [comment] 2020-08-27 20:15
Capturing keep points from this discussion in https://github.com/purescript/documentation/pull/350
