### ISSUE TITLE
Make file paths clickable in terminal

### ISSUE THREAD

**Issue by ad-si** [purescript/purescript#3472] opened 2018-12-03 15:47 UTC
File paths in warnings and errors are currently not clickable, because it doesn't match the common patterns to specify lines and columns. E.g. currently it prints:

```txt
Warning found:
in module Transity.Data.Ledger
at src/Transity/Data/Ledger.purs line 44, column 1 - line 44, column 42
```

This should be changed to:

```txt
Warning found:
in module Transity.Data.Ledger
at src/Transity/Data/Ledger.purs:44:1 - 44:42
```

Haskell and Rust already use this style:

```txt
/Users/adrian/Projects/tasklite/app/Main.hs:177:1: error:
    Parse error: module header, import declaration
    or top-level declaration expected.
    |
177 | foobar
    | ^^^^^^
```

```txt
[Running cargo fmt && cargo test]
error: expected one of `!` or `::`, found `use`
 --> /Users/adrian/Projects/textalyzer/src/lib.rs:6:1
  |
4 | foobar
  |       - expected one of `!` or `::` here
5 |
6 | use pad::{Alignment, PadStr};
  | ^^^ unexpected token
```

**Comment by ad-si** [comment] 2018-12-03 16:37
E.g. iTerm2 => https://www.iterm2.com/documentation-smart-selection.html

So actually the Terminal only supports actions for certain patterns. In this case it open my specified editor. The editor itself is then the program to understand the path:line:column format and open it accordingly and I know that at least Atom, Sublime, and VSCode are supporting it.

**Comment by hdgarrood** [comment] 2018-12-03 16:49
It sounds like you could also configure iTerm2 to recognise the current format and open an editor anyway? Unless there are many terminals other than iTerm2 which do this, I'm inclined to agree with @garyb that the current format is much easier to read, and I think most people probably are reading it themselves (if they're seeing it at all, that is &mdash; editor plugins can jump straight to error locations, of course). It's not really our place as maintainers to call a workflow where someone is reading the error message themselves 'wrong', imo.

**Comment by hdgarrood** [comment] 2018-12-03 16:52
Oh sorry, as you said the issue is of course that you'd need your editor to recognise the format.

**Comment by ad-si** [comment] 2018-12-03 17:17
- `subl readme.md:13:5` works
- `atom readme.md:13:5` works
- Textmate's ![screen shot 2018-12-03 at 17 06 41z](https://user-images.githubusercontent.com/36796532/49389319-e1d8e380-f71d-11e8-907b-a6e3dae464d9.png) works
- ```
    $ ag --vimgrep 'alt='
    readme.md:13:3:  alt='Screenshot Balance'
   ```
- Haskell's compiler uses the format
- Rust's compiler uses the format
- Node.js uses the format
- Ruby uses the format
- Go uses the format
- …

I mean, how much more evidence do you want that this is the way to go? 😒

**Comment by natefaubion** [comment] 2018-12-03 17:31
FWIW, `psa` uses the `line:col` format.

**Comment by ad-si** [comment] 2018-12-03 17:33
@hdgarrood Well, than how about you say something productive to the topic instead of bashing my argumentation style.

**Comment by natefaubion** [comment] 2018-12-03 17:33
> @hdgarrood Well, than how about you say something productive to the topic instead of bashing my argumentation style.

This is uncalled for. I'll second @hdgarrood's suggestion.

**Comment by ad-si** [comment] 2018-12-03 17:38
Well, if this is so important to you, what about:

```
Warning found:
in module Components.Toggle
at src/Components/Toggle.purs:6:1 - 6:101 (line 6, column 1 - line 6, column 101)
```

**Comment by JordanMartinez** [comment] 2018-12-03 18:12
The goal is to display a human-readable format (e.g. `line 4, column 1`), and a clickablel-URL format, correct? It seems like no one is against this goal.

However, what's our criteria for determining which approach is best? This seems to be the issue.

For example, in @ad-si's original approach that many others use...
> at src/Components/Toggle.purs:6:1 - 6:101

... results in some loss of readability: one needs to know the format to understand it (Is it `column:line` or `line:column` or something else entirely?) whereas the current approach is much more readily understandable. 

It's reasonable to try to combine it, as done in `ad-si`'s example immediately above this comment:
> at src/Components/Toggle.purs:6:1 - 6:101 (line 6, column 1 - line 6, column 101)

We gain back some readability but it still loses the "left-to-right" natural reading of
> at src/Components/Toggle.purs line 6, column 1 - line 6, column 101

On the other hand, doing it this way upholds both but at the cost of verbosity/duplication:
> at src/Components/Toggle.purs line 6, column 1 - line 6, column 101
> (view via the clickable link - src/Components/Toggle.purs:6:1 - 6:101)

**Comment by hdgarrood** [comment] 2018-12-03 18:14
I could get on board with

> at src/Components/Toggle.purs:6:1 - 6:101 (line 6, column 1 - line 6, column 101)

**Comment by ad-si** [comment] 2018-12-03 18:19
I was able to change the iTerm settings that it also works with the current formatting:

![screen shot 2018-12-03 at 18 15 28z](https://user-images.githubusercontent.com/36796532/49392922-c246b880-f727-11e8-9c1a-b77e023a8e94.png)

However, I know from many people that the click to open feature is one of their favorite terminal features, so I don't think it's a good default to let them add such complicated settings first.
Also, this probably only works with iTerm.

**Comment by chexxor** [comment] 2018-12-03 18:32
I'd be a little bit annoyed that location info is duplicated in the message and the reason it's like this is the result of a compromise. IMO, it seems like the ideal solution would be to have a sensible default which targets a single audience and make the output format configurable using some template language. I know "kubectl" for kubernetes accepts a common go-lang template for configuring the output of some commands. This output format could be configured in a command-line argument `--format="..."` or a config file, like ".gitconfig" for git. I know config files and flags are annoying and a bit controversial, but it seems inevitable.

I do agree with the original post that having a non-breaking word, or something which is easy to select and copy, to paste into an editor *would* be nice. That said, in my experience, the current format (the long-form one) has never bothered me, likely because my editor's IDE plugin gives exact line-column information in a visual way.

I don't know if it's the official guideline for it, but it seems like the current formatting is intended to be human-friendly. If being human-friendly is the current guideline for the formatting, I think it's hard to say that `Toggle.purs:6:1` is more human-friendly than `Toggle.purs line 44, column 1 - line 44, column 42`.

**Comment by ad-si** [comment] 2018-12-03 18:49
For the other compilers readability is less of a problem since they reprint that part of the code:

![screen shot 2018-12-03 at 18 44 25z](https://user-images.githubusercontent.com/36796532/49394369-988f9080-f72b-11e8-802c-33a7bfda3217.png)

So you can always see the line numbers of the output on the left side and you don't need the numbers in the URL anymore. That's also what Elm and Haskell do.
I guess this would actually be the best solution.

![screen shot 2018-12-03 at 18 48 29z](https://user-images.githubusercontent.com/36796532/49394524-0d62ca80-f72c-11e8-9d1c-80aff03307b5.png)

They also work with highlighting, so the filename could be highlighted and the rest grayed out.

**Comment by hdgarrood** [comment] 2018-12-03 18:56
I agree with the above; see also #1898. Including both the path:line:col format as well as the current format seems reasonable to me as an interim measure.

**Comment by LiamGoodacre** [comment] 2018-12-15 14:35
Closed by https://github.com/purescript/purescript/pull/3473

**Closed by LiamGoodacre** 2018-12-15 14:35 UTC
Labels: error-message
