### ISSUE TITLE
Cannot use a literal negative Int without parens

### ISSUE THREAD

**Issue by anttih** [purescript/purescript#2100] opened 2016-05-08 18:04 UTC
```
> show (-1)
"-1"

> show -1
Error found:
in module $PSCI
at  line 1, column 1 - line 1, column 7

  Could not match type

    Int

  with type

    _0 -> String


while checking that type Int
  is at least as general as type _0 -> String
while checking that expression 1
  has type _0 -> String
in value declaration it

where _0 is an unknown type
```

**Comment by hdgarrood** [comment] 2016-05-08 18:09
This is the same as what Haskell does, and I think it's the intended behaviour. To get both of these expressions to do what I assume you are wanting them to (namely, print "-1"), we would have to allow type information to influence parsing, which I don't think we want to do, as I expect it would significantly complicate compiler internals, and possibly also result in unpredictable behaviour.

**Comment by paf31** [comment] 2016-05-08 18:13
The alternative is to handle this in the lexer, with whitespace between the `-` and the `1` making the difference. In one case, there would be two lexemes, in the other, one.

**Comment by hdgarrood** [comment] 2016-05-08 18:16
Ah, of course. Still, if `3+4` and `3 +4` both work, then I think `3-4` and `3 -4` ought to both work too.

**Comment by paf31** [comment] 2016-05-08 18:27
Yes, I think we'd want positive literals to behave the same way, whatever we pick.

**Comment by paf31** [comment] 2016-05-08 19:08
I think this is one of those cases where we should pick an approach and stick to it, then keep this issue to log the decision. Moving to Discussion.

**Comment by AppShipIt** [comment] 2016-05-08 19:48
I prefer your single lexeme approach originally proposed in https://github.com/purescript/purescript/issues/1846#issuecomment-174323871.

**Comment by hdgarrood** [comment] 2016-05-08 19:57
I like how it is right now; I wouldn't want us to change `(- 1)` back to being an operator section for binary minus now that we require underscores for all other operator sections.

**Comment by garyb** [comment] 2016-05-08 19:58
Agreed ^

**Comment by anttih** [comment] 2016-05-08 20:19
As a user I'm strongly in favor of making `-1` to mean a negative Int. I would also expect `+1` to be valid. In contrast, I'd never write `3+4` and to me `3 -4` looks like it should not parse at all.

**Comment by hdgarrood** [comment] 2016-05-08 20:22
`-1` on its own is a negative int; the following is fine:

```purescript
module Main where

import Prelude
import Control.Monad.Eff.Console (print)

main = print x
  where
  x = -1
```

You might not write `3+4` but I know a few people who would.

**Comment by AppShipIt** [comment] 2016-05-08 23:35
> In contrast, I'd never write 3+4 and to me 3 -4 looks like it should not parse at all.

User expectations coming from any other language I'm familiar with is my reason as well. But as discussed in the linked thread I can't recall the last time I calculated using negative literals.

**Comment by rgrempel** [comment] 2016-05-09 20:59
Here's an example where it would be nice to be able to use negative literals without the parentheses. 

https://github.com/rgrempel/purescript-elm/blob/master/examples/Graphics/CollageExamples.purs#L659-L666

Now, one wouldn't ideally be using Tuples here, and the negative literals do work better with records. But I've got other reasons why I'm using Tuples.

**Comment by kika** [comment] 2016-05-10 04:16
@hdgarrood 
> -1 on its own is a negative int; 

Well, depends on definition of "on its own", see:
```
> let x = -1
Error found:
in module $PSCI
at  line 1, column 9 - line 1, column 10
  Unknown value negate
> import Prelude
> let x = -1
> x
-1
```

Personally, I'd prefer for the compiler to be non-whitespace sensitive unless absolutely necessary. I just found confusing that `foreign import data XXX :: *` is whitespace sensitive around `::`  while `xxx::XXX -> YYY` is not.
So for me `3 -4` is just `3 - 4` or `3-4` while `3--4` or `3 - -4` means `3 - (-4) = 3+4`

**Comment by AppShipIt** [comment] 2016-05-10 04:19
> I'd prefer for the compiler to be non-whitespace sensitive unless absolutely necessary.

Typed holes are also whitespace dependent which would be relatively consistent with this.

**Comment by natefaubion** [comment] 2016-05-10 13:18
> So for me `3 -4` is just `3 - 4` or `3-4` while `3--4` or `3 - -4` means `3 - (-4) = 3+4`

I don't think `3--4` parses as `3 - -4` in any language that supports a decrement operator.

**Comment by paf31** [comment] 2016-09-25 00:32
Closing, see above. Also, I don't see enough benefit to warrant breaking the syntax, for the sake of two characters.

**Closed by paf31** 2016-09-25 00:32 UTC
Labels: question, syntax

**Comment by rightfold** [comment] 2017-12-14 21:45
Another solution is to use different symbols for subtraction and negation. APL does this.
