### ISSUE TITLE
Loop and memory leak with typed hole and recursive newtype

### ISSUE THREAD

**Issue by LiamGoodacre** [purescript/purescript#3386] opened 2018-06-19 21:23 UTC
The following causes a compiler loop and consumes more and more memory:
```purescript
newtype X a = X (X (X a))
xToY :: X Int -> X (X Int)
xToY = ?ohNo
```

**Comment by rhendric** [comment] 2020-12-27 05:44
Closing because I can't reproduce this in the 0.14.0 release candidate.

**Closed by rhendric** 2020-12-27 05:44 UTC
Labels: bug, typechecker
