### ISSUE TITLE
Missing line and column information in error messages

### ISSUE THREAD

**Issue by paulyoung** [purescript/purescript#2203] opened 2016-06-21 18:41 UTC
I was in the middle of some refactoring a couple of weeks ago and noticed that some errors had missing information, which made them harder to locate.

I first noticed this in Atom via the [`ide-purescript`](https://github.com/nwolverson/atom-ide-purescript) package and was able to reproduce on the command line.

The errors in question are `1/10` and `2/10` below.

<img width="1072" alt="screen shot 2016-06-11 at 6 11 43 pm" src="https://cloud.githubusercontent.com/assets/84700/16241367/28321ede-37a2-11e6-9930-6bebeaab3b15.png">

I believe this was using:
- psc 0.9.1
- pulp 9.0.1
- psa 0.3.9
- node 6.2.1

**Comment by paulyoung** [comment] 2016-06-21 18:42
To clarify, the errors had missing _line and column_ information.

**Comment by paf31** [comment] 2016-07-10 23:36
I think the solution here is to add position information to types. We don't have a `PositionedType` data constructor right now. This is quite a bit more work than I think we should do in 0.9.2, so I'm moving this back to 0.10.0.

**Comment by paf31** [comment] 2016-07-11 00:00
Actually, this is a dupe of #2216.

**Closed by paf31** 2016-07-11 00:00 UTC
Labels: bug, error-message
