### ISSUE TITLE
Cannot derive generic for constructor containing a record type synonym

### ISSUE THREAD

**Issue by garyb** [purescript/purescript#1718] opened 2015-12-16 15:49 UTC
``` purescript
import Data.Generic (Generic)

type X = { value :: String }

data XG = XG X

derive instance genericXG :: Generic XG
```
```
  No type class instance was found for

    Data.Generic.Generic { value :: String
                         }


in value declaration genericXG
```

But it works if you use the record directly:

``` purescript
import Data.Generic (Generic)

data XG = XG { value :: String }

derive instance genericXG :: Generic XG
```

**Comment by paf31** [comment] 2015-12-16 16:34
Duplicate of #1443.

**Closed by paf31** 2015-12-16 16:34 UTC
Labels: bug

**Comment by garyb** [comment] 2015-12-16 16:35
Ah, whoops.
