### ISSUE TITLE
Importing the current module does not result in a distinct error

### ISSUE THREAD

**Issue by Benjmhart** [purescript/purescript#3623] opened 2019-05-06 03:25 UTC
If you are operating in Data.MyModule,  and attempt to import Data.MyModule in any capacity, this should result in a parse error.

However the current behavior is to report an Unknown Value error when the compiler encounters an imported value from the module.

**Comment by hdgarrood** [comment] 2019-05-06 07:36
This is a duplicate of #3079 and is fixed in master :)

**Closed by hdgarrood** 2019-05-06 07:36 UTC
