### ISSUE TITLE
Error message always uses fully qualified name

### ISSUE THREAD

**Issue by tfausak** [purescript/purescript#2059] opened 2016-04-27 14:49 UTC
Error messages always use the fully-qualified name, even if that name is already in scope. For example:

``` purescript
> import Prelude
> newtype X a = X (Array a)
> map (_ + 1) (X [1, 2])
```

```
Error found:
  No type class instance was found for
    Prelude.Functor X
```

I think it would be nice if that error just said:

```
Error found:
  No type class instance was found for
    Functor X
```

**Comment by garyb** [comment] 2016-04-27 15:02
This is a duplicate of #1647 I think?

**Comment by garyb** [comment] 2016-04-27 15:03
Actually, not quite, that's talking about adding qualification where needed - I guess this is a case where it's unnecessarily qualified. Similar idea though!

**Comment by tfausak** [comment] 2016-04-27 15:04
Yeah, this seems very similar to that issue. I didn't find that when I searched for this. Feel free to close as a duplicate.

**Comment by AppShipIt** [comment] 2016-04-27 15:13
For posterity the motivating use case from @tfausak's talk:

``` purescript
import Neon
newtype MyList a = MyList (Array a)
map (_ + 1) (MyList [1, 2, 3])
```

```
Error found:
  No type class instance was found for
    Neon.Class.HasMap.HasMap MyList
```

Where Neon masks the hierarchy to be user friendly.

**Comment by garyb** [comment] 2016-04-27 15:47
Ok, closing as duplicate then. The idea in the other issue will address this: the idea being to qualify according to the scope where the error arises, so if it's unqualified, show the error that way, if it's qualified with some custom name, use that. etc.

I'd love to do this right now (we get a lot of "Could not unify Query with Query" type errors in SD), but it's not super straightforward, I'll need to try some things out.

**Closed by garyb** 2016-04-27 15:47 UTC
Labels: duplicate
