### ISSUE TITLE
"the module could not be parsed" error in optimized build

### ISSUE THREAD

**Issue by joelgrus** [purescript/purescript#1981] opened 2016-03-28 23:27 UTC
In 0.8.3, if I make a new project and build it, it works fine:

```bash
$ pulp init
$ pulp build
* Building project in /home/joel/src/test
psc: No files found using pattern: src/**/*.js
* Build successful.
```

but if I try to do an optimised build, I get an error in the bundling step:

```bash
$ pulp build --to dist/index.js
* Building project in /home/joel/src/test
psc: No files found using pattern: src/**/*.js
* Build successful.
* Bundling Javascript...
Error in module Prelude (Foreign):

  The module could not be parsed:
  lexical error @ line 216 and column 14

* ERROR: Subcommand terminated with error code 1
```

If I look in `output/Prelude/foreign.js` the problem seems to be in `exports.showCharImpl` which has some odd string literals in it? (`"\a"`)

If I comment out that method (and also `exports.showStringImpl`) the bundling works.

(I had a similar problem with `purescript-test-unit`, but this is pretty much the minimal case.)

**Comment by hdgarrood** [comment] 2016-03-28 23:28
I think this is a duplicate of https://github.com/purescript/purescript-prelude/issues/65.

**Comment by joelgrus** [comment] 2016-03-28 23:31
Looks like it, I'll close this one.

**Closed** 2016-03-28 23:30 UTC

**Comment by nwolverson** [comment] 2016-03-29 07:37
Was conflicted where to raise this. For reference psc uses Haskell rules for strings (via Parsec) but doesn't output `\a` from compiled PureScript source (rather `\x07`). `\&` is also supported (nothing is output). So just an issue from writing unfortunate FFI.
