### ISSUE TITLE
Improve  `Could not match type` message

### ISSUE THREAD

**Issue by wclr** [purescript/purescript#4091] opened 2021-05-18 14:06 UTC
## Summary

On type mismatch the common message is:
```
 Could not match type

    { data :: String
    }

  with type

    Int

while checking that type Int
  is at least as general as type { data :: String
```

This message can be seen as kind of ambiguous and can be interpreted in two ways:

- Could not match **expected** type .. with **actual** type

- Could not match **actual** type .. with **expected** type

## Motivation

I'm talking from the perspective of a user and I notice that this simple and ubiquitous message from time to time adds cognitive load to the analysis of what is going on with the error, in this example: what should I look for in the code `Int` type variable or `{ data :: }` thing.

If to say that it's an obvious thing and the error is marked in the code, this still doesn't make this message unambiguous and more user-friendly by itself.

## Proposal

To modify the message, adding the specifiers **expected/actual/found** as it put above.

**Comment by kritzcreek** [comment] 2021-05-18 14:10
Duplicate of https://github.com/purescript/purescript/issues/3399?

**Comment by wclr** [comment] 2021-05-18 14:58
Yeah, I even didn't check, my bad. It's a surprise for me that the order is not consistent in the message.

**Comment by garyb** [comment] 2021-05-18 15:06
Closing as a duplicate then, since the other is still open!

**Closed by garyb** 2021-05-18 15:06 UTC
Labels: enhancement
