### ISSUE TITLE
inferred type not correct

### ISSUE THREAD

**Issue by zhangmaku** [purescript/purescript#3572] opened 2019-03-20 06:17 UTC
```
[55/55 MissingTypeDeclaration] src/App/View/Homepage.purs:111:1
  111  timeTools tvalue changeEvent (State s) = do
  112    div ! className "input-group mb-3" $ do
  113      input ! className "form-control" ! type' "number"
  114        ! value (show $ tvalue)
  115        ! step "1"  #! onChange ((readFloat <<< targetValue) >>> changeEvent )
  116      div ! className "input-group-append" $ do
  117        span ! className "input-group-text" $ text $ "time"
  118        span ! className "input-group-text"
  119           $ text $ format (zeroFill <> precision 2) (compareDay tvalue (State s)) <> " days"


  No type declaration was provided for the top-level declaration of timeTools.
  It is good practice to provide type declarations as a form of documentation.
  The inferred type of timeTools was:

forall t22. Number -> (Number -> t22) -> State -> Free (MarkupM (Event -> t22)) Unit

in value declaration timeTools
```
my use case
```
timeTools (exTx.time) ChangeNewExTxEntryTime (State s)
timeTools (exTx.time) (ChangeExTxEntryTime exTx.id) (State s)
```
Write the inferred type on the code, appear

```
[1/1 TypesDoNotUnify] src/App/View/Homepage.purs:113:5
  113      input ! className "form-control" ! type' "number"
  114        ! value (show $ tvalue)
  115        ! step "1"  #! onChange ((readFloat <<< targetValue) >>> changeEvent )
```
                                                                    
  Could not match type

    Event

  with type

    Event

Pulp version 12.3.1
purs version 0.12.3 using /usr/local/bin/purs

**Comment by LiamGoodacre** [comment] 2019-03-20 09:45
@zhangmaku Make sure you have the correct `Event` type in scope.
Not quite a bug, but a confusing error message as the types aren't qualified relative to the current module's imports - duplicate of https://github.com/purescript/purescript/issues/1647

**Closed by LiamGoodacre** 2019-03-20 09:45 UTC
