### ISSUE TITLE
Move where clauses under guards

### ISSUE THREAD

**Issue by pseudonom** [purescript/purescript#888] opened 2015-02-19 02:29 UTC
In Purescript,

``` purescript
foo | a = 1 where a = true
```

throws `Unknown value 'a'` on compilation.

(Haskell allows this.)

**Comment by michaelficarra** [comment] 2015-02-19 05:04
This seems pretty gross to me. Can you provide any samples of this being used to specify a function more elegantly than would otherwise be possible?

**Comment by paf31** [comment] 2015-02-19 05:40
I didn't know this was possible in Haskell. What does it desugar to?

**Comment by michaelficarra** [comment] 2015-02-19 05:42
I don't think this is specific to guards in Haskell. I believe any expression can have a `where`:

```
$ ghci
GHCi, version 7.8.4: http://www.haskell.org/ghc/  :? for help
Loading package ghc-prim ... linking ... done.
Loading package integer-gmp ... linking ... done.
Loading package base ... linking ... done.
λ> let x = a where a = 1
λ> x
1
λ>
```

**Comment by pseudonom** [comment] 2015-02-19 18:07
> Can you provide any samples of this being used to specify a function more elegantly than would otherwise be possible?

It's not the only way to write the function, but I initially tried guarded `where`s with a smart constructor:

```purescript
mkFoo :: Bar -> Either Error Foo
mkFoo a | test1 a = Left Err1 where test1 = ...
mkFoo a | test2 a = Left Err2 where test2 = ...
mkFoo a | test3 a = Left Err3 where test3 = ...
mkFoo a | otherwise = Right (Foo a)
```
(Effectively, a multi-way conditional.)

It's not obvious to me that there's a better way to write that.

**Comment by mietek** [comment] 2015-07-30 22:53
This syntax is used in Haskell to make all variables bound in the `where` clause available in all guards. For example, instead of writing
```purescript
topLeftCorner :: Rect -> Line -> Maybe Line
topLeftCorner r l | l.y2 > r.ytop = Nothing
                  | otherwise     = let d = delta l
                                    in  aux r l d (topProduct r l d) (leftProduct r l d)

aux :: Rect -> Line -> Point -> Number -> Number -> Maybe Line
aux r l d ptop pleft | ptop > pleft = leftBottomRegion r l d pleft
                     | otherwise    = reflectLineXMinusY <$> leftBottomRegion (reflectRectXMinusY r) (reflectLineXMinusY l) (reflectPointXMinusY d) ptop
```
I should be able to write
```purescript
topLeftCorner :: Rect -> Line -> Maybe Line
topLeftCorner r l | l.y2 > r.ytop = Nothing
                  | otherwise     = aux r l

aux :: Rect -> Line -> Maybe Line
aux r l | ptop > pleft = leftBottomRegion r l d pleft
        | otherwise    = reflectLineXMinusY <$> leftBottomRegion (reflectRectXMinusY r) (reflectLineXMinusY l) (reflectPointXMinusY d) ptop
        where
          d     = delta l
          ptop  = topProduct r l d
          pleft = leftProduct r l d
```

**Comment by nullobject** [comment] 2016-03-24 10:02
Just to clarify above:

- a `let` can be part of any value expression.
- a `where` clause is bound across all guards.

This is perfectly valid haskell syntax:
```haskell
f :: Int -> String
f x
  | x == one = let a = "foo" in a
  | x == two = b
  | otherwise = "baz"
  where
    b = "bar"
    one = 1
    two = 2
```

Looking at the psc code, I'm not sure how the `ValueDeclaration` could support this structure?

```haskell
ValueDeclaration Ident NameKind [Binder] (Either [(Guard, Expr)] Expr)
```

Perhaps with something like this?

```haskell
ValueDeclaration Ident NameKind [Binder] (Either ([(Guard, Expr)], Expr) Expr)
```

**Comment by paf31** [comment] 2016-03-24 23:55
`where` clauses get desugared to `let` in the parser. I think we might be able to fix this by having the parser desugar guards to a `case` statement with zero arguments, and slotting the `let` in before that.

**Comment by Vikasg7** [comment] 2018-08-13 02:56
@paf31  
No Sir, The following code:  
```haskell
f :: Int -> String
f x = 
  let
    b = "bar"
    one = 1
    two = 2
  in case of
       | x == one = let a = "foo" in a
       | x == two = b
       | otherwise = "baz"
```  
produces following error message in repl:  
```
  Unable to parse module:
  unexpected "of"
  expecting expression
```  

I came to this thread while doing exercise problem from your purescript book.  
I came up with following code for my problem. Here is how I am able to use local variables/binding in the guard.  
```Haskell
import Prelude
import Data.Array.Partial (head, tail)
import Partial.Unsafe (unsafePartial)

isEven :: Int -> Boolean
isEven num = mod num 2 == 0

countEvens :: Array Int -> Int
countEvens [] = 0
countEvens arr =
   let
      x  = unsafePartial $ head arr
      xs = unsafePartial $ tail arr
   in
      go x xs
   where
      go :: Int -> Array Int -> Int
      go x xs | isEven x  = 1 + countEvens xs
              | otherwise = countEvens xs
```
The above code would have been cut short if binding in where clause where available in guards.  
Hope to see this syntax implemented soon.

**Comment by Vikasg7** [comment] 2018-08-13 11:15
@LiamGoodacre  you need to replace `=` with `->` in the body of the `case` statement.  
I edited my previous comment.

**Comment by garyb** [comment] 2018-08-13 13:35
I think Phil was suggesting a desugaring for the no-case guard, not user-level syntax for a workaround.

**Comment by natefaubion** [comment] 2019-05-24 18:45
Note that Phil's desugaring suggestion does not reproduce Haskell's behavior, since the guards would not go to the next case on failure.

```haskell
example = \case
  Foo a
    | isThat a -> ...
    where isThat = ...
  Bar b -> ...
```

If the guard for `isThat` fails, it should try the `Bar` branch. The let/case desugaring does not accomplish this. I don't think there is a faithful desugaring. Additionally, strictness means that you can easily evaluate too much if you only use some bindings in some of the guards.

**Comment by natefaubion** [comment] 2020-02-06 19:38
I think that this should be closed. It deviates from Haskell sure, but I think it makes the most sense given PureScript's strictness.

**Comment by hdgarrood** [comment] 2020-02-08 13:34
> Note that Phil's desugaring suggestion does not reproduce Haskell's behavior, since the guards would not go to the next case on failure.

Just to make sure I've understood this. Are you saying that, for example, if you wrote

```purescript
f (Foo x)
  | x `mod` 5 == 0 = fizz
  | x `mod` 3 == 0 = buzz
  where
  fizz = "Fizz"
  buzz = "Buzz"
f (Foo x)
  = show x
```

then it would desugar to

```purescript
f (Foo x) =
  let
    fizz = "Fizz"
    buzz = "Buzz"
  in
    case of
      | x `mod` 3 == 0 = fizz
      | x `mod` 5 == 0 = buzz
f (Foo x) =
  show x
```

which is not what a Haskell user would expect because it won't fall through to the `show x` case if x is not a multiple of either 3 or 5?

**Comment by natefaubion** [comment] 2020-02-08 14:31
Yes, that’s correct. There isn’t a way to faithfully desugar it into existing case constructs. However, we do have a consistent rule that where scopes over = and ->.

**Comment by hdgarrood** [comment] 2020-02-08 15:08
Right, thanks. Yeah I think I'm going to close this then, given that, plus the fact that we now have three maintainer :+1: s for closing.

**Closed by hdgarrood** 2020-02-08 15:08 UTC
Labels: codegen, enhancement, syntax

**Comment by prednaz** [comment] 2020-05-26 02:47
```purescript
f (Foo x) (Bar y)
  | x `mod` 5 == 0 = fizz <> fizz
  | x `mod` 3 == 0 = buzz
  where
    fizz = "Fizz"
    buzz = "Buzz"
f (Foo x) (Baz y) = show x
```
could desugar to
```purescript
f p1 p2 =
  let
    fizz = "Fizz"
    buzz = "Buzz"
  in
    case (p1 /\ p2) of
      (Foo x /\ Bar y)
        | x `mod` 5 == 0 -> fizz <> fizz
        | x `mod` 3 == 0 -> buzz
      (Foo x /\ Baz y) -> show x
```
or even more interestingly to
```purescript
f p1 p2 =
  let
    fizz unit = "Fizz"
    buzz unit = "Buzz"
  in
    case (p1 /\ p2) of
      (Foo x /\ Bar y)
        | x `mod` 5 == 0 -> fizz unit <> fizz unit
        | x `mod` 3 == 0 -> buzz unit
      (Foo x /\ Baz y) -> show x
```
.

Will users be confused by implicitly introducing laziness like that? - They are not in the case of If-Then-Else expressions. And `where` is even more clearly a built-in keyword because If-Then-Else expressions at least form expressions. Even in lazy Haskell you could not replace `where` by any user defined construct while you could replace If-Then-Else expressions with applications of a user-defined `if'` function very well.

However, there is the problem of the lack of sharing. If the user writes `fizz <> fizz`, the definition of `fizz unit` would be evaluated twice. I know PureScript to little to say how this would be taken care of best. Maybe there is something like `unsafePerformEffekt`, which you could use inside of the `fizz :: Unit -> String` function, or you use the FFI there, or maybe `where` is so inherently built-in that it is supported best by baking it into the compiler itself.

I personally rely on `where` in Haskell so much that the more difficult it is to support it in PureScript, the more important it seems to provide it for users instead of pushing the responsibility onto them, especially if it takes baking it into the compiler itself.
