### ISSUE TITLE
Need upper bound on optparse-applicative

### ISSUE THREAD

**Issue by glguy** [purescript/purescript#2309] opened 2016-09-17 00:12 UTC
Possibly among other issues, psc-publish is not compatible with all version of optparse-applicative >= 0.12.1, In the current version of optparse-applicative the <> operator is no longer exported.

An upper bound of < 0.13.0.0 is needed

found a related ticket: https://github.com/haskell-infra/hackage-trustees/issues/74

**Comment by hdgarrood** [comment] 2016-09-17 19:01
This is fixed in master, so won't be a problem once we release 0.9.4. The only thing left to do now would be to add a revision for 0.9.3 in hackage to include this upper bound.

**Closed** 2016-09-17 19:48 UTC

**Comment by phadej** [comment] 2016-09-19 07:48
@hdgarrood for all versions since 0.6.2: http://matrix.hackage.haskell.org/package/purescript#GHC-7.8/purescript-0.6.2

**Comment by hdgarrood** [comment] 2016-09-19 07:53
None of the others is supported, though. I realise you disagree but I don't think this is worth doing.

**Comment by gbaz** [comment] 2016-09-19 13:19
@hdgarrood , @paf31 I would highly recommend doing this even for unsupported versions. The problem is that in any workflow that invokes a solver, the wrong (old) version may be chosen, producing invalid install plans. Its only a bit more work to retroactively edit old hackage metadata, and it typically ends up preventing a fair amount of confusion for end-users.
