### ISSUE TITLE
very tricky unification error message due to lazy vs strict variant of non imported type

### ISSUE THREAD

**Issue by rvion** [purescript/purescript#2266] opened 2016-08-07 09:43 UTC
### EDIT: see second message for the explanation

I just found an other unification bug.

I report it in case it triggers a different case than in previous unification bug reports (I think it does)

here, the type is unambiguous: I have a `List (Tuple String String)`, but from what I understand, purescript is telling me that it can't see it's a `List (Tuple String a)`

![image](https://cloud.githubusercontent.com/assets/2150990/17461623/5fd29150-5c93-11e6-9107-f19dff5ec988.png)

here:

```purescript
fromList :: forall a. List (Tuple String a) -> StrMap a
cutAfter :: String -> String -> Tuple String String
```

**Comment by rvion** [comment] 2016-08-07 09:55
Arf....

it's a problem with Lazy lists vs non Lazy.
I think there is an important discoverability problem here.

my whole file was: 

```purescript
import Prelude
import Control.Monad.Eff (Eff)
import Control.Monad.Eff.Console (CONSOLE, log)
import Data.List.Lazy (replicateM)
import Data.StrMap (StrMap, fromList)
import Data.String (split)
import Data.Tuple.Nested ((/\))
import Util (cutAfter, debug, readLine, readInt)

main :: forall e. Eff (console :: CONSOLE | e) Unit
main = do
  n <- readInt
  q <- readInt
  ns <- fromList <$> replicateM n (cutAfter " " <$> readLine)
  qs <- replicateM q readLine
  debug n
  debug q
  debug (show ns)
  debug (show qs)
  log "done"
```

 -> here, list was never imported;
 -> when hovering above types in my ide, I was not able to see the difference because 

     🔴  fromList :: forall a. __List__ (Tuple String a) -> StrMap a
     🔴  replicateM :: forall m a. (Monad m) => Int -> m a -> m (__List__ a)


So this problem might be __very__ difficult to debug as there was no visible problem

**Comment by garyb** [comment] 2016-08-07 10:23
It's a duplicate of #1647 in that case :)

**Closed by garyb** 2016-08-07 10:23 UTC
