### ISSUE TITLE
Mass library update for 0.7.0

### ISSUE THREAD

**Issue by garyb** [purescript/purescript#1038] opened 2015-04-07 21:40 UTC
Contrib:

- [x] [purescript-channels](https://github.com/purescript-contrib/purescript-channels) (@jdegoes)
- [x] [purescript-machines](https://github.com/purescript-contrib/purescript-machines) (@jdegoes)
- [x] [purescript-strongcheck](https://github.com/purescript-contrib/purescript-strongcheck) (@jdegoes)
- [x] [purescript-base](https://github.com/purescript-contrib/purescript-base) (@jdegoes)
- [x] [purescript-argonaut](https://github.com/purescript-contrib/purescript-argonaut) (@jdegoes)
- [x] [purescript-dom](https://github.com/purescript-contrib/purescript-dom) (@garyb)
- [x] [purescript-arraybuffer-types](https://github.com/purescript-contrib/purescript-arraybuffer-types) (@garyb)
- [x] [purescript-parsing](https://github.com/purescript-contrib/purescript-parsing) (@paf31)
- [x] [purescript-lens](https://github.com/purescript-contrib/purescript-lens) (@joneshf)
- [x] [purescript-react](https://github.com/purescript-contrib/purescript-react) (@paf31)
- [x] [purescript-these](https://github.com/purescript-contrib/purescript-these) (@puffnfresh?)

Node:
- [x] [purescript-node-path](https://github.com/purescript-node/purescript-node-path)
- [x] [purescript-node-buffer](https://github.com/purescript-node/purescript-node-buffer)
- [x] [purescript-node-fs](https://github.com/purescript-node/purescript-node-fs)
- [x] [purescript-node-readline](https://github.com/purescript-node/purescript-node-readline) `0.2.0`
- [x] [purescript-node-fs-aff](https://github.com/purescript-node/purescript-node-fs-aff)

**Comment by paf31** [comment] 2015-06-06 01:55
Everything compiles again, now we "just" need to go through and update the Bower versions and docs.

**Comment by paf31** [comment] 2015-06-06 01:56
I haven't worked on contrib yet, just core.

**Comment by garyb** [comment] 2015-06-07 00:29
I've done some work on `purescript-lists` but not quite finished with it yet - I'm trying to ensure `Data.Array`, `Data.List` and `Data.List.Lazy` all have the same operations available (where sensible, obviously lazy will have some extra stuff, etc.), and also to update them all to use the same tests for these operations.

**Comment by paf31** [comment] 2015-06-16 20:19
I still need to find out the status for `streams` and `react`, but if you are marked as the maintainer on a contrib library (@garyb, @joneshf, @jdegoes), please try to update your libraries to compile with 0.7 and add documentation.

Thanks.

**Comment by paf31** [comment] 2015-06-19 20:41
I suggest we identify the maintainer clearly in the project README for every contrib project. Example: https://github.com/purescript-contrib/purescript-parsing

Please remember to update your contrib projects before the 0.7 release.

**Comment by paf31** [comment] 2015-06-19 20:43
Also, any contrib projects which are unmaintained (currently `react`, and I'm still not sure about `streams`, @puffnfresh ?) could be identified as such in red.

Come to think of it, it would also be nice to have badges for compiler compatibility, and for links to Pursuit docs later.

**Comment by jdegoes** [comment] 2015-06-19 20:45
I will do this over the weekend or, for repos in SlamData, divvy the work up. Do we have a migration guide yet? Also, when will the 0.7 release come out?

**Comment by paf31** [comment] 2015-06-19 20:48
0.7 will be out as soon as we write and test the DCE implementation with the new FFI. Gary and I plan to have a look at it this weekend, hopefully.

The release notes currently serve as an approximation to the migration guide, and I'll make sure they're as thorough as possible before release.

**Comment by joneshf** [comment] 2015-06-19 21:16
I'm out of town until Monday, so it'll be a while until I get time to do anything.

Do we need to do release candidates like the rest of the libraries have so far, or how does that work?

We can use something like http://shields.io/ for badges.

**Comment by paf31** [comment] 2015-06-19 21:28
> We can use something like http://shields.io/ for badges.

Yep, that's what I used for the parsing library :)

I suggest that if you want to release anything, releasing a pre-release version, tagged with `vX.Y.Z.-rc.1`, like we did for the core libraries. When we release the compiler, we can rename the tags all at once. I use `purescript-lens` and `purescript-index` for the `todo` example in `purescript-thermite` (so nothing important, really), but whenever you have time to update it, I'd definitely appreciate it.

**Comment by garyb** [comment] 2015-06-20 00:16
Shields.io is pretty nifty.

**Comment by paf31** [comment] 2015-06-29 17:06
The new release of the compiler should hopefully be out today or tomorrow, so now's a good time to update your contrib libraries.

Also, I think I'll take over maintainership of `purescript-react`, since nobody else seems to want to, which just leaves `purescript-streams` (@puffnfresh, can I assume that one's yours?)

**Comment by puffnfresh** [comment] 2015-06-29 22:36
If the problem is that it's in -contrib, then we can just move purescript-streams over to my personal account. No problem.

**Comment by paf31** [comment] 2015-06-29 22:38
@puffnfresh Whatever you prefer, I just want to make sure that things in `contrib` will get maintained by _someone_. If it's dead for now, then yes please, let's move it out.

**Comment by puffnfresh** [comment] 2015-06-29 22:40
Done :+1:

**Comment by paf31** [comment] 2015-06-29 22:48
Thanks!

**Comment by jdegoes** [comment] 2015-07-03 16:39
I (or the SlamData team) should get to these in the coming week. Sorry for the delay!

**Comment by paf31** [comment] 2015-07-03 18:28
@jdegoes Great stuff, thanks!

**Comment by hdgarrood** [comment] 2015-07-06 14:28
purescript-node-buffer and purescript-node-fs are done.

**Closed** 2015-07-13 17:49 UTC
Labels: libraries
