### ISSUE TITLE
Instance search with type synonym fails

### ISSUE THREAD

**Issue by natefaubion** [purescript/purescript#1370] opened 2015-08-12 18:38 UTC
```purescript
module TransformerFail where

import Prelude
import Control.Monad.State.Class

type Context = Int

phail :: forall m. (Monad m, MonadState Context m) => Int -> m Int
phail i = phail (i - 1)
```
```
Error found:
Error in module TransformerFail:
Error in binding group phail:
No instance found for Control.Monad.State.Class.MonadState TransformerFail.Context<> m3
```

If I change `Context` to `Int` in the signature, it type checks.

**Comment by paf31** [comment] 2015-08-12 18:39
I'm beginning to think that just desugaring all synonyms up front would be good.

**Comment by garyb** [comment] 2015-08-12 20:19
Is this a duplicate of #1275 / #1027. Not sure about the former, almost certainly the latter.

I have an idea I'd like to try as a way of dealing with synonyms, I think I mentioned it to you - kinda a hybrid desugaring, where we keep the synonym but attach the inner desugared type too. I'll perhaps get a chance to look at that at the weekend.

**Comment by paf31** [comment] 2015-08-12 21:25
No for the first, yes for the second. The first is about how `forall` is handled.

**Closed by paf31** 2015-08-12 21:26 UTC
Labels: bug, typechecker
