### ISSUE TITLE
Request: be explicit about 'expected' and 'actual' types

### ISSUE THREAD

**Issue by knjk04** [purescript/purescript#3703] opened 2019-07-25 15:44 UTC
I'm new to Purescript and I was initially confused about which type was the expected type and which was the actual type from the error message. Could we change the error message to specify that x is the 'expected type' and y is the 'actual type' (like Haskell)?

E.g. instead of 

>   Could not match type
>     Effect NonElementParentNode
>   with type
>     NonElementParentNode

it would be this

>   Could not match **actual** type
>     Effect NonElementParentNode
>   with **expected** type
>     NonElementParentNode

**Comment by hdgarrood** [comment] 2019-07-25 16:02
Thanks for the report. Yes, we would like to do this at some point. It's a non-trivial amount of work, though, which is why it hasn't happened already. This is a duplicate of #3399, which I've just reopened.

**Closed by hdgarrood** 2019-07-25 16:02 UTC
