### ISSUE TITLE
Superclass appearing twice with distinct variables gets swallowed

### ISSUE THREAD

**Issue by matthewleon** [purescript/purescript#3221] opened 2018-01-25 02:12 UTC
Thanks to @MonoidMusician for the help naming this and thinking through it a bit with me.

Here is some code that compiles. You can play with it in Try Purescript here: http://try.purescript.org/?session=6415730a-7da3-4edd-de2c-c336e6caafd8&backend=core&gist=7dde67cb93037272461652330c5a7069

```purescript
module Main where

import Prelude
import Data.Maybe (Maybe, fromJust)
import Partial.Unsafe (unsafePartial)

class Substructure g h where
  toSuper :: h -> g
  fromSuper :: g -> Maybe h

class (Substructure g h, Semigroup g) <= Subsemigroup g h

defaultAppend :: forall g h. Subsemigroup g h => h -> h -> h
defaultAppend x y =
    unsafePartial
  $ fromJust
  $ (fromSuper :: g -> Maybe h)
  $ toSuper x <> toSuper y
```

Let's try adding a second `Semigroup` constraint in the `Subsemigroup` class, this one to `h`. The compiler seems to lose the ability to find the `Semigroup` instance for `g`: http://try.purescript.org/?session=6415730a-7da3-4edd-de2c-c336e6caafd8&backend=core&gist=67cc93ae6cfdbf6301401721d65c4b2b

```
purescript
module Main where

import Prelude
import Data.Maybe (Maybe, fromJust)
import Partial.Unsafe (unsafePartial)

class Substructure g h where
  toSuper :: h -> g
  fromSuper :: g -> Maybe h

class (Substructure g h, Semigroup g, Semigroup h) <= Subsemigroup g h

defaultAppend :: forall g h. Subsemigroup g h => h -> h -> h
defaultAppend x y =
    unsafePartial
  $ fromJust
  $ (fromSuper :: g -> Maybe h)
  $ ((toSuper x) :: g) <> ((toSuper y) :: g)
```

**Comment by matthewleon** [comment] 2018-01-25 02:26
A quick note that what I'm trying to do here is a bit dumb, as the definition of `Substructure` makes no real sense... That said, it feels like I _should_ be allowed to do it by the typechecker.

**Comment by MonoidMusician** [comment] 2018-01-25 15:39
My notes:
- Adding `Semigroup g` to the type signature of `defaultAppend` works
- I've run into the issue in my own project which is why I think it has to do with duplicate superclasses: https://github.com/MonoidMusician/purescript-datagen/blob/aa1115d039acbf5b64a23e5d27e185a74d453818/src/Zippers.purs#L42
- It looks like the superclasses _should_ be available, at least from the codegen:
```javascript
var Subsemigroup = function (Semigroup1, Semigroup2, Substructure0) {
    this.Semigroup1 = Semigroup1;
    this.Semigroup2 = Semigroup2;
    this.Substructure0 = Substructure0;
};
```
- This seems to be the code that adds superclass dictionaries in scope and nothing looks obviously wrong to me: https://github.com/purescript/purescript/blob/ce94cd94e836a013c52ab8f7545ff6dd63c7e69c/src/Language/PureScript/TypeChecker/Entailment.hs#L566

**Comment by LiamGoodacre** [comment] 2018-01-25 19:25
I believe this is a duplicate of https://github.com/purescript/purescript/issues/2959

**Closed** 2018-01-25 21:10 UTC
Labels: duplicate
