### ISSUE TITLE
Inference regression in master

### ISSUE THREAD

**Issue by natefaubion** [purescript/purescript#3114] opened 2017-10-14 06:31 UTC
I actually don't know how to title this issue, so please edit it to make it more appropriate.

`purescript-variant`s tests do not compile on master anymore, and it's throwing me for a loop. In particular, using `#` with `on` chaining results in an inexplicable error:

```
[1/1 TypesDoNotUnify] test/VariantF.purs:43:13

                  v
  43      case1 = case_
  44        # on _foo (\a → "foo: " <> show a)
  45        # on _bar (\a → "bar: " <> show a)
  46        # on _baz (\a → "baz: " <> show a)
                                             ^

  Could not match type

    Array

  with type

    Tuple String

  while trying to match type Array
    with type Tuple String
  while trying to match type FProxy Array
    with type FProxy (Tuple String)
  while trying to match type ( baz :: FProxy t16
                             , bar :: FProxy Array
                             , foo :: FProxy Array
                             )
    with type ( foo :: FProxy Maybe
              , bar :: FProxy (Tuple String)
              , baz :: FProxy (Either String)
              )
  while solving type class constraint

    Prim.RowCons "baz"
                 (FProxy t16)
                 t10
                 ( foo :: FProxy Maybe
                 , bar :: FProxy (Tuple String)
                 , baz :: FProxy (Either String)
                 )
```

The rest of the verbose errors are unprintable due to very strange formatting. For reference, here is the test code https://github.com/natefaubion/purescript-variant/blob/master/test/VariantF.purs#L42-L46

*   I do not use or mention `Array` anywhere in the variant codebase, no literals, nothing.
*   If I don't use `#` syntax it works (either parens or `$` instead).
*   I have made no changes to the code (compiles fine on 0.11.6)

**Comment by parsonsmatt** [comment] 2017-12-19 03:24
I'm unable to reproduce this on current `purescript` master and current `purescript-variant` master. Are you still seeing this?

**Comment by natefaubion** [comment] 2017-12-19 03:26
On master or the 0.12 branch?

**Comment by natefaubion** [comment] 2017-12-19 03:26
Probably warrants a title edit since we split off the 0.12 branch.

**Comment by parsonsmatt** [comment] 2017-12-19 03:27
Oh, I misread -- `purescript-variant`'s master branch, not `purescript`'s master :sweat_smile:

**Comment by natefaubion** [comment] 2017-12-19 03:27
It _was_ purescript master when this issue was written :)

**Comment by parsonsmatt** [comment] 2017-12-19 03:40
I just checked out `0.12.0-dev`, built the compiler, and ran the test suite for `purescript-variant`. I'm not able to reproduce :confused:

**Comment by parsonsmatt** [comment] 2017-12-19 05:10
`git bisect` identifed aacdb9abd0c81320e6c13c71dfaf92b060acd66a as the first bad commit that introduces the regression.

I must not be using `git bisect` correctly, because I can't find a "first commit" that *fixes* the regression :man_shrugging:

**Comment by natefaubion** [comment] 2017-12-19 06:11
That's good to know! I wonder how that resulted in `Array` being propagated everywhere.

**Comment by parsonsmatt** [comment] 2017-12-19 07:13
`Array` is entry number `0` in the list of types when I dump the state.`[]` and `0` were the default values provided to all the old constructors where a chain was possible, as `tcdIndex = 0`.No idea if that's related but that's the only hypothesis I have.

**Comment by hdgarrood** [comment] 2017-12-19 08:10
Do you think you might be able to come up with a minimal example that triggers this bug between those commits?

**Comment by parsonsmatt** [comment] 2017-12-19 16:19
I'll try to get something up for that.

**Comment by parsonsmatt** [comment] 2017-12-20 03:01
OK, I've got a PR up for some test cases for this. The tests are green on current master, and I don't know why.

- Error appears to be thrown from `solve` in `entails` because that's the only location of a hint for `ErrorSolvingConstraint`
- `TypesDoNotUnify` seems to mostly be thrown from `unifyTypes'` which is unsurprising.
- `unifyTypes` seems to be called here:
  ```haskell
            solution <- lift . lift $ unique tys'' instances
            case solution of
              Solved substs tcd -> do
                -- Note that we solved something.
                tell (Any True, mempty)
                -- Make sure the substitution is valid:
                lift . lift . for_ substs $ pairwiseM unifyTypes
```
- I attach some, uh, debugging machinery to the `unique` cases that actually return stuff:

```haskell
            unique _      x@[(a, dict)] = do
                let !() = unsafePerformIO $ T.writeFile "only_one.txt" (T.pack (show x)) 
                return $ Solved a dict
-- ...
              | otherwise = do
                  let !() = unsafePerformIO $ T.writeFile "tcds.txt" (T.pack (show tcds)) 
                  return $ uncurry Solved (minimumBy (compare `on` length . tcdPath . snd) tcds)

```

I run the test case, and sure enough, we've got a `only_one.txt` hanging out in the repo, containing (pretty-printed):

```haskell
[ ( fromList []
  , TypeClassDictionaryInScope
    { tcdChain = []
    , tcdIndex = 0
    , tcdValue = ConsInstance
    , tcdPath = []
    , tcdClassName =
        Qualified
          (Just (ModuleName [ProperName {runProperName = "Prim"}]))
          (ProperName {runProperName = "RowCons"})
    , tcdInstanceTypes =
        [ TypeLevelString "bar"
        , TypeApp
            (TypeConstructor
               (Qualified
                  (Just
                     (ModuleName
                        [ProperName {runProperName = "VendoredVariant"}]))
                  (ProperName {runProperName = "FProxy"})))
            (TUnknown 21)
        , RCons
            (Label {runLabel = "foo"})
            (TypeApp
               (TypeConstructor
                  (Qualified
                     (Just
                        (ModuleName
                           [ProperName {runProperName = "VendoredVariant"}]))
                     (ProperName {runProperName = "FProxy"})))
               (TypeConstructor
                  (Qualified
                     (Just (ModuleName [ProperName {runProperName = "Prim"}]))
                     (ProperName {runProperName = "Array"}))))
            REmpty
        , RCons
            (Label {runLabel = "bar"})
            (TypeApp
               (TypeConstructor
                  (Qualified
                     (Just
                        (ModuleName
                           [ProperName {runProperName = "VendoredVariant"}]))
                     (ProperName {runProperName = "FProxy"})))
               (TUnknown 21))
            (RCons
               (Label {runLabel = "foo"})
               (TypeApp
                  (TypeConstructor
                     (Qualified
                        (Just
                           (ModuleName
                              [ProperName {runProperName = "VendoredVariant"}]))
                        (ProperName {runProperName = "FProxy"})))
                  (TypeConstructor
                     (Qualified
                        (Just (ModuleName [ProperName {runProperName = "Prim"}]))
                        (ProperName {runProperName = "Array"}))))
               REmpty)
        ]
    , tcdDependencies = Nothing
    })
]
```

So we're passing this guy in for some reason. The `instances` variable is defined with:

```haskell
            let instances = do
                  chain <- groupBy ((==) `on` tcdChain) $
                           sortBy (compare `on` (tcdChain &&& tcdIndex)) $
                           forClassName (combineContexts context inferred) className' tys''
                  -- process instances in a chain in index order
                  let found = for chain $ \tcd ->
                                -- Make sure the type unifies with the type in the type instance definition
                                case matches typeClassDependencies tcd tys'' of
                                  Apart        -> Right ()                  -- keep searching
                                  Match substs -> Left (Just (substs, tcd)) -- found a match
                                  Unknown      -> Left Nothing              -- can't continue with this chain yet, need proof of apartness
                  case found of
                    Right _               -> []          -- all apart
                    Left Nothing          -> []          -- last unknown
                    Left (Just substsTcd) -> [substsTcd] -- found a match
```

This means that `matches typeClassDependencies tcd sys''` returned `Match substs` for those arguments.

Why, though? I suspect the `substituteTypes` function. So I dump some more debug info:

```haskell
            latestSubst <- lift . lift $ gets checkSubstitution
            let tys'' = map (substituteType latestSubst) tys'
            let !() = unsafePerformIO $ T.appendFile "substituteType.hs" 
                       (T.pack (unlines ["-- latest Substitution", show latestSubst, "-- tys'", show tys', "-- tys''", show tys'', "", ""]))
```

The final output in the file is:

```haskell
-- latest Subtitution
-- ...snipping, this is like 500 lines
      , ( 13
        , TypeConstructor
            (Qualified
               (Just (ModuleName [ProperName {runProperName = "Prim"}]))
               (ProperName {runProperName = "Array"})))
-- more snips...

-- tys'
[ TypeLevelString "bar"
, TypeApp
    (TypeConstructor
       (Qualified
          (Just (ModuleName [ProperName {runProperName = "VendoredVariant"}]))
          (ProperName {runProperName = "FProxy"})))
    (TUnknown 21)
, TUnknown 9
, RCons
    (Label {runLabel = "foo"})
    (TypeApp
       (TypeConstructor
          (Qualified
             (Just (ModuleName [ProperName {runProperName = "VendoredVariant"}]))
             (ProperName {runProperName = "FProxy"})))
       (TypeConstructor
          (Qualified
             (Just
                (ModuleName
                   [ ProperName {runProperName = "Data"}
                   , ProperName {runProperName = "Maybe"}
                   ]))
             (ProperName {runProperName = "Maybe"}))))
    (RCons
       (Label {runLabel = "bar"})
       (TypeApp
          (TypeConstructor
             (Qualified
                (Just
                   (ModuleName [ProperName {runProperName = "VendoredVariant"}]))
                (ProperName {runProperName = "FProxy"})))
          (TypeApp
             (TypeConstructor
                (Qualified
                   (Just
                      (ModuleName
                         [ ProperName {runProperName = "Data"}
                         , ProperName {runProperName = "Tuple"}
                         ]))
                   (ProperName {runProperName = "Tuple"})))
             (TypeConstructor
                (Qualified
                   (Just (ModuleName [ProperName {runProperName = "Prim"}]))
                   (ProperName {runProperName = "String"})))))
       REmpty)
]
-- tys''
[ TypeLevelString "bar"
, TypeApp
    (TypeConstructor
       (Qualified
          (Just (ModuleName [ProperName {runProperName = "VendoredVariant"}]))
          (ProperName {runProperName = "FProxy"})))
    (TUnknown 21)
, RCons
    (Label {runLabel = "foo"})
    (TypeApp
       (TypeConstructor
          (Qualified
             (Just (ModuleName [ProperName {runProperName = "VendoredVariant"}]))
             (ProperName {runProperName = "FProxy"})))
       (TypeConstructor
          (Qualified
             (Just (ModuleName [ProperName {runProperName = "Prim"}]))
             (ProperName {runProperName = "Array"}))))
    REmpty
, RCons
    (Label {runLabel = "foo"})
    (TypeApp
       (TypeConstructor
          (Qualified
             (Just (ModuleName [ProperName {runProperName = "VendoredVariant"}]))
             (ProperName {runProperName = "FProxy"})))
       (TypeConstructor
          (Qualified
             (Just
                (ModuleName
                   [ ProperName {runProperName = "Data"}
                   , ProperName {runProperName = "Maybe"}
                   ]))
             (ProperName {runProperName = "Maybe"}))))
    (RCons
       (Label {runLabel = "bar"})
       (TypeApp
          (TypeConstructor
             (Qualified
                (Just
                   (ModuleName [ProperName {runProperName = "VendoredVariant"}]))
                (ProperName {runProperName = "FProxy"})))
          (TypeApp
             (TypeConstructor
                (Qualified
                   (Just
                      (ModuleName
                         [ ProperName {runProperName = "Data"}
                         , ProperName {runProperName = "Tuple"}
                         ]))
                   (ProperName {runProperName = "Tuple"})))
             (TypeConstructor
                (Qualified
                   (Just (ModuleName [ProperName {runProperName = "Prim"}]))
                   (ProperName {runProperName = "String"})))))
       REmpty)
]
```

At some point, the substitution map got the entry:

```haskell
      , ( 9
        , RCons
            (Label {runLabel = "foo"})
            (TypeApp
               (TypeConstructor
                  (Qualified
                     (Just
                        (ModuleName
                           [ProperName {runProperName = "VendoredVariant"}]))
                     (ProperName {runProperName = "FProxy"})))
               (TUnknown 13))
            REmpty)
```

Then, when `substituteType` checks for the `TUnknown 13`, it returns the `Data.Array` entry in the type substitution map.

My batteries for debugging are drained at this point. Hopefully this is useful

**Comment by kRITZCREEK** [comment] 2018-01-03 19:46
Can this be closed? I tested it on current master with and without the annotation and it compiles and runs fine.

**Comment by parsonsmatt** [comment] 2018-01-03 19:50
Yes, this was introduced in a commit that did the instance chains and was later fixed in another commit. The #3175 PR introduced regression tests for it to ensure it won't happen again.

**Closed** 2018-01-03 23:10 UTC
Labels: bug, typechecker
