### ISSUE TITLE
PureScript 0.13.0 doesn't build with cabal

### ISSUE THREAD

**Issue by vmchale** [purescript/purescript#3654] opened 2019-05-30 21:22 UTC
Running `cabal new-install purescript` yields various errors of the sort

```
      in the definition of data constructor ‘HappyWrap180’
     |
1130 | newtype HappyWrap180 = HappyWrap180 ([(SourceToken, _)])
     |                                                     ^

dist/build/Language/PureScript/CST/Parser.hs:1137:53: error:
    Wildcard ‘_’ not allowed
      in the definition of data constructor ‘HappyWrap181’
     |
1137 | newtype HappyWrap181 = HappyWrap181 ([(SourceToken, _)])
     |                                                     ^

dist/build/Language/PureScript/CST/Parser.hs:1144:50: error:
    Wildcard ‘_’ not allowed
      in the definition of data constructor ‘HappyWrap182’
     |
1144 | newtype HappyWrap182 = HappyWrap182 (NE.NonEmpty _)
     |                                                  ^

dist/build/Language/PureScript/CST/Parser.hs:1151:50: error:
    Wildcard ‘_’ not allowed
      in the definition of data constructor ‘HappyWrap183’
     |
1151 | newtype HappyWrap183 = HappyWrap183 (NE.NonEmpty _)
     |                                                  ^

dist/build/Language/PureScript/CST/Parser.hs:1158:50: error:
    Wildcard ‘_’ not allowed
      in the definition of data constructor ‘HappyWrap184’
     |
1158 | newtype HappyWrap184 = HappyWrap184 (NE.NonEmpty _)
     |                                                  ^

dist/build/Language/PureScript/CST/Parser.hs:1165:53: error:
    Wildcard ‘_’ not allowed
      in the definition of data constructor ‘HappyWrap185’
     |
1165 | newtype HappyWrap185 = HappyWrap185 ([(SourceToken, _)])
     |                                                     ^

dist/build/Language/PureScript/CST/Parser.hs:1172:53: error:
    Wildcard ‘_’ not allowed
      in the definition of data constructor ‘HappyWrap186’
     |
1172 | newtype HappyWrap186 = HappyWrap186 ([(SourceToken, _)])
     |                                                     ^

dist/build/Language/PureScript/CST/Parser.hs:1179:53: error:
    Wildcard ‘_’ not allowed
      in the definition of data constructor ‘HappyWrap187’
     |
1179 | newtype HappyWrap187 = HappyWrap187 ([(SourceToken, _)])
     |                                                     ^
```

I believe the package bounds should also be restricted, see https://matrix.hackage.haskell.org/#/package/purescript

**Comment by natefaubion** [comment] 2019-05-30 23:14
As of right now, we don't explicitly support anything other than the `stack` workflow in the project itself. However, a PR for getting it to build with `cabal` would be appreciated. I'm not sure what needs to be done for `happy`.

**Comment by natefaubion** [comment] 2019-05-30 23:21
For reference https://github.com/purescript/purescript/blob/738aaa2f21097c7f18aa8100b16ae52316addb04/INSTALL.md

**Comment by vmchale** [comment] 2019-05-30 23:24
@natefaubion right but it was uploaded to hackage with incorrect bounds and without the `build-tools` field specified

**Comment by hdgarrood** [comment] 2019-05-31 16:51
@vmchale I'll deal with the version bounds when I get a moment. Do you know what we need to do with the `build-tools` field?

**Comment by vmchale** [comment] 2019-05-31 16:53
I believe it should specify a dependency on `happy`, i.e. `build-tools: happy` in the appropriate library stanza

**Comment by natefaubion** [comment] 2019-05-31 16:54
According to https://www.haskell.org/cabal/users-guide/developing-packages.html?highlight=build%20tool#pkg-field-build-tool-depends `build-tools` is deprecated and we should use `build-tool-depends`.

**Comment by vmchale** [comment] 2019-05-31 19:16
My mistake: in that case it should be `build-tool-depends: happy:happy`.

**Comment by hdgarrood** [comment] 2019-06-01 12:56
It turns out specifying `build-tool-depends` is not sufficient to get this working. There are two things going on here:
- Our parser leads to invalid code being generated when we pass the `--coerce` flag. As far as I can tell, this appears to be a bug in our parser and not in Happy; see e.g. https://github.com/simonmar/happy/pull/134, it's intended behaviour that we can sometimes get compilation errors, and explicit forall is required for polymorphic productions (we're using type wildcards and implicit forall, which appears to be the source of these errors). It's probably worth fixing this because the `--coerce` flag is supposed to generate more efficient code; the happy manual recommends using `--array --ghc --coerce` if your parser is intended to be used with GHC.
- Stack and Cabal supply different flags when they invoke `happy`; in particular, Stack does not pass `--coerce` but Cabal does. Ideally there would be a way of saying which happy flags we want in our cabal file, but I haven't been able to work out what this is.

**Comment by hdgarrood** [comment] 2019-06-01 12:58
See https://groups.google.com/forum/#!topic/haskell-stack/9oKeSo-nz7U

**Comment by hdgarrood** [comment] 2019-06-01 13:00
So apparently cabal supports specifying flags to pass to build tools, but stack doesn't: https://github.com/commercialhaskell/stack/issues/2868

**Comment by hdgarrood** [comment] 2019-06-01 13:41
I've tightened the `base` lower bound on Hackage, but I think we're going to have to put out a 0.13.1 to address the failures you've listed.

**Comment by vmchale** [comment] 2019-06-01 13:50
@hdgarrood it could be put in the `cabal.project` file for people using github... or alternately via some command-line flags?

**Comment by hdgarrood** [comment] 2019-06-01 14:49
@vmchale It seems like it is to do with the version of `happy` which ends up being selected. I seem to have gotten it working by specifying
```
  build-tools:
      happy ==1.19.9
```
in the `library` section. Can you check and let me know if that works for you too?

**Comment by hdgarrood** [comment] 2019-06-01 15:04
I think my earlier comment https://github.com/purescript/purescript/issues/3654#issuecomment-497943101 is wrong, as strace indicates that Stack is in fact invoking `happy` with the `-agc` flags as well. I think it must just be because different versions of happy are being used. You may need to run `cabal v2-clean && cabal v2-configure` after adding the `build-tools` bit.

**Comment by hdgarrood** [comment] 2019-06-01 17:22
Oops, didn’t mean to reopen. Hackage matrix builder says we’re okay so I’m going to close this.

**Closed by hdgarrood** 2019-06-01 17:22 UTC

**Comment by chenrui333** [comment] 2019-06-05 01:25
Having some issue in the homebrew 0.13.0 upgrade, https://github.com/Homebrew/homebrew-core/pull/40498

Going to try some ideas in here.

**Comment by hdgarrood** [comment] 2019-06-07 12:40
@chenrui333 I'd recommend addressing this by downloading a later revision of the `purescript.cabal` file via the url https://hackage.haskell.org/package/purescript-0.13.0/purescript.cabal, and using that instead of the `purescript.cabal` contained in the original tarball. This workflow is probably something that homebrew's Haskell formulas should support more generally (if they don't already) as lots of Haskell packages rely on revisions.

**Comment by hdgarrood** [comment] 2019-06-07 12:42
Oh I suppose you're going to want to pin a particular revision and use a hash for integrity. You can find links to specific revisions at https://hackage.haskell.org/package/purescript-0.13.0/revisions/

**Comment by chenrui333** [comment] 2019-06-27 06:09
Good to know, trying to fix the build issue now.
