### ISSUE TITLE
Bug: can't match constrained type xxx with type xxx (same type)

### ISSUE THREAD

**Issue by rvion** [purescript/purescript#2229] opened 2016-07-15 12:29 UTC
on 0.9.2:

code:

```purescript
  let foo =
        if true
          then {test: id}
          else {test: id}
```

![image](https://cloud.githubusercontent.com/assets/2150990/16874182/325c1c44-4a98-11e6-9fc7-e12671da3589.png)

`id` is the regular identity function imported from prelude
![image](https://cloud.githubusercontent.com/assets/2150990/16874224/67d181f2-4a98-11e6-8a9a-34e696550ed4.png)

**Comment by garyb** [comment] 2016-07-15 12:35
Constrained types can't be unified at all, as far as I'm aware. This is arising due to the use of polymorphic, constrained `id` in a record.

**Comment by kRITZCREEK** [comment] 2016-07-15 12:39
Is this the impredicative type thing? ^^

**Comment by garyb** [comment] 2016-07-15 12:41
In the context of the record here, yeah I think so.

**Comment by paf31** [comment] 2016-07-18 17:11
We should be instantiating the polymorphic type before unification though, so this is a bug.

**Comment by garyb** [comment] 2016-07-18 17:36
This is the same as #1579 then, but that one was closed?

**Comment by paf31** [comment] 2016-07-31 01:14
Ugh, this one is a pain. On the one hand, we want `infer` on `id` to give back the polymorphic type, but here, we want it to be instantiated. I can't figure out if we need a special rule for record literals (that doesn't seem right) or if we need to do something different with `Var` in `infer`. I'll think about this some more.

There's something slightly different about something like `id` which is in scope globally, versus a `Var` like `f` in `\(x :: forall a. a -> a) -> x x`, where you're explicitly ascribing a polymorphic type, but right now we can't distinguish between those two cases nicely.

**Comment by texastoland** [comment] 2016-08-02 17:46
Possible duplicate of purescript/purescript#1957?

**Comment by garyb** [comment] 2016-08-02 17:48
@paf31 How does the record case differ from when doing the same thing with data constructors?

```
-- inferred type:
-- what :: forall t27 t28 t29 t30.                 
--   ( Category t27                        
--   , Category t29                        
--   ) => Tuple (t27 t28 t28) (t29 t30 t30)
what = Tuple id id
```

It seems like we have a few differences where records don't behave the same way seemingly equivalent things using data constructors, and I don't quite understand where the differences arise. This also goes back to the proposal that I freaked out about where the suggestion was to only allow monotypes in records :wink: - I'm just not sure _why_ they have these issues.

**Comment by paf31** [comment] 2016-08-02 17:50
The record case is more along the lines of impredicative polymorphism, since you don't have a data constructor where you can switch to checking mode.

**Comment by garyb** [comment] 2016-08-02 17:54
Interestingly @texastoland discovered a case of this in his localstorage work where leaving the type unspecified works, but stating it does not. I was surprised by that, as whenever I've encountered this issue I've not been able to change the behaviour with annotations or anything.

**Comment by texastoland** [comment] 2016-08-03 02:24
@garyb The return type was correctly inferred but fails to unify when passed to any other function with essentially the same type.

A key example where this would be nice is `Argonaut`'s [`foldJson`](https://github.com/purescript-contrib/purescript-argonaut-core/blob/f70e919e5f42194ab4f671bb739d80eb5803149d/src/Data/Argonaut/Core.purs#L90-L93) which accepts 7 functions. Aesthetically it'd be easier to read labeled.

Here's my [`localstorage` test](https://github.com/texastoland/purescript-localstorage/blob/refactor/test/Browser/LocalStorage.purs) with requisite `unsafeCoerce`s. @st58 originally authored the API and feels pleasantly object like by effectively currying `Storage` references into the record functions.

**Comment by paf31** [comment] 2016-10-01 22:28
Closing, see my previous notes regarding polymorphic things in records.

Also note, a type signature fixes this:

``` purescript
foo :: { test :: forall c a. Category c => c a a }
foo =
        if true
          then {test: id}
          else {test: id}
```

**Closed by paf31** 2016-10-01 22:28 UTC
Labels: bug, typechecker
