### ISSUE TITLE
Compiler really doesn't like point-free style when typeclass and recursive data structure are involved

### ISSUE THREAD

**Issue by edwardw** [purescript/purescript#3807] opened 2020-03-12 10:44 UTC
Consider the following code:

```purescript
module Main where

import Prelude
import Data.Generic.Rep (class Generic, Argument(..), Constructor(..), NoArguments, NoConstructors, Product(..), Sum(..), from)
import Data.Symbol (class IsSymbol)
import Effect (Effect)
import Effect.Console (log)


class Foo a where
  foo :: a -> String

instance fooUnit :: Foo Unit where
  foo _ = "Unit"

class GFoo a where
  gfoo :: a -> String

instance gfooNoConstructors :: GFoo NoConstructors where
  gfoo _ = "NoConstructors"

instance gfooNoArguments :: GFoo NoArguments where
  gfoo _ = "NoArguments"

instance gfooConstructor :: (GFoo a, IsSymbol name) => GFoo (Constructor name a) where
  gfoo (Constructor x) = "Constructor " <> gfoo x

instance gfooArgument :: Foo a => GFoo (Argument a) where
  gfoo (Argument x) = "(Argument " <> foo x <> ")"

instance gfooSum :: (GFoo a, GFoo b) => GFoo (Sum a b) where
  gfoo = case _ of
    Inl x -> "Inl " <> gfoo x
    Inr x -> "Inr " <> gfoo x

instance gfooProduct :: (GFoo a, GFoo b) => GFoo (Product a b) where
  gfoo (Product x y) = "Product " <> gfoo x <> " " <> gfoo y

genericFoo :: forall a rep. Generic a rep => GFoo rep => a -> String
genericFoo = gfoo <<< from

data Bar = V Unit | Lam Unit Bar | App Bar Bar

derive instance genericBar :: Generic Bar _

instance fooBar :: Foo Bar where
  foo x = genericFoo x

main :: Effect Unit
main = log $ foo (V unit)
```

It is a bit long but actually quite mechanical. It works, but if written point-free style:

```purescript
instance fooBar :: Foo Bar where
  foo = genericFoo
```

the compiler rejects it with the error

```
The value of fooBar is undefined here, so this reference is not allowed.
```

My guess is that it has to do with the extra constraints on the `genericFoo` signature. It has to be there because if moving these constraints to the instance head, it would be `UndecidableInstances` situation.

The workaround is trivial, of course. Just don't write point-free here but it is surprising.

Probably related to [purescript-generics-rep#23](https://github.com/purescript/purescript-generics-rep/issues/23).

**Comment by hdgarrood** [comment] 2020-05-10 20:32
This looks like expected behaviour to me. It's not to do with `UndecidableInstances`, it's to do with strictness. In fact, purescript behaves like GHC's `UndecidableInstances` by default. The reason this fails is as follows:

* While constructing a `Foo Bar` instance, you use `genericFoo` "immediately" (not under a function).
* This use of `genericFoo` requires a `GFoo` instance to be conjured up for the rep of `Bar`
* In the process of conjuring that instance, we come across the `Bar` values in the `App` constructor or `Bar`, which require a `Foo Bar` instance...
* but we haven't yet finished constructing the `Foo Bar` instance we wanted in the first place.

If we silenced the error and generated the code for it anyway, we'd end up with something like

```javascript
var fooBar =
  Foo(genericFoo(genericBar)(gFooArgument(fooBar)))
```

which wouldn't work; as the error says, the value of `fooBar` is undefined here (i.e. on the right hand side of its definition in a place where it would be needed immediately). Eta-expanding gives us something more like:

```javascript
var fooBar = Foo(function(x) {
  return genericFoo(genericBar)(gFooArgument(fooBar)))(x)
})
```

I think this might be a "wontfix"?

**Closed** 2020-05-14 10:03 UTC
