### ISSUE TITLE
Tail call elimination does not work with unsafePartial

### ISSUE THREAD

**Issue by leobm** [purescript/purescript#2288] opened 2016-08-25 23:26 UTC
psc version 0.9.3

First version is TC optimized 

``` purescript
length1 :: forall a. Array a -> Int
length1 =
  unsafePartial length1' 0
  where
  length1' :: forall b. (Partial) => Int -> Array b -> Int
  length1' acc arr =
    if null arr
    then acc
    else length1' (acc + 1) (tail arr)
```

``` javascript
var length1 = (function () {
      var length1$prime = function (__copy_dictPartial) {
          return function (__copy_acc) {
              return function (__copy_arr) {
                  var dictPartial = __copy_dictPartial;
                  var acc = __copy_acc;
                  var arr = __copy_arr;
                  tco: while (true) {
                      var $42 = Data_Array["null"](arr);
                      if ($42) {
                          return acc;
                      };
                      if (!$42) {
                          var __tco_dictPartial = dictPartial;
                          var __tco_acc = acc + 1 | 0;
                          var __tco_arr = Data_Array_Partial.tail(dictPartial)(arr);
                          dictPartial = __tco_dictPartial;
                          acc = __tco_acc;
                          arr = __tco_arr;
                          continue tco;
                      };
                      throw new Error("Failed pattern match at Main line 39, column 5 - line 41, column 39: " + [ $42.constructor.name ]);
                  };
              };
          };
      };
      return Partial_Unsafe.unsafePartial(function (dictPartial) {
          return length1$prime(dictPartial);
      })(0);
  })();
```

Second version is not TC optimised :

``` purescript
length2  :: forall a. Array a -> Int
length2 =
  length2' 0
  where
  length2' :: forall b. Int -> Array b -> Int
  length2' acc arr =
    if null arr
    then acc
    else length2' (acc + 1) (unsafePartial tail arr)
```

``` javascript
  var length2 = (function () {
      var length2$prime = function (acc) {
          return function (arr) {
              var $41 = Data_Array["null"](arr);
              if ($41) {
                  return acc;
              };
              if (!$41) {
                  return length2$prime(acc + 1 | 0)(Partial_Unsafe.unsafePartial(function (dictPartial) {
                      return Data_Array_Partial.tail(dictPartial);
                  })(arr));
              };
              throw new Error("Failed pattern match at Main line 29, column 5 - line 31, column 53: " + [ $41.constructor.name ]);
          };
      };
      return length2$prime(0);
  })();
```

**Comment by paf31** [comment] 2017-01-15 04:49
If we look at the generated JS:

```js
var length2 = (function () {
    var length2$prime = function (acc) {
        return function (arr) {
            var $3 = Data_Array["null"](arr);
            if ($3) {
                return acc;
            };
            if (!$3) {
                return length2$prime(acc + 1 | 0)(Partial_Unsafe.unsafePartial(function (dictPartial) {
                    return Data_Array_Partial.tail(dictPartial);
                })(arr));
            };
        };
    };
    return length2$prime(0);
})();
```

then we see that the problem is that `length2$prime` is tail-recursive, but calls itself with a function as an argument.

The compiler doesn't generate a loop in this case, because in general, it's possible for the function to capture variables which can then change during the loop.

In this case, it should be safe to generate a loop, since `unsafePartial` will call the function immediately, but the compiler can't know that without inspecting the function body. If we inlined `unsafePartial`, then this wouldn't be an issue.

I'm tempted to close this as <kbd>won't fix</kbd>, but it does seem like we ought to optimize this to something sensible.

**Closed** 2017-01-20 17:40 UTC
Labels: bug, codegen, optimizer
