### ISSUE TITLE
FFI: multiple backends, packaging, future plans

### ISSUE THREAD

**Issue by damncabbage** [purescript/purescript#2449] opened 2016-11-26 04:29 UTC
With `--dump-corefn` facilitating more PureScript backends (that don't require a full compiler fork), and the [recent packaging work](https://github.com/purescript/purescript/pull/2424) (including discussion of the information each package is going to encode), I can't help but feel that FFI is something that may come up again shortly.

This isn't something that likely has an answer (yet?), but I wanted to ask these questions to provoke discussion:

1. Can some PureScript code, that has a single FFI function for example, be compilable by both (say) JS and C++ backends if both language's FFI definitions are provided?
2. What happens if you have two FFI functions, one that only works on the JS backend, and the other that only works with C++? (Think of providing a uniform interface for a library that, by necessity, has very different internals for different backends.)
3. Is there a user-level way of detecting what the compiler is, to switch between different FFI implementations? Or would some definitions be C++-specific, others JS-specific, and others be implementable by any language?
4. How do we specify that a given chunk of code is compatible with a given backend? Is this Package-level? Type-level? Both?
5. How do we specify that a some code only works with _certain versions_ of a backend, eg. Node 4-6, Node 7+, etc?
6. Only slightly related, but also: how do we specify that some code only works with certain versions of the PureScript compiler?

There's a recurring theme to some of this, and that's asking what we specify in package-level metadata, what is encoded via types or other things in the language itself, and what belongs in both (eg. for ease of retrieval).

I don't have much experience with language FFI in general. To fellow FFI newbies, the [Idris docs](http://docs.idris-lang.org/en/latest/reference/ffi.html) may be interesting. I'm curious to see what other approaches people have seen.

Edit: "JS" and "C++" are just generic examples. Substitute "Visual Basic for Applications" or whatever you'd like. 😄

**Comment by starper** [comment] 2016-11-26 06:27
Maybe effects could help with some of this issues. But not that kind of effects, that we have now, wich, in my opinion, are pretty useless, but some kind of effects that describe what this code requires to run (like `es6` support, browser or node), not what code does (like logging, for example). Then you would need to somehow prove that everything that code requires is supported, otherwise it will throw an error immediately.
```purescript
-- Main.purs
module Main where
import Prelude
import Control.Monad.Eff (Eff)
import SomeModule (someES6Effect)
main :: forall e. Eff ( es6 :: ES6 | e ) Unit
main = someES6Effect
```
```javascript
// effects.js
exports.es6 = function () {
  return isES6Supported(); // somehow check if es6 is supported and then return true or false
}
```
Previous example was only for `JS`, but maybe it could be useful for different backends too:
```purescript
module Main where
import Prelude
import Control.Monad.Eff (Eff)
import SomeCOnlyLib (C)
import SomeCOnlyLib as CL
import SomeJSOnlyLib (JS)
import SomeJSOnlyLib as JSL

foo :: forall e. Eff ( backend :: C | e ) Unit
foo = CL.someEffect
bar :: forall e. Eff ( backend :: JS | e ) Unit
bar = JSL.someEffect

main :: forall e. Eff ( backend :: C | e ) Unit
main = foo
```
Now you can't use both `C` and `JS` implementations, you have to choose one and then somehow prove that it is supported.

What do you think about this idea?

**Comment by hdgarrood** [comment] 2016-11-26 14:51
1. Yes, that's what led us to the current design of separate FFI files. The aim is that people can provide both a `Foo.js` and a `Foo.cpp` alongside their `Foo.purs`; different backends should be able to look at just the relevant FFI file.
2. The only issue I can think of in this situation is that right now, the JS backend will throw an error if you have a `foreign import foo` statement with no corresponding `exports.foo` in the FFI file; we could either relax this a bit somehow, or we could tell people that in this case they should implement `exports.foo` in the JS FFI file in a way that throws an error saying 'This is unsupported with the JS backend'.
3. Yes, I'd do it like this:
    ```
    -- Backend.purs
    newtype Backend = Backend String -- perhaps there's a better way of doing this but this will do for now
    foreign import backend :: Backend

    -- Backend.js
    exports.backend = "js";

    -- Backend.cpp
    char backend[] = "pure11"; // i do not know C++ so pls forgive inevitable mistakes here
    ````
    I think we will probably want a library that does this at some point.
4. I'm not aware that this has been considered yet, but perhaps we don't need to specify this, because I think we can deduce this automatically - if there is a `foreign import` anywhere, then the supported backends are the intersection of the following:
    * The set of supported backends for the dependencies
    * The set of corresponding FFI files for each `foreign import`.
 
   I guess this is kind of expensive to compute so perhaps it would make sense to include this information in a package manifest file (together with a process that checks based on the above at the time of publishing a new version).
5. I'm not aware of a way of doing this currently. The `purescript-node` stuff only supports Node 4+, but if you try to run it on earlier versions it might give you a runtime error.
6. I think package sets will solve this problem to a large extent, but also most people include this information in the release notes AFAIK. If not, I think you can look at what versions of the core libraries something depends on - the core libraries definitely say what compiler versions are supported in their release notes. If anyone knows of languages that provide this information in a more direct way, though, I'd be interested to read about it.

My gut feeling is that tracking backend support at the type level will not really be worth the inconvenience. I can't see tracking backend support in the `Eff` row working too well, because then how do you track that information with a `foreign import` that doesn't involve the `Eff` type? Eg, what if I `foreign import` a `String` or a `Int -> String`?

**Comment by starper** [comment] 2016-11-26 16:14
@hdgarrood Maybe if function behaves differently with different backends it shouldn't be considered pure then? On the other hand there always will be some rough edges (some data types that are supported by one backend, but not supported by the other, for example), so maybe you are right and tracking this at the type level is not a good idea, maybe package level is more suitable for this. Something like `supported-backends: ['js', 'c']` in some `config` file.

**Comment by andyarvanitis** [comment] 2016-11-26 20:38
Speaking for the C++ backend, the "C++-specific" packages just have `*.hh` and `*.cc` FFI files present in addition to the usual `*.js` ones. Nothing else special is needed. See examples in https://github.com/pure11. There's nothing preventing unifying these packages (I'd really like to, in fact).

**Comment by nwolverson** [comment] 2016-11-26 23:19
For the Erlang backend, the same holds, that the same definitions can be used with additional `*.erl` FFI file, and under https://github.com/purerl can be found branches of core packages which have both the JS and Erl FFI. Things fall in 3 camps:

1. Able to give definitions for both `.js` and `.erl` FFI and work on both (with interesting subset of "pure" packages with no FFI)
1. Something has to change/not be supported on one backend (for Erlang, meaning e.g. mutable state/arrays), i.e. a proper fork
1. Specific to platform/backend - eg bindings to native datatypes, I have some of these which have no `.js` FFI files

Group 1. covers the majority of cases. My preference if using `--dump-corefn` is for this to not proceed to JS generation (or checking JS FFI), or be used in combination of some other option for that. I feel like we can do better and have a `--backend` flag which calls out to another executable, maybe passing a list of built files/modules in and getting errors/warnings back.

Definitely there needs to be some kind of backend/platform metadata, whether that is explicit in some config file or implicit in inclusion in some package set.

**Comment by paf31** [comment] 2016-11-28 17:45
Duplicate of #1692?

**Comment by damncabbage** [comment] 2016-11-29 01:38
There's _some_ overlap, eg. point 1, but I don't think the rest is covered, particularly anything to do with point 2-3's disparate FFI implementations in the same library, or point 4-6's package- or type-level metadata.
If you want I can move the discussion there, but I don't think it's a close-as-duplicate sort of thing.

**Comment by andyarvanitis** [comment] 2016-11-30 02:56
I'm pretty sure this has been covered by others, but it seems to me that the *general* strategy for FFI in packages is (or can be):
1) For packages that aren't really platform-specific, use as little FFI as possible -- mainly just whatever is needed to "bootstrap" the desired functionality or avoid really terrible performance. In these types of packages, FFI is almost a code smell. I think keeping to this, we won't have much of a problem with the different FFIs coexisting *
2) For packages that really are platform- or framework-specific (node, iOS, etc), you won't need multiple FFIs. Just like all good software, you would break out the non-platform stuff

\* It might be worth revisiting some of the standard and contrib packages to see if some FFI can be removed or consolidated

**Comment by damncabbage** [comment] 2016-11-30 12:51
Trying to address 3, 4, 5 and 6:

Is there room in psc-package.json for specification of, for a given package, a list of constraints on:
* Backends (eg. `["js", "cpp"]`, `erlang`, or empty / unset for all backends)
* OSs (eg. `["darwin", "linux"]`, `windows`, etc. and empty / unset as above) and Architecture (most likely needed for backends like C++; I need someone else to chime in here).
* Versions of backends...? (Like package.json's "engines"; this a stretch, but eg. `"node": [">= 4"]`. Again, optional.)
* PureScript compilers...? (eg. `[ ">= 0.9.*", "< 0.10" ]`; `prelude`, like `base`, could be a clumsy stand-in here, but prelude isn't meant to be a requirement if I remember correctly.)

_Some_ of the above may be implicitly encoded in something like a package-set, if you assume that the package-sets are always talking about a set for particular version of a compiler (for example), but I'd argue that:
* There are too many dimensions (and values along each dimension) to take this approach for _everything_, and
* You're left high and dry if you need to `extra-deps` something that's outside the package set, but don't have any of this information encoded in the package metadata itself.

(It's the same reason why I'd want constraints available for each package, even if said packages are part of a package-set; it'd be an unpleasant game of cartesian-explosion whackamole without them.)

Yes, FFI should be relatively rare. But no, I don't want people to have to go and read a README or release notes to figure out what a library requires; this is definitely one of those things that would benefit from the machine figuring things out (even if we can ignore what the machine says).

@hdgarrood: Good point about being able to deduce at a given time what backends are required for a library.

**Comment by garyb** [comment] 2016-11-30 13:16
I thought it was always part of the plan to have compiler compatibility information as part of a package set, but I could be wrong.

> Backend-dependent package dependencies needed for each package.

I'm not sure about this... I don't think this situation should arise at all, given the points @andyarvanitis raises above: FFI should be used for wrapping a platform specific library, or its use should be minimal to do something that is not otherwise possible in PureScript, but is backend agnostic (like `unsafeCoerce`, array functions, etc).

But even if the need does arise even once, we already have ways of doing this without special package-y support: write a fully generic, no-FFI interface based on typeclasses or `Free` or whatever that anyone can use, and then have backend specific implementations in separate libraries that provide the appropriate instances or interpreter.

**Comment by damncabbage** [comment] 2016-11-30 13:23
> FFI should be used for wrapping a platform specific library.

I'm not sure if by "platform" you mean Linux-vs-Darwin or JS-vs-Erlang. Could you clarify this?

**Comment by garyb** [comment] 2016-11-30 13:43
Ah sorry, yeah, I meant platform as in "node", so, backend.

**Comment by damncabbage** [comment] 2016-11-30 13:48
Okay.

> … and then have backend specific implementations in separate libraries that provide the appropriate instances or interpreter.

So let's say we do have this interpreter. A nice HTTP Server "interface" of some variety, with Express (in JS) being an implementation. How do we encode what version of Express.js is required?

(Picking a different example: And what if I'm not installing it _directly_, but it's being brought in as a dependency by something else, eg. a React interpreter used by something like Thermite, for example, that makes use of this interpreter as a dependency.)

**Comment by garyb** [comment] 2016-11-30 13:53
Ah, I see - you're talking about non-PureScript dependencies, I didn't realise that's what you meant. Including that kind of info is indeed a goal of `psc-package`, I think Phil had some ideas about it but I'm not sure if they were written up anywhere. Perhaps we need some kind of plugin architecture so you can have resolvers for various sources - `npm`, `bower`, `hex`, etc.

**Comment by hdgarrood** [comment] 2016-11-30 14:17
I can't immediately see any problems with those additions to `psc-package.json`, although we might want to think about how `psc-package` is going to know what version of e.g. node.js we are using.

I think adding a version range for supported PureScript compiler versions would be a great place to start exploring this. One nit: assuming we want to parse version ranges the same way npm and bower do, I think we should just have a string for the compiler version range, not an array of strings. E.g. `>=0.9.2 <0.10` is a valid version range according to `node-semver`:

> Comparators can be joined by whitespace to form a comparator set, which is satisfied by the intersection of all of the comparators it includes.

**Comment by paf31** [comment] 2016-11-30 17:24
I'd like to avoid getting into constraint solving in `psc-package` if possible. Specifying version ranges on things like OS and backends sounds like it will quickly require constraint solving. Constraint solving is a fine approach for some other tool in my opinion, but for the simple use case we have now, I'd prefer we avoid it.

I agree there could be some explosion in the number of package sets, but I think that is preferable in the short term. It was always intended that people would create their own forks of the package set for custom use cases or internal company use.

There are all sorts of things we can track in `psc-package.json`, but we can also put many of those things into the package set itself. If someone plans to use `extra-deps` to pull in something else by its `psc-package.json` file, I would expect them to have done the work of making sure that version is compatible - we don't do any sort of bounds checking there.

**Comment by damncabbage** [comment] 2016-11-30 22:41
> If someone plans to use extra-deps to pull in something else by its psc-package.json file, I would expect them to have done the work of making sure that version is compatible

Sure, but it's now a slog for them. That library has ten dependencies. The user now gets to figure out what's compatible by hand, without the benefit of those dependent libraries' authors encoding what versions of other libraries they intended for it to be used with, what version of a platform, what OS. ("It compiles" isn't enough of a version compatibility check.)

> It was always intended that people would create their own forks of the package set for custom use cases or internal company use.

Stackage build plans (of which I consider package-sets to be inspired by) were, as far as I can tell, a move to make it easy for users to install at the expense of extra work for maintainers.

Custom package sets gives some flexibility for cases not met by the central package-sets repo, yep, but puts the work back on the users, to figure out what version every package in package-sets is compatible with a given OS + Backend version, and leaves them without any automated way of doing this. It also doesn't cover the backend-specific deps that @garyb I were just been talking about in the comments above.

> … for the simple use case we have now, I'd prefer we avoid it.
> Generally, I'd suggest we start with the simple approach and solve these things if and when they become issues. Right now, the use of psc-package for the other backends is brand new.

I don't think we have a simple case, though; the current tool we have (Bower) is failing us _right now_ for the OS+Arch version, PSC version and JS dependencies issues at the very least, if the questions on IRC and problems in my own projects are anything to go by.

This issue is an attempt to figure out how we'd like to approach solving these problems, so I or others can chuck some effort into making the existing efforts better, rather than running off and making our own parallel packaging tool or something (with all the problems that brings).

**Comment by hdgarrood** [comment] 2016-12-01 10:43
Why do you want to avoid constraint solving in psc-package? Is it to do with architecture, or that you don't want to be too ambitious with what the scope of psc-package is, or something else?

**Comment by hdgarrood** [comment] 2016-12-01 10:47
Come to think of it, perhaps we should move discussion on extra-deps to #2443

**Comment by hdgarrood** [comment] 2017-12-20 12:43
Shall we close this? We've recently been trying to make the compiler issue tracker a little more focused, i.e. mainly just for stuff related to the compiler. It seems like there's definitely still discussion to be had and work to be done on these topics, but I think the psc-package or package-sets repositories might be a better place for it.

**Comment by nwolverson** [comment] 2017-12-20 13:05
Agree, I'd suggest issues for specific proposals for compiler/language changes as and when required.

**Closed** 2017-12-20 14:01 UTC
Labels: codegen
