### ISSUE TITLE
Catch eager self-reference at compile time

### ISSUE THREAD

**Issue by mikesol** [purescript/purescript#4022] opened 2021-03-10 08:55 UTC
## Description

JS code is produced that results in `RangeError: Maximum call stack size exceeded` when using the point-free style. Taking away the point free makes it work fine.

## To Reproduce

To see the behavior, you can first see the behavior that works as intended:

```purescript
module Recursive2 where

import Prelude
import Data.Maybe (Maybe(..), maybe)
import Data.Newtype (class Newtype)
import Data.Typeclass (Typeclass, type (@>), type (@@), TNil, (@>), tnil, using_)
import Effect (Effect)
import Effect.Class.Console (log)

newtype ShowMe a
  = ShowMe (a -> String)

derive instance newtypeShowMe :: Newtype (ShowMe a) _

type BaseShow
  = ShowMe @@ Maybe Int @> Int @> Boolean @> TNil

type MyShows
  = Typeclass BaseShow

myShow :: Unit -> MyShows
myShow _ =
  ShowMe
    ( maybe "Nothing"
        (\x -> append "One less than Maybe " $ using_ myShow $ (_ + 1) x)
    )
    @> (ShowMe $ (show :: Int -> String))
    @> (ShowMe $ (show :: Boolean -> String))
    @> tnil

recursive2 :: Effect Unit
recursive2 = do
  log $ using_ myShow true
  log $ using_ myShow (Just 42)
  log $ using_ myShow 1
```

This outputs an expected:

```bash
true
One less than Maybe 43
1
```

To provoke the error, change the definition of `myShow` to be point-free

```purescript
module Recursive2 where

import Prelude
import Data.Maybe (Maybe(..), maybe)
import Data.Newtype (class Newtype)
import Data.Typeclass (Typeclass, type (@>), type (@@), TNil, (@>), tnil, using_)
import Effect (Effect)
import Effect.Class.Console (log)

newtype ShowMe a
  = ShowMe (a -> String)

derive instance newtypeShowMe :: Newtype (ShowMe a) _

type BaseShow
  = ShowMe @@ Maybe Int @> Int @> Boolean @> TNil

type MyShows
  = Typeclass BaseShow

myShow :: Unit -> MyShows
myShow _ =
  ShowMe
    ( maybe "Nothing"
        (append "One less than Maybe " <<< using_ myShow <<< (_ + 1))
    )
    @> (ShowMe $ (show :: Int -> String))
    @> (ShowMe $ (show :: Boolean -> String))
    @> tnil

recursive2 :: Effect Unit
recursive2 = do
  log $ using_ myShow true
  log $ using_ myShow (Just 42)
  log $ using_ myShow 1
```

This results in:

```bash
/home/meeshkan-abel/mike/purescript-extensible-typeclass/output/Data.Typeclass/index.js:85
    return new PosCons(function (v) {
           ^

RangeError: Maximum call stack size exceeded
    at Object.posConsCacheMiss (/home/meeshkan-abel/mike/purescript-extensible-typeclass/output/Data.Typeclass/index.js:85:12)
    at /home/meeshkan-abel/mike/purescript-extensible-typeclass/output/Recursive2/index.js:18:96
    at myShow (/home/meeshkan-abel/mike/purescript-extensible-typeclass/output/Recursive2/index.js:24:7)
    at /home/meeshkan-abel/mike/purescript-extensible-typeclass/output/Data.Typeclass/index.js:61:103
    at /home/meeshkan-abel/mike/purescript-extensible-typeclass/output/Recursive2/index.js:18:212
    at myShow (/home/meeshkan-abel/mike/purescript-extensible-typeclass/output/Recursive2/index.js:24:7)
    at /home/meeshkan-abel/mike/purescript-extensible-typeclass/output/Data.Typeclass/index.js:61:103
    at /home/meeshkan-abel/mike/purescript-extensible-typeclass/output/Recursive2/index.js:18:212
    at myShow (/home/meeshkan-abel/mike/purescript-extensible-typeclass/output/Recursive2/index.js:24:7)
    at /home/meeshkan-abel/mike/purescript-extensible-typeclass/output/Data.Typeclass/index.js:61:103
[error] Tests failed: exit code: 1
```

Note that, to reproduce, you will need https://github.com/mikesol/purescript-extensible-typeclass in `packages.dhall` assuming you're using `spago`.

## Expected behavior

I'd expect one of two outcomes:
- The compilation to fail because of the point free style.
- The compilation to succeed and the run to succeed.

## PureScript version

0.14.0

**Comment by afcondon** [comment] 2021-03-10 12:05
...i think this is the same problem that also makes parser tutorials from Haskell harder to learn from?...if i'm right it about that i think warnings would be very helpful

**Comment by MonoidMusician** [comment] 2021-03-10 12:34
I think this is expected behavior, because by hiding the recursive reference under a lambda (with the `Unit` argument), you’re basically asking the compiler to not check it. (Plus it would have to inspect the evaluation behavior of `using_` which is too much to ask for.)

If you want to fix it in the library, you should probably make `using_` lazier, either by requiring the argument have a `Lazy` instance and using `defer`, or requiring that it be a newtype over a function type:
```purescript

using_ :: forall a x f f' head tail row. Newtype (f x) (a -> f' => UnCons x f head tail (TypeclassC' f row) => (Unit -> Typeclass (TypeclassC' f row) )-> a -> f'
using_ row a = unwrap (fst (uncons (Proxy :: Proxy x) (row unit))) a
```

I think that will help, but it’s untested.

**Comment by rhendric** [comment] 2021-03-10 18:52
@hdgarrood, I think you're possibly missing that the body of `myShow` is already delayed? @MonoidMusician has it right; the problem is that `using_` immediately invokes its argument, and when `myShow` is invoked, it immediately applies `using_` to `myShow`. But a lazier `using_` wouldn't have this problem, so the issue isn't exclusively with how `using_` is used in `myShow` or how `using_` is defined, but rather with the combination of the two, based on implementation information that doesn't appear in `using_`'s type. Warning about that sounds like a pretty tall order based on how we currently do per-module compilation, even ignoring the question of how much termination checking do we really want to take on.

**Comment by mikesol** [comment] 2021-03-10 19:42
All of this sounds reasonable.
I will try @hdgarrood to make a more self-contained example. I gave it a go before submitting the issue, but it was really hard for me to provoke the bug via other code paths. I now see how the combination of `using_` and `myShow` blows stuff up and I can fix it accordingly in the lib. Thanks for your help & feedback!

**Comment by hdgarrood** [comment] 2021-03-10 21:44
Yes, thanks, I was missing that. No need to make a smaller example - I see what’s going on now. I agree that this is beyond what we can reasonably detect inside the compiler, so shall we close this?

**Closed** 2021-03-11 11:03 UTC
Labels: enhancement
