### ISSUE TITLE
New notation for Class and Instances entailment

### ISSUE THREAD

**Issue by rvion** [purescript/purescript#2688] opened 2017-02-22 10:41 UTC
When I look at things like https://www.wikiwand.com/en/List_of_logic_symbols, I really feel there could be some better notations for entailment

in logic, there is [Double_turnstile (⊨) for `entails`](https://www.wikiwand.com/en/Double_turnstile)
and it's [reverse form (⫤) ](http://www.fileformat.info/info/unicode/char/2ae4/index.htm)

💚  I wish class could be

```purescript 
instance foo :: C x y ⊨ A x, B y 
instance foo :: C x y |= A x, B y

class C x y ⊨ A x, B y 
class C x y |= A x, B y

# instead of 
# class A x <= B y <= C x y
# class (A x, B y) <= C x y
```

I think entailment after the class name is better, because this way, information are always at the same positions, regardless of the number of entailment. I know where to look, and I can read things from general class name to more specific entailment needed.

## If we want an operator to compose class “constraints"

to get the best of both world (notation and composability) we could have a type operator

```purescript
/\ :: Constraint -> Constraint -> Constraint
∧ :: Constraint -> Constraint -> Constraint
```

so we could write 

```
class C x y ⊨ A x ∧ B y
class C x y |= A x /\ B y
```

------------

extracted from https://github.com/purescript/purescript/issues/2686#issuecomment-281614252

**Comment by paf31** [comment] 2017-02-22 18:20
With #2686, I think these could be implemented in a library.

**Comment by paf31** [comment] 2017-02-23 17:12
So how does this differ from #2686?

**Comment by rvion** [comment] 2017-02-24 06:15
I originally thought this one would differ from #2686 as:

 - #2686 is more about making `=>` a type operator for `type signatures`
 - this one (#2688) is more about `Class Foo a |= Bar a`, `instance Foo x |= ...` notations, and I thought it may not be directly implementable from an operator because of the special syntax and support in the copiler about class entailment

I thought that making a new issue would be a good idea not to pollute too much the original issue in case of further discussion, but since there is not much discussion, and since I already shared the idea in the other thread, it may be better to close it.

-----------

Really, I have no very strong opinion about `|=` or all this, I just wanted to give those few ideas I had while reading your proposal:

  1. `=>` type operator might enable `entailment notation` `both at the start or at the end of `signatures
  2. some alternative operators borrowed from logic notation (`|=`, `=|`)could be used.
  3. instead of encouraging a chained application of the constraint application opeartor `constraint -> type -> type`, using two operators (one to add constraints, one to apply them to a type) might make more sense and might read better
  4. moving class entailment at the end has some nice properties 
      - easier to mentally parse as class name is always at the 6th characters
      - easier to read out loud: eg. `class Foo a entails Bar a and Baz a Int` or `class Foo a forall Bar a and Baz a Int`

I just came out way longer since it was not that clear in my head when I typed it, and since I tried to give some more energy to the proposal.

**Comment by paf31** [comment] 2017-02-25 19:12
Well I don't really want to have multiple syntaxes for `class` and `instance`. Users would be able to use custom syntax in type signatures if they wanted to for some reason, but the instance and class syntax would be fixed.

**Comment by rvion** [comment] 2017-02-25 21:39
I also think only one syntax is better. 
I'm not even sure that it is a good idea to allow several alternative type signature syntaxes in the same time.

**Comment by paf31** [comment] 2017-02-25 22:33
Well if it's a type operator then the user will be able to define their own operators too. That's what I mean by allowing different operators in signatures.

**Comment by rvion** [comment] 2017-02-26 07:37
Yes, I understood that, I just don't know it it's a desirable byproduct to allow different entailment symbols in type signatures.
To some extent, I was also thinking that it could have been defined in prim, without proper user-land machinery to alias it or re-define it.
My initial point was more about `forall a b. Foo a => Bar b => a -> b` not being really nice IMO. I just then gave some ideas to brainstorm around alternative notations. I think I quite like the |= symbol, though, even if I understand it's not - that - important. I also know it's late to change this part of the language, but since you were already discussing the change from `(a,b)=>` to `a=>b=>` I thought the discussion could make sense

**Comment by paf31** [comment] 2017-02-26 20:38
> I just don't know it it's a desirable byproduct to allow different entailment symbols in type signatures.

Well, you could say the same thing about the function arrow. Users can override that with their own type operator now if they wanted to.

**Comment by paf31** [comment] 2017-03-19 23:08
I'm going to close this as a possible duplicate of #2686. If there is a difference that I'm not understanding, then we can reopen it.

**Closed by paf31** 2017-03-19 23:08 UTC
