### ISSUE TITLE
Change of --require-path not causing a rebuild

### ISSUE THREAD

**Issue by damncabbage** [purescript/purescript#1836] opened 2016-01-20 11:33 UTC
Confirmed with 0.7.6 through to current master (0c87efeff2afa3210726791d68a53078bed52bbe).

Reproducing this:
```
$ psc --version
0.8.0.0

$ cat src/Foo.purs
module Foo where
foo :: Int
foo = 1

$ cat src/Bar.purs
module Bar where
import Foo (foo)
bar :: Int
bar = foo

$ psc src/*.purs -o output --require-path=".."
$ cat output/Bar/index.js
// Generated by psc version 0.8.0.0
"use strict";
var Foo = require("../Foo");
...

$ psc src/*.purs -o output
$ cat output/Bar/index.js
// Generated by psc version 0.8.0.0
"use strict";
var Foo = require("../Foo");
...

$ rm -rf output
$ psc src/*.purs -o output
$ cat output/Bar/index.js
// Generated by psc version 0.8.0.0
"use strict";
var Foo = require("Foo");
...
```

**Comment by hdgarrood** [comment] 2016-01-20 11:36
@damncabbage Thanks for writing this up :)

For an example of how this can cause problems, see https://github.com/bodil/pulp/issues/151

**Comment by jasonzoladz** [comment] 2016-02-01 13:12
Will there be a 0.8.* bugfix release for this?

**Comment by garyb** [comment] 2016-02-01 13:22
Yep, the 0.9.0 milestone assigned here is slightly misleading, as really it means "some time between 0.8.0 and 0.9.0". This one will probably go in 0.8.2 unless someone gets to it before me or Phil.

**Comment by jasonzoladz** [comment] 2016-02-01 13:43
Thanks.  If you could come up with a PureScript package manager too that would be great.  🙃(The current situation is bananas.)

**Comment by hdgarrood** [comment] 2016-02-22 22:49
I appreciate that this might not be feasible, but I'd prefer we at least try get rid of the `--require-path` option entirely first, and find other solutions to the problems that led us to introduce it in the first place. It makes the build situation really silly, since some tools expect (or require) us to use one approach, and others expect or require the other, which makes them incompatible. Another red flag, imo, is that the only sensible value for it (other than the default) seems to be `../`.

**Comment by paf31** [comment] 2016-02-22 22:50
Yes, I'm starting to see that `../` is a better default.

**Comment by paf31** [comment] 2016-03-02 03:50
Are we in agreement that we should remove `--require-path` and default it to `../` then?

**Comment by hdgarrood** [comment] 2016-03-02 09:26
:+1: from me. I wouldn't really mind if the default remained as an empty string either (this is what I use 99% of the time, with pulp). Although, I think the webpack integration would be impossible without `../`, so I guess `../` is the better choice.

**Comment by garyb** [comment] 2016-03-07 00:27
:+1: for fixing it as `../`

**Comment by paf31** [comment] 2016-03-10 18:20
Closing as duplicate of #1836

**Closed by paf31** 2016-03-10 18:20 UTC
Labels: bug, codegen

**Comment by damncabbage** [comment] 2016-03-10 23:54
"Duplicate" as in "describing a problem with something that will be removed", or...?

(I want to make sure it's being closed for the right reason. This ticket isn't a duplicate of #1698.)

**Comment by hdgarrood** [comment] 2016-03-11 17:24
@damncabbage I think your question is answered by https://github.com/purescript/purescript/issues/1698#issuecomment-194986494

**Comment by paf31** [comment] 2016-03-11 17:28
Yes, sorry, that.
