### ISSUE TITLE
Type class constraints must be repeated for instances

### ISSUE THREAD

**Issue by huntwj** [purescript/purescript#3859] opened 2020-04-26 20:48 UTC
## Description

(Working from PureScript by Example)

```purescript
-- Action laws:
-- * act mempty a = a
-- * act (m1 <> m2) a = act m1 (act m2 a)
class Monoid m <= Action m a where
  act :: m -> a -> a

newtype Self m = Self m

-- Why is Monoid m required and not inferred as super class of Action?
instance selfAction :: Monoid m => Action m (Self m) where
  act m1 (Self m2) = Self (m1 <> m2)
```

When implementing the `instance selfAction`, it seems the `Monoid m` constraint is redundant since it is present in the Action class declaration.

## To Reproduce

```purescript
-- Removing the Monoid constraint causes an error...
instance selfAction :: Action m (Self m) where
  act m1 (Self m2) = Self (m1 <> m2)
```

and results in the error message:

```
  No type class instance was found for

    Data.Semigroup.Semigroup m1


while applying a function append
  of type Semigroup t0 => t0 -> t0 -> t0
  to argument m1
while inferring the type of append m1
in value declaration selfAction

where m1 is a rigid type variable
        bound at (line 0, column 0 - line 0, column 0)
      t0 is an unknown type

```

## Expected behavior

It would work the same as with the (redundant?) Monoid constraint

## Additional context

This is from PureScript by example section 6.11 problem 4.

## PureScript version

0.13.6

**Comment by garyb** [comment] 2020-04-26 20:56
This isn't a bug:

- the class declaration says: "For every instance of `Action m a` there needs to be a `Monoid m` "
- the instance declaration says: "Assuming there is a `Monoid m`, there is an instance `m (Self m)`"

Basically, the constraint of a class doesn't mean what you're thinking of there - putting a constraint on the class states that it is a requirement for all instances, not that it's something instances should automatically assume is true of their types.

This is part of the reason we chose different symbols for class implications (`<=`) vs instance constraints (`=>`).

**Comment by hdgarrood** [comment] 2020-04-26 21:02
Thanks for the report, but this is working as intended. When you write
```purescript
class Monoid m <= Action m
```
you're saying that in order to define an `Action m` instance, you have to provide a `Monoid m` instance. You can think of it as
```purescript
type MonoidDict m = { append :: m -> m -> m, mempty :: m }
type ActionDict m a = { monoid :: MonoidDict m, act :: m -> a -> a }
```
so to construct an `ActionDict`, you have to provide a `MonoidDict`. When you write an instance, you're essentially defining an `ActionDict` value:
```purescript
selfAction :: ActionDict m (Self m)
selfAction = { act: \m1 (Self m2) -> m1 <> m2, monoid: ?whatGoesHere }
```
But this doesn't work, because we can't just magic up a `MonoidDict` out of nothing. But if we take a `MonoidDict m` argument, we're okay:
```purescript
selfAction :: MonoidDict m -> ActionDict m (Self m)
selfAction monoid = { act: \m1 (Self m2) -> m1 <> m2, monoid }
```

Another way of viewing the difference between `instance selfAction :: Monoid m => Action m (Self m)` versus just `instance selfAction :: Action m (Self m)` is that they say different things about where you're expecting the `Monoid m` instance to come from. When you write an instance without constraints, like `instance selfAction :: Action m (Self m)`, you're saying that the compiler should be able to find the relevant superclass instances itself given what it already knows from looking at the instance head. (In this case, that's not possible, because we don't know anything about `m`.) When you write `instance selfAction :: Monoid m => Action m (Self m)`, you're saying that you don't yet have enough information to locate the Monoid instance, so you're deferring that task for later, i.e. it is now the responsibility of anyone who wants to use this Action instance to provide the Monoid superclass instance.

**Comment by huntwj** [comment] 2020-04-26 21:18
Thank you all for your quick response. I'll trust you know what you're talking about as I'm going to have to take some time to grok your responses to understand them.

Be well.

**Comment by hdgarrood** [comment] 2020-04-26 21:23
Thanks, you too! I'm going to close this as this isn't something we are considering changing at the moment, but please feel free to ask on https://discourse.purescript.org if you have further questions.

**Closed by hdgarrood** 2020-04-26 21:23 UTC
Labels: bug
