### ISSUE TITLE
Inconsistent handling of doc-comments for instances

### ISSUE THREAD

**Issue by bernhard-herzog** [purescript/purescript#3563] opened 2019-03-16 17:39 UTC
Purescript 0.12.3 handles doc-comments inconsistently. In particular, doc-comments for derived instances do not show up in the HTML documentation, whereas those for explicit instances do.

For example, the HTML docs generated for the following module constains the doc-comment for the Show instance, but not the one for the Eq instance:
```purescript
module InstanceDocs where

import Prelude

data T = T

-- | Doc-comment for derived instance
derive instance eqT :: Eq T

-- | Doc-comment for explicit instance
instance eqShow :: Show T where
  show T = "T"
```

Some package authors apparently expect doc-comments to work for derived instances, as e.g. the [Data.Tuple module](https://github.com/purescript/purescript-tuples/blob/master/src/Data/Tuple.purs) shows, which has doc-comments for `Eq` and `Functor` (among others) which do not show up in the documentation on pursuit.

Interestingly, if I change the way the derived instance declaration is written, the doc-comment *does* show up:
```purescript
derive
-- | Doc-comment for derived instance
      instance eqT :: Eq T
```

I only figured out that last part because AFAICT from the sources, the parser simply doesn't include the doc-comment in the AST when parsing derived instances. In `src/Language/PureScript/Parser/Declarations.hs`, `parseInstanceDeclaration` uses `withSourceAnnF` whereas `parseDerivingInstanceDeclaration` doesn't. The latter uses the former, though, to parse the part after the `deriving` keyword, so the doc-comment is included when it's between the `deriving` and the `instance`.

**Comment by hdgarrood** [comment] 2019-03-17 11:05
Thanks for the report! I suspect this is something we will want to address after the new parser (#3555).

**Comment by rhendric** [comment] 2020-12-27 06:49
Closing because I can't reproduce this on 0.14.0-rc4.

**Closed by rhendric** 2020-12-27 06:49 UTC
Labels: bug, purs docs
