### ISSUE TITLE
Types generated by wildcards and typed holes should work when substituted

### ISSUE THREAD

**Issue by fisx** [purescript/purescript#1793] opened 2016-01-04 15:32 UTC
note sure how to name or describe this problem, but there is a concise way to reproduce it:

http://stackoverflow.com/questions/34593686/purescript-type-signature-fails-to-compile-code-works-fine-without-suggested-s

don't think these are related, but they are the closest (open) matches i found: #1110, #1579.

**Comment by fisx** [comment] 2016-02-06 16:33
I actually think that this breaks type checking for programs that can't easily be rewritten.  I think sometimes I need to add a type signature to set constraints, but I can't due to this bug.

I will try to be more specific soon, but has anybody made progress on this in the last four weeks?

Thanks!

**Comment by LiamGoodacre** [comment] 2016-02-06 17:58
Had a quick look at your example, if I change:
~~~purescript
driver' = driver
~~~

to

~~~purescript
driver' = \x -> driver x
~~~

The compile error goes away.

**Comment by LiamGoodacre** [comment] 2016-02-06 18:21
I tried to simplify the code down to:

~~~purescript
data F a

idF :: Natural F F
idF = \a -> a

main :: forall m. (Monad m) => m Unit
main = do
  o <- pure idF
  let idF' :: forall a. F a -> F a
      idF' = o
  pure unit
~~~

Getting the following error:

~~~purescript
Error found:
in module Main
at  line 12, column 1 - line 13, column 1

  A type variable has escaped its scope.
  Relevant expression:

    o


in the expression (bind (($dictMonad1."__superclass_Prelude.Bind_1") undefined)) ((pure ((...) undefined)) idF)
in value declaration main
~~~

Either I refactored incorrectly, or your bug is a specific case of [Error Code EscapedSkolem](https://github.com/purescript/purescript/wiki/Error-Code-EscapedSkolem) which the compiler hasn't picked up.

Also in my simplified case, if I change the `o` to `\x -> o x` I still get the same error.

**Comment by paf31** [comment] 2016-08-21 01:55
I'm fairly certain this is a duplicate of #2236 actually.

**Comment by paf31** [comment] 2016-10-02 17:27
I think there is a nice fix here - we just replace any unknowns in the types with new wildcards, and use the original names for skolems.

**Closed** 2016-10-11 15:24 UTC
Labels: bug, easy, typechecker

**Comment by garyb** [comment] 2016-10-22 11:45
I don't think this is really fixed, it's still easy to get wildcard values that cannot be substituted without modification:

``` purescript
class A a b | a -> b where
  get :: a -> b

g1 :: forall a b. A a b => a -> _ -- inferred b0, not b
g1 = get
```

Maybe that's considered a different issue though?

**Comment by paf31** [comment] 2016-10-22 18:55
The fix only affected the suggestion used by `psc-ide` and the JSON error reporting. It seemed too confusing to me to have something like

```
Wildcard type definition has the inferred type
      
    b
      
in value declaration g1

where b0 is a rigid type variable
        bound at line 7, column 1 - line 7, column 6
```

and I didn't like the alternative of having overlapping rigid type variables with the same name in the final section of the error message either.
