### ISSUE TITLE
`psc-ide` should refer to unimported names with the module

### ISSUE THREAD

**Issue by parsonsmatt** [purescript/purescript#1979] opened 2016-03-28 16:08 UTC
It would be nice if `psc-ide` would report the fully qualified name of symbols that aren't currently in scope.

Example code:

```purescript
module Example where

import Batteries (Unit)
import Control.Monad.Eff (Eff)
import Flare (number, runFlareShow)

ex :: Eff _ Unit
ex = runFlareShow "input" "output" (number "example" 0.0)
```

The wildcard type definition has the following warning text:

```
src/Study/Flare.purs|12 col 1 warning| Wildcard type definition has the inferred type (dom :: DOM, channel :: CHANNEL | _0) in value declaration ui where _0 is an unknown type 
```

I'd like it to say:

```
src/Study/Flare.purs|12 col 1 warning| Wildcard type definition has the inferred type (dom :: DOM.DOM, channel :: Signal.Channel.CHANNEL | _0) in value declaration ui where _0 is an unknown type 
```

Would this be a welcome change? I can attempt to submit a PR if it's wanted.

**Comment by paf31** [comment] 2016-03-28 16:56
This isn't really a psc-ide change, we should fix the error in the regular compiler.

**Comment by paf31** [comment] 2016-03-28 16:57
Actually, this is a duplicate of #1647.

**Comment by garyb** [comment] 2016-03-28 16:58
^ beat me to it, was trying to find the issue number :)

**Closed by paf31** 2016-03-28 16:57 UTC
Labels: error-message, typechecker
