### ISSUE TITLE
Compile to WebAssembly

### ISSUE THREAD

**Issue by puffnfresh** [purescript/purescript#1177] opened 2015-06-17 19:15 UTC
https://brendaneich.com/2015/06/from-asm-js-to-webassembly/

Are there any benefits to doing so?

I guess we'd need this first:

https://github.com/WebAssembly/design/blob/master/FutureFeatures.md#gcdom-integration

**Comment by freebroccolo** [comment] 2015-06-17 20:30
I'm not familiar with WebAssembly yet but if it's similar enough to `asm.js` then I suspect purescript won't benefit from it much without significant changes to compilation model and FFI. From my experiments trying to use `asm.js`with purescript, there is often worse performance apparently due to way the VMs handle the transition between the asm.js and non-asm.js code.

**Comment by freebroccolo** [comment] 2015-06-17 20:33
Another possibility here though would be to compile to `asm.js` via emscripten from the output of the C++ backend. I think that approach definitely could yield some significant performance improvements for certain types of code.

**Comment by robotlolita** [comment] 2015-06-17 20:40
I don't think there's much of a benefit until WebAssembly adds at least PTC and better tooling(?). WebAssembly is targeting C/C++ today, and they're still iterating over the design. Should be interesting to consider it in the future though, as they're planning to diverge from JS's semantics in order to be a better compilation target for languages that aren't close to JS semantically (though PureScript kinda is).

**Comment by pierrebeaucamp** [comment] 2015-12-15 20:35
I don't think Web Assembly will be ready to use anytime soon. At least not until they implement some sort of garbage collection, which will only be worked on after the MVP is done (see [design/GC.md](https://github.com/WebAssembly/design/blob/master/GC.md)).

However, I think integrating asm.js is an interesting option. @freebroccolo, I haven't run any tests myself, but don't know why a VM would need to switch from asm.js to non-asm.js code. 

I'm thinking of implementing only some of the asm.js features, like the bit operations on integers for example. So purescript doesn't need to be 100% asm.js compliant, but would benefit from the increased performance nevertheless.

**Comment by freebroccolo** [comment] 2015-12-15 22:41
@pierrebeaucamp it's been awhile since I messed with it so I don't fully recall the details but I believe it has to do with the way the `asm.js` heap gets handled, i.e., when you enter a section of code that makes use of `asm.js` there is some setup and cleanup that needs to happen to play nicely with the rest of javascript. If this happens in a loop or every time you call an inexpensive function, it kills your performance and you end up worse off than if you had just not bothered in the first place.

So in order to get some actual benefit, you need to structure your code so that you have tasks that run long enough to outweigh the initial penalty or you need to have a compilation strategy that runs everything in `asm.js` to begin with.

Bit twiddling was one of the things I was actually interested in doing in `asm.js` with purescript (for a "native" bignum lib) but performance was bad (or at least not better) for the above reasons. I was able to get some benefit by writing larger chunks of code in the FFI but at that point there wasn't really a reason to use purescript anymore. Even writing pure javascript with hand-rolled `asm.js` was no match for emscripten compiled javascript though (and Odinmonkey showed the biggest performance increase at that point IIRC).

It's possible the situation has improved depending on what has happened with browsers in the meantime so it might be worth another shot but I wouldn't expect much.

**Comment by pierrebeaucamp** [comment] 2015-12-16 01:00
Hm, wouldn't this be related to the [asm validation](http://asmjs.org/spec/latest/#validation)? I.e. if you don't validate / flag the code as asm, the VM would just interpret it as normal code...

**Comment by freebroccolo** [comment] 2015-12-16 02:58
@pierrebeaucamp well, sort of. You can write `asm` conformant code and it shouldn't cause any real problems anywhere. It may even be slightly faster. However, if you do actually get the VM to recognize and execute it as `asm`, there is some overhead in switching into `asm` mode. There was a blog post describing this by one of the mozilla people awhile back but I don't remember where anymore. In any case, the post described why `asm.js` wasn't always faster or was only barely faster in some cases and it basically had to do with this. Things may have changed since then though so maybe someone should do some tests.

I suspect it's still the case that calling individual inexpensive functions written in `asm` style from purescript via the FFI will probably not make much difference if the VM even executes it in `asm` mode. You'd need to write a longer running piece of code in a loop or something to really see anything. This is fine if you're writing a renderer or doing some sort of numerical stuff but not very useful if you just want to write a library, which is why I doubt purescript can see much benefit from `asm.js` in its current form.

Now, an if entire purescript program with all the dependencies were compiled to specialized `asm` style code then I think there would very likely be some non-trivial performance gains for certain kinds of code. But I think probably the best way to do that would still be via emscripten, so that means we'd either need an LLVM backend or we would need to compile to the C++ backend first.

But anyway this is just speculation based on what I observed before.

**Comment by andyarvanitis** [comment] 2015-12-16 05:05
@freebroccolo Let me know if you'd like to try out something with one of the C++ backends. Pure14 is faster, but doesn't support rank-N types and is less tested (and behind). Pure11 should support everything, but its use of a custom variant type has a performance cost (no benchmarks yet).

**Comment by pierrebeaucamp** [comment] 2015-12-19 01:59
@freebroccolo So I've done some reading and it turns out that `use asm` triggers ahead of time compilation of the code. If you omit that line, it runs in the regular JIT VM.

So probably there will be only a small performance benefit (and, therefore, it's not really worth optimizing for).

**Comment by paf31** [comment] 2016-09-25 00:00
Closing, since this should ideally be implemented using the output of `--dump-corefn` now. In any case, I don't think this would be implemented in the main compiler.

**Closed by paf31** 2016-09-25 00:00 UTC

**Comment by rosenk** [comment] 2017-06-02 10:09
What is the status of this? Are we tracking this issue somewhere else?

**Comment by garyb** [comment] 2017-06-02 10:38
Nobody is working on it that I'm aware of - it's not being tracked in this repo as it's not going to be implemented in the main compiler in the foreseeable future. Maybe one day :smile:

**Comment by metasansana** [comment] 2017-12-26 16:33
Says [here](http://webassembly.org/docs/high-level-goals) WASM aims to target mobile, IoT and 'non-browser embeddings'. I think purescript could benefit a lot from that in terms of portability.

All major browsers now support the format so unless the API design or implementations are horrible, at some point people are going to be shipping WASM code instead of JS. There might be an opportunity to greatly influence the future of Web app development here.

**Comment by kRITZCREEK** [comment] 2017-12-26 16:44
WASM will not be a viable compilation target until it gets a story for garbage collection.

**Comment by Pauan** [comment] 2017-12-26 17:54
@kRITZCREEK Although I agree with you, I want to point out that it is possible to *compile a garbage collector to WebAssembly* and then use it. That's what many garbage collected languages do right now. The problem is with JavaScript interop, not with the garbage collector per se.

**Comment by thewoolleyman** [comment] 2019-04-06 02:30
Relevant thread: https://github.com/WebAssembly/gc/issues/36

**Comment by Pauan** [comment] 2019-05-10 11:56
@flip111 One issue is that the PureScript GC would need to carefully interact with the JavaScript GC in order to avoid memory leaks (e.g. circular references between PureScript and JS).

The PureScript compiler would also have to do some heroics to transform the CommonJS modules into something which can be imported and used by wasm. This is possible, but it's definitely very tricky!

To give an example of the sort of stuff PureScript would have to do: wasm does not support JS objects at all, it only supports integers. So in order to communicate between PureScript and JS, *everything* must be converted into an integer.

The way to do that is to create a heap in JS, and put JS objects into that heap. The index in the heap is the "pointer" to the object. Then JS sends that index to wasm, and wasm can use it (since it's just an integer).

Then whenever wasm wants to do something to the object, it has to send the index back to JS, JS then looks up the index in the heap, does the operation, and then sends the result back to wasm.

And when wasm is done using the object, it has to send a message to JS telling JS to remove the object from the heap (so that way it doesn't cause a memory leak). This is complicated by the fact that PureScript would need its own GC to keep track of these pointers.

All of this extra work means that interop between wasm and JS is multiple orders of magnitude slower than just using JS directly. Which means that wasm is best in situations where it doesn't need to communicate with JS, and can do everything purely in wasm.

Wasm will soon have `anyref`, which avoids the need for a JS heap, but that doesn't really help much, since you now need to deal with wasm tables instead (which are basically a heap).

I've worked on Rust + JS integration, so I have a good idea of how all this fits together. It's not *that* difficult, but it's ***very*** different from what PureScript currently does, so it would likely require major changes to the FFI system (or heroics on the part of the PureScript compiler).

And since PureScript has so much communication with JS, it's likely that a wasm version of PureScript would actually be slower (and would have dramatically larger file sizes) compared to the JS version of PureScript.

This is different from Idris, which was designed to be run natively (and so they have their own GC already), and their FFI with JS is very different from PureScript.

PureScript was designed around JS, so trying to move to wasm is very complicated, and likely won't give any benefits.
