### ISSUE TITLE
Namespace clash between Modules and Data Constructors

### ISSUE THREAD

**Issue by csabahruska** [purescript/purescript#1792] opened 2016-01-04 13:57 UTC
version: psc 0.7.6.1

This code should work but it crashes:

file: Linear.purs
```purescript
module Linear where
import Prelude

hello = "Hello"
```

file: Main.purs
```purescript
module Main where

import Prelude
import Control.Monad.Eff
import Control.Monad.Eff.Console
import Linear

data OK = Linear2
data BAD = Linear

main :: forall e. Eff (console :: CONSOLE | e) Unit
main = do
  log hello
```

problem:
```javascript
  var Linear = PS["Linear"];.....
  var Linear2 = (function () {
      function Linear2() {

      };
      Linear2.value = new Linear2();
      return Linear2;
  })();
  var Linear = (function () {
      function Linear() {

      };
      Linear.value = new Linear();
      return Linear;
  })();
  var main = Control_Monad_Eff_Console.log(Linear.hello);
```

[module_and_data_namespace_bug.zip](https://github.com/purescript/purescript/files/77242/module_and_data_namespace_bug.zip)

**Comment by garyb** [comment] 2016-01-04 14:24
This is a duplicate of #867 (fixed in 0.8), thanks though.

**Closed by garyb** 2016-01-04 14:24 UTC
Labels: duplicate
