### ISSUE TITLE
Compiler infers wrong type

### ISSUE THREAD

**Issue by akegalj** [purescript/purescript#2236] opened 2016-07-19 10:32 UTC
I have created sample repo that showcases this problem. Basically I can't figure out what is right type annotation for this function https://github.com/akegalj/pux-types/blob/master/src/Main.purs#L23 :
```purescript
data Action
    = Button
    | Nop

type State = Int

-- NOTE: here I tried to do some action with effect and I picked `throw`
-- update :: forall eff. Action -> State -> EffModel State Action (err' :: CHANNEL | eff)
update Button state = onlyEffects state [ liftEff $ throw "bla" *> pure Nop ]
update Nop state = noEffects state

view :: State -> Html Action
view count =
  div
    []
    [ button [ onClick (const Button) ] [ text "Button" ]
    ]

main :: forall e. Eff (err :: EXCEPTION, channel :: CHANNEL | e) Unit
main = do
  app <- start
    { initialState: 0
    , update: update
    , view: view
    , inputs: []
    }

renderToDOM "#app" app.html
```

when I compile without type annotation compiler infers this type:
```
      forall t10 t27.                               
        Action                                      
        -> t27                                      
           -> { state :: t27                        
              , effects :: Array                    
                             (Aff                   
                                ( channel :: CHANNEL
                                | t10               
                                )                   
                                Action              
                             )                      
              }         
```
and when I put this suggested type I am getting:
```
  No type class instance was found for
                                                            
    Control.Monad.Eff.Class.MonadEff ( err :: EXCEPTION     
                                     | t0                   
                                     )                      
                                     (Aff                   
                                        ( channel :: CHANNEL
                                        | eff1              
                                        )                   
                                     )    
```
So for the start it looks that it infers the wrong type. As it looks to me that this suggestion is valid because we use `throw` to make an effect (which is using `EXCEPTION` effects) - so if replaced with `CHANNEL` with `EXCEPTION` I am getting:
```
in module Main
at /home/akegalj/projects/pux-types/src/Main.purs line 24, column 1 - line 24, column 89

  No type class instance was found for
                                                            
    Control.Monad.Eff.Class.MonadEff ( err :: EXCEPTION     
                                     | t0                   
                                     )                      
                                     (Aff                   
                                        ( channel :: CHANNEL
                                        , err' :: EXCEPTION 
                                        | eff1              
                                        )                   
                                     )     
```
There is a whole discussion about this issue starting at http://ircbrowse.net/browse/purescript?id=367336&timestamp=1468883448#t1468883448 and with the conclusion that it is probably a bug. It looks like it is related to the problem described here as well https://github.com/afcondon/puxws/commit/e45e864ad21c51e16c8f3ee92f4ba6f80053abdf .

Maybe someone knows a workaround for this? In this example a workaround is just to drop type annotation for `update` and compiler infers it himself but I have one project where this trick doesn't work so I have to annotate it properly.

**Comment by paf31** [comment] 2016-07-24 23:58
Thanks, I'll have a look at this.

**Comment by garyb** [comment] 2016-07-25 00:26
I'm not sure this is necessarily something that is fixable - it's an impossible type: the row requires that `EXCEPTION` is not present to prevent an overlap, but `EXCEPTION` is required by the implementation, so either way you try it you get a type error.

This arises due to the signature of `launchAff`:

``` purescript
launchAff :: forall e a. Aff e a -> Eff (err :: EXCEPTION | e) (Canceler e)
```

I fixed submitted a patch to pux that allows the `EXCEPTION` by using `unsafeInterleaveEff`. Ironically enough `launchAff` also requires an unsafeInterleave to make that type possible.

I think until overlaps are allowed (which would require lacks constraints to be "safe" as far as I can see) or `launchAff` is altered this is going to be "broken".

**Comment by paf31** [comment] 2016-07-26 17:34
@garyb I think the bug is that it compiles when there is no annotation, since it infers the wrong type.

**Comment by puffnfresh** [comment] 2016-07-27 00:21
@paf31 yes, that's right.

**Comment by garyb** [comment] 2016-07-27 09:51
Ohh right, I missed that. Ouch.

**Comment by paf31** [comment] 2016-07-31 17:43
I just tried this, and my compiler infers the type

```purescript
forall t10 t27.
      Action
      -> t27
         -> { state :: t27
            , effects :: Array
                           (Aff
                              ( channel :: CHANNEL
                              , err :: EXCEPTION
                              | t10
                              )
                              Action
                           )
            }
```

and when I substitute that, it compiles.

Are we using different versions of the compiler, perhaps?

**Comment by garyb** [comment] 2016-07-31 17:47
No, I fixed pux with a coercion to allow exception effects.

**Comment by garyb** [comment] 2016-07-31 17:48
Try 5.0.2, that's the version without the fix I think.

**Comment by paf31** [comment] 2016-07-31 17:48
Ah, ok, I'll use the previous version then, thanks.

**Comment by paf31** [comment] 2016-07-31 17:50
Ok, so I think we should be getting a duplicate label error, right?

**Comment by garyb** [comment] 2016-07-31 17:52
I think so, although above it looks like the `EXCEPTION` effect is missing from the inferred type, as when the inferred type is used the instance can't be found due to it being missing from the row.

**Comment by paf31** [comment] 2016-07-31 17:59
Ok, in that case, it seems like the instance solver should be failing, since that unification should be happening there (if we did unification in the constraint solver, which we don't, yet 😄)

**Comment by garyb** [comment] 2016-07-31 18:03
I'm not sure that's actually what _is_ happening though, as I'm not sure I've ever seen an inferred time be missing an effect label before! Just, that's what it looks like from what was written in the issue opening.

**Comment by paf31** [comment] 2016-07-31 18:19
I think I know what's going on here, it's just a bit subtle. PR coming soon hopefully.

**Comment by paf31** [comment] 2016-07-31 18:21
@garyb I have a fix, although it breaks `aff` (rightly, I think). The offending function is `logShow` in the console wrapper module:

```
17  logShow = liftEff <<< C.logShow
    ^^^^^^^^^^^^^^^^^^^^^^^^

No type class instance was found for

  Control.Monad.Eff.Class.MonadEff ( console :: CONSOLE
                                   | t0
                                   )
                                   (Aff
                                      ( console :: CONSOLE
                                      | e1
                                      )
                                   )

The instance head contains unknown type variables. Consider adding a type annotation.

while checking that expression (compose liftEff) logShow
  has type forall e a.
             (Show a) => a
                         -> Aff
                              ( console :: CONSOLE
                              | e
                              )
                              Unit
while applying a function compose
  of type forall b c d a. (Semigroupoid a) => a c d -> a b c -> a b d
  to argument liftEff
in value declaration logShow

where e1 is a rigid type variable
        bound at line 17, column 1 - line 17, column 25
      t0 is an unknown type
```

Note, this actually is incorrect, and needs a type annotation, since there _is_ an unknown type involved.

**Comment by garyb** [comment] 2016-07-31 18:24
I'm not sure I understand? `logShow` has a type annotation, and how is it right that the fix breaks it?

**Comment by paf31** [comment] 2016-07-31 18:26
It's only right in the absence of fundeps. If we had

```purescript
class MonadEff eff m | m -> eff where ...
```

then the `eff (Aff eff)` instance would be picked, and that would imply the effect row in the thing being lifted.

As it is, the compiler just has something of type `Eff (console :: CONSOLE | t0)` where `t0` is unknown, and it's not necessarily right to unify that with the `e` from the type signature.

**Comment by garyb** [comment] 2016-07-31 18:28
In that case, won't that break every usage of any kind of `lift` function? Or at least `liftEff`/`liftAff`?

**Comment by paf31** [comment] 2016-07-31 18:30
Only things using rows, like `liftEff`. This is basically the same class of problem as we have with transformers, the issue is that I never applied the same restriction for rows for some reason.

I can verify this breaks Halogen. I think the best solution for now is to just provide a monomorphic `liftEff` from `Eff` to `Aff`.

**Comment by garyb** [comment] 2016-07-31 18:32
This would be pretty disasterous for SlamData, chances are we'd have to wait for fundeps before upgrading past 0.9.2 if this does go in :sob:

**Comment by paf31** [comment] 2016-07-31 18:35
Yes, it's definitely an unfortunate situation. I'll open a PR anyway, so you can see the solution, and we can discuss pros/cons some more there.

**Comment by paf31** [comment] 2016-07-31 18:45
Deferred until 0.10, when we'll aim to have fundeps as well.

**Comment by garyb** [comment] 2016-09-23 10:47
@paf31 I think we can close this now?

**Comment by paf31** [comment] 2016-09-23 16:32
Yes, thanks.

**Closed by paf31** 2016-09-23 16:32 UTC
Labels: bug, typechecker
