### ISSUE TITLE
Int type: incorrect modular arithmetics

### ISSUE THREAD

**Issue by Unisay** [purescript/purescript#3154] opened 2017-11-18 22:18 UTC
**Expected behavior**:
```
999999956 * 999999956 = 999999912000001936 `mod` 2147483648 = 707696528
```
(10000000000000000000000000000000 in binary  contains 33 bits and is 2147483648 in decimal)

Proof: https://www.wolframalpha.com/input/?i=999999956+*+999999956+mod+2147483648
Proof in C:
```
#include <stdio.h>
int main()
{
   int a=999999956; // int is 32 two's complement bits
   int b=999999956;
   printf("%d",a*b);
   return 0;
}

$ gcc -w test.c -o test -lm && test || echo
707696528
```
**Actual behavior in PS**:
```
$ pulp psci
> 999999956 * 999999956
707696512
```

**Comment by paf31** [comment] 2017-11-18 23:11
You can see this in JS as follows:

```
> (999999956 * 999999956) | 0
707696512
```

So this is a result of using JavaScript's `number` type to represent integers. I don't think there is anything we can do to avoid this, but maybe someone has an idea.

**Comment by hdgarrood** [comment] 2017-11-18 23:35
This is a duplicate of #2980; note that the fix suggested there, which is to use `Math.imul`, provides the expected behaviour:

```
Math.imul(999999956, 999999956)
> 707696528
```

**Closed by hdgarrood** 2017-11-18 23:35 UTC
Labels: bug
