### ISSUE TITLE
Should core tests be removed or updated?

### ISSUE THREAD

**Issue by kl0tl** [purescript/purescript#3852] opened 2020-04-23 17:48 UTC
The core-tests directory hasn’t been updated in a while (core-tests/psc-package.json refers to the psc-0.11.3 set and core-tests/test-everything.sh uses `psc-package update`, which is a subcommand that was removed in 2018) and those tests aren’t run by Travis CI.

**Comment by hdgarrood** [comment] 2020-04-23 18:26
Thanks for the report; this is a duplicate of #2837.

**Closed by hdgarrood** 2020-04-23 18:26 UTC
