### ISSUE TITLE
use correct type variable names in wildcard suggestions

### ISSUE THREAD

**Issue by matthewleon** [purescript/purescript#2646] opened 2017-02-09 16:10 UTC
myConst :: forall a b. _ -> b -> a
    myConst = const

The compiler warning gives:

    Wildcard type definition has the inferred type
    
        a0

Ideally we would want that type variable simply named `a` rather than `a0`. This is much clearer to the programmer.

**Comment by hdgarrood** [comment] 2017-02-09 16:35
I think this is basically a duplicate of #2638.

**Comment by matthewleon** [comment] 2017-02-09 17:17
@hdgarrood I saw that issue, but from a user's perspective there seemed to me to be a significant difference in the problem (not naming the inferred type properly vs. not properly recommending the user to introduce a new type variable). I imagine that the underlying issue might indeed be the same, though.

**Comment by hdgarrood** [comment] 2017-02-09 18:14
I've now split up #2638 into two separate issues, so #2638 is now just for  the names given to inferred type variables, and I created a new issue for having suggestions recommend introducing new type variables where applicable.

**Closed by hdgarrood** 2017-02-09 18:14 UTC

**Comment by hdgarrood** [comment] 2017-02-09 18:18
I've edited the description of #2638 so it's clearer what the issue actually is, but I do think this is a duplicate so I've closed it.

**Comment by paf31** [comment] 2017-02-09 19:57
> Ideally we would want that type variable simply named a rather than a0. This is much clearer to the programmer.

Clearer perhaps, but it throws away crucial information when a type is skolemized twice for some reason.
