### ISSUE TITLE
Conflicting data constructors

### ISSUE THREAD

**Issue by kika** [purescript/purescript#2158] opened 2016-05-24 05:36 UTC
```purescript 
data Button = Close | Ok | Cancel | Yes | No
data ButtonSet = Ok | OkCancel | YesNo | YesNoCancel
```
generates (after psc-bundle optimization) 
```javascript
  var Ok = (function () {
      function Ok() {

      };
      Ok.value = new Ok();
      return Ok;
  })();
  var Ok = (function () {
      function Ok() {

      };
      Ok.value = new Ok();
      return Ok;
  })();
  exports["Ok"] = Ok;
```
without a single error or warning from the compiler. 
IMHO, there's nothing inherently wrong with this code, both `Ok`s are defined within the scope of two different types. Maybe it makes sense to generate them as `Button_Ok` and `ButtonSet_Ok` in the resulting javascript? If not, it should be an error.

**Comment by kika** [comment] 2016-05-24 05:40
Also, on a somewhat related note: all constructors, except `Ok` were optimized away, and I think `Ok` wasn't just because of this conflict. I use these constructors in FFI (returning these types from FFI glue code), and I have no way of controlling greediness of the optimizer (which has access to the FFI js files).

**Comment by hdgarrood** [comment] 2016-05-24 08:33
I think this should just throw an error; if not, what should the type of `Ok` be? I think this is a dupe of #1945.

**Comment by garyb** [comment] 2016-05-24 10:35
Yeah, it's basically the same thing as that. There are checks in the code for duplicate data constructors so I guess they're just not working.

**Closed by garyb** 2016-05-24 10:35 UTC
Labels: duplicate
