### ISSUE TITLE
Improve error messages for types of same name

### ISSUE THREAD

**Issue by Risto-Stevcev** [purescript/purescript#2339] opened 2016-09-29 13:07 UTC
If there are two types of the same name that are imported. For ex:

```purescript
import Foo (Bar(Norf)) as Foo
import Baz (Bar(Norf)) as Baz

qux :: Foo.Bar -> String
qux _ = "blah"

norf = qux Baz.Norf
```

It will throw a type error saying something like it could not match type `Bar` with type `Bar`, but it would be more useful for it to say that it could not match type `Baz.Bar` with type `Foo.Bar`.

**Comment by garyb** [comment] 2016-09-29 13:15
Duplicate of #1647 :)

**Closed by garyb** 2016-09-29 13:15 UTC
