### ISSUE TITLE
Messages for unexpected record update syntax

### ISSUE THREAD

**Issue by texastoland** [purescript/purescript#2250] opened 2016-07-27 03:26 UTC
I factored out a record update and have been bitten by leftover `=`s a few times. Here are difficult to sort errors I encountered:

```hs
r = g {foo = "bar"}
{-
Could not match type
    Record
  with type
    Function
      { foo :: t2
      | t3
      }
-}
g {foo} = foo
```

```hs
r' = {foo = "bar"}
{-
  Unable to parse module:
  unexpected =
  expecting :, , or }
-}
```

```hs
f baz = g
  { foo = "bar"
  , baz -- punny
  }
{-
  Unable to parse module:
  unexpected {
  expecting no indentation or end of input
-}
```

Both former messages are fairly good. An extra step to point out record literal versus update syntax would've made it obvious. If possible it'd be nice to have a special case message for these like <q>Did you mean `({ field: value })` instead of `({ field = value })`?</q>

**Comment by texastoland** [comment] 2016-07-27 03:42
On a side note does update syntax not support punning too to prevent ambiguity with literals when all fields are punned? Would it be sensible to interpret it as un update if there's at least one `=`?

**Comment by paf31** [comment] 2016-07-27 15:20
What does the full error message say here? I suspect there is something useful towards the bottom like `while checking g has type { ... }`.

Often the problem isn't that the error isn't helpful, but that the helpful bit isn't the highlighted bit.

**Comment by texastoland** [comment] 2016-07-27 17:36
No. They're all pastable in http://try.purescript.org. Except for the last one (which I believe may deserve a separate issue for punning updates) the messages were quite precise. The problem was I was looking for types or missing punctuation respectively when the real error was misplaced syntax.

**Comment by paf31** [comment] 2016-07-30 18:57
I think the errors are quite clear though:

- The first is a type error, and it should tell you what it was checking at the time it failed.
- The second is a parse error, and even tells you which character was invalid.
- The third is a parse error too, and admittedly could be a little more helpful, but at least points at the opening curly brace.

Maybe the solution here is to try to use `<?>` in parsec to assign meaningful names to the characters, so you'd get something like 

```
Unable to parse module:
unexpected =
expecting field value, next field (pun), or end of record
```

**Comment by texastoland** [comment] 2016-07-30 19:46
Perhaps. The underlying issue is what the messages lack however. Currently error messages are like a doctor administering a diagnosis in precise medical terminology without prescribing any treatment. In the case of an unexpected record update (except for curiously unsupported punning updates) I always mean literal syntax. Other examples I encountered this week are flipping `->` with `<-` and missing `do` in combination with `<-`. From a [XY perspective](http://xyproblem.info) arguably each is an opportunity to simplify syntax to make it harder to get wrong. Regardless I think it's the heart of what Elm is doing well.

**Comment by paf31** [comment] 2016-09-24 23:26
Closing. Agreed that the parse errors aren't great, but they're as good as we're going to be able to get with Parsec without a lot of special cases. Also note that the context of the type error helps quite a bit here too.

**Closed by paf31** 2016-09-24 23:26 UTC
Labels: error-message, syntax
