### ISSUE TITLE
Use Text instead of String

### ISSUE THREAD

**Issue by paf31** [purescript/purescript#547] opened 2014-08-06 22:43 UTC
Some unicode characters are not being handled properly apparently.

**Comment by paf31** [comment] 2015-09-11 22:29
Moving to 0.8 since I think this can be classified as "performance".

**Comment by aspidites** [comment] 2015-10-20 19:13
I'll be taking a look at this soon (this week) unless someone else is interested in it.

**Comment by faineance** [comment] 2016-03-30 09:28
I'd like to have a try at this.

**Comment by paf31** [comment] 2016-03-30 16:12
That would be great!

**Comment by zjhmale** [comment] 2016-05-13 01:39
@paf31 i just tried all these unicode [here](https://github.com/purescript/purescript/blob/master/src/Language/PureScript/Parser/Lexer.hs#L191-200) and all works fine. so, is this issue be fixed already?

**Comment by hdgarrood** [comment] 2016-05-13 01:44
Not yet; even though I think most (hopefully all? 😉 ) of the unicode-related issues have been fixed, there's still the issue that the compiler extensively uses the `String` type internally, which is not a very good choice for representing textual data.

**Comment by zjhmale** [comment] 2016-05-13 02:17
@hdgarrood can you give some cases related to this issue? thx :)

**Comment by hdgarrood** [comment] 2016-05-13 02:24
Sorry, I don't understand the question. What do you mean by "case"?

**Comment by zjhmale** [comment] 2016-05-25 07:20
@hdgarrood sorry 😂 , i mean you said that 

>there's still the issue that the compiler extensively uses the String type internally, which is not a very good choice for representing textual data.

so can you give some code snippets that will cause the unicode issue? then maybe i can find the entry point to fix it. i just tried some but all works good. 😂

**Comment by kRITZCREEK** [comment] 2016-05-25 07:56
@zjhmale Haskell's `String` type handles unicode allright, the problem is that `[Char]` is a very inefficient representation for textual data. Haskell's `text` package provides the `Text` datatype and associated operations which use stream fusion to greatly improve performance.

**Comment by zjhmale** [comment] 2016-05-25 10:21
@kRITZCREEK got it, thx!

**Comment by kRITZCREEK** [comment] 2016-11-04 12:15
I'd like to tackle this one :) *BUT* I want two concessions:

1. OverloadedStrings
2. Protolude/our own custom Prelude which banishes String as much as possible

I know there was pushback around 1. because of inference problems and 2. is quite a big step no doubt, but the boilerplate will make this a drag otherwise.

This will also cause conflicts with pretty much every other PR, are we up for the extra work?^^

**Comment by garyb** [comment] 2016-11-04 12:21
I'm fine with `OverloadedStrings` as long as it's not enabled globally - but if we switch to `Text` maybe that will be necessary anyway? I'm not sure how widespread we'd have issues with literals that should be `Text` - I think most of them would be for generated names.

**Comment by kRITZCREEK** [comment] 2016-11-04 12:30
When I initially merged psc-ide into the compiler repo that PR had OverloadedStrings enabled globally and I need like two type annotations in the lexer. I don't see how that's a problem.

**Comment by kRITZCREEK** [comment] 2016-11-04 13:10
The new code in `CoreFn/ToJSON.hs` caused some issues so I turned OverloadedStrings off for that module, but other than that it's two annotations inside `Lexer.hs`

```patch
From f6b72cd986a5f7143145832065dff571b075f81a Mon Sep 17 00:00:00 2001
From: Christoph Hegemann <christoph.hegemann1337@gmail.com>
Date: Fri, 4 Nov 2016 14:08:39 +0100
Subject: [PATCH] enable OverloadedStrings

---
 purescript.cabal                         | 1 +
 src/Language/PureScript/CoreFn/ToJSON.hs | 2 ++
 src/Language/PureScript/Parser/Lexer.hs  | 4 ++--
 3 files changed, 5 insertions(+), 2 deletions(-)

diff --git a/purescript.cabal b/purescript.cabal
index a4bf123..163bda0 100644
--- a/purescript.cabal
+++ b/purescript.cabal
@@ -311,6 +311,7 @@ library
                      PatternSynonyms
                      RankNTypes
                      RecordWildCards
+                     OverloadedStrings
                      ScopedTypeVariables
                      TupleSections
                      ViewPatterns
diff --git a/src/Language/PureScript/CoreFn/ToJSON.hs b/src/Language/PureScript/CoreFn/ToJSON.hs
index 69ef3eb..4bbb8f7 100644
--- a/src/Language/PureScript/CoreFn/ToJSON.hs
+++ b/src/Language/PureScript/CoreFn/ToJSON.hs
@@ -1,3 +1,5 @@
+{-# LANGUAGE NoOverloadedStrings #-}
+
 -- |
 -- Dump the core functional representation in JSON format for consumption
 -- by third-party code generators
diff --git a/src/Language/PureScript/Parser/Lexer.hs b/src/Language/PureScript/Parser/Lexer.hs
index 286bb73..90ba3dd 100644
--- a/src/Language/PureScript/Parser/Lexer.hs
+++ b/src/Language/PureScript/Parser/Lexer.hs
@@ -562,7 +562,7 @@ reservedTypeNames = [ "forall", "where" ]
 -- The characters allowed for use in operators
 --
 isSymbolChar :: Char -> Bool
-isSymbolChar c = (c `elem` ":!#$%&*+./<=>?@\\^|-~") || (not (isAscii c) && isSymbol c)
+isSymbolChar c = (c `elem` (":!#$%&*+./<=>?@\\^|-~" :: String)) || (not (isAscii c) && isSymbol c)
 
 
 -- |
@@ -575,7 +575,7 @@ isUnquotedKeyHeadChar c = (c == '_') || isAlphaNum c
 -- The characters allowed in the tail of an unquoted record key
 --
 isUnquotedKeyTailChar :: Char -> Bool
-isUnquotedKeyTailChar c = (c `elem` "_'") || isAlphaNum c
+isUnquotedKeyTailChar c = (c `elem` ("_'" :: String)) || isAlphaNum c
 
 -- |
 -- Strings allowed to be left unquoted in a record key
-- 
2.10.2

```

**Comment by garyb** [comment] 2016-11-04 14:10
Well, that's not so bad :)

**Comment by hdgarrood** [comment] 2016-11-04 18:07
Has anyone tried doing something like defining a `t :: Text -> Text; t = id`, so that we can write `t "foo"` as a slightly lighter-weight way of writing `("foo" :: Text)`?

**Comment by phadej** [comment] 2016-11-04 18:36
@hdgarrood I do that in some of my code. It works, though you loose one single letter variable name (e.g. for some `Traversable`s) ;)

**Closed** 2016-11-28 17:41 UTC
Labels: bug, codegen, easy, hacktoberfest, syntax
