### ISSUE TITLE
Compiler hang, possibly during typeclass resolution

### ISSUE THREAD

**Issue by hdgarrood** [purescript/purescript#939] opened 2015-03-04 21:49 UTC
This code makes the compiler hang:
```purescript
module Coercible2 where

foreign import unsafeCoerce
  "function unsafeCoerce(x) { return x }" :: forall a b. a -> b
class Coercible a b
coerce :: forall a b. (Coercible a b) => a -> b
coerce = unsafeCoerce
instance transitiveCoercible :: (Coercible a b, Coercible b c) => Coercible a c
newtype Foo = Foo Number
instance coercibleFooNumber :: Coercible Foo Number

main = do
  show (coerce (Foo 4) :: Number)
```
I think this might be related to #438

**Comment by paf31** [comment] 2015-03-04 21:59
Well, your instances are undecidable, and we don't prune the search tree at a finite depth (maybe we should).

**Comment by hdgarrood** [comment] 2015-03-04 22:14
Yeah, I wasn't expecting this to compile

**Comment by paf31** [comment] 2015-03-07 02:36
I'll close this as a duplicate of #438. Maybe the solution is to prune the search tree. I don't fancy trying to statically determine termination.

**Closed by paf31** 2015-03-07 02:36 UTC

**Comment by hdgarrood** [comment] 2015-03-07 02:40
Can undecidabiliity of instances be statically determined? Might be nice to include a warning for undecidable instances if so, when warnings are implemented?

**Comment by paf31** [comment] 2015-03-07 02:44
Definitely.

So, Haskell 98 makes this simple: in the absence of `FlexibleContexts`, `FlexibleInstances` and other things, the right hand side of the `=>` in an instance head is always strictly structurally larger than the left hand side, so (...waves hands, natural numbers are well-founded...) you can't ever get an infinite search tree, and it's very simple to statically determine termination.

However, removing all of those things makes things too restrictive IMO. We can probably come up with some other condition which guarantees termination though, and give a warning as you suggest.

**Comment by berdario** [comment] 2016-08-11 11:17
I don't see `UndecidableInstances` being mentioned in the list of GHC extensions that approximate Purescript semantics

https://github.com/purescript/purescript/wiki/Differences-from-Haskell#extensions

Should it be added?
