### ISSUE TITLE
Currying doesn't work in class `instance`

### ISSUE THREAD

**Issue by Hi-Angel** [purescript/purescript#4560] opened 2024-12-09 15:49 UTC
## Description

Given code:

```haskell
instance Eq FooBar where
  eq a b = eq a b
```

It is identical to

```haskell
instance Eq FooBar where
  eq = eq
```

However the latter causes compilation error.

I consulted how Haskell implementation works and identical code:

```haskell
instance Eq FooBar where
  (==) = (==)
```

…compiles just fine. So it's definitely a bug on the PureScript side.

## To Reproduce

Compile code:

```haskell
module Main where

import Prelude

import Effect (Effect)

data FooBar = Foo | Bar | Buzz

instance Eq FooBar where
  eq = eq

main :: Effect Unit
main = pure unit
```

## Expected behavior

It compiles fine

## Actual behavior

It fails with

```haskell
[1 of 1] Compiling Main
Error found:
at src/Main.purs:9:1 - 10:10 (line 9, column 1 - line 10, column 10)

  The value of $eqFooBar0 is undefined here, so this reference is not allowed.
```

## PureScript version

0.15.15

**Comment by garyb** [comment] 2024-12-09 17:31
This is a duplicate of #2975, but there is maybe an interesting point here - our tooling now suppresses the messages that `purs` emits that has the links pointing people to error docs like https://github.com/purescript/documentation/blob/master/errors/CycleInDeclaration.md

The doc does attempt to explain why this error occurs, but short version: it's not a bug that the Haskell version doesn't work in PureScript - it's not accepted because PureScript has strict evaluation semantics, so it's equivalent to `eq = undefined`. The eta-expanded version is still bad because it will explode the stack when called. The Haskell version will just never terminate.

(You perhaps know this already and just used `Eq` as a simple example case, but in case you don't, `Eq` is one of the classes that you can have the compiler derive the instance for).

**Closed** 2024-12-09 17:50 UTC
Labels: type: bug
