### ISSUE TITLE
Syntax for unnested lists

### ISSUE THREAD

**Issue by N-1-c-k-e** [purescript/purescript#1887] opened 2016-02-15 23:56 UTC
**Syntax:**
```purescript
...(in)... -- or [in] or {in}
    element1
    element2
    ...
    elementN
```
**Parsing:**
Paste all elements with same indentation level into parentheses and (for two or more elements) divide them by ",":
```purescript
...(element1, element2, ..., elementN)... -- or [...] or {...}
```
**Rationale:**
Easier to read, less typing, looks beautiful and consistent with language style.
Keyword "in" chosen because it's short and meaningful.
**Examples:**
```purescript
let author =
    {name: "Phil"
    ,interests:
        ["Functional Programming"
        , "JavaScript"
        ]
    }
-->
let author = {in}
    name: "Phil"
    interests: [in]
        "Functional Programming"
        "JavaScript"
```
```purescript
import Data.Array.Unsafe
    (head
    ,tail
    )
-->
import Data.Array.Unsafe (in)
    head
    tail
```

**Comment by garyb** [comment] 2016-02-16 01:18
:-1: from me, personally. Constructing arrays and lists can already be done in a similar way with rebindable `do`, and the `in` for `import` seems totally weird to me.

**Comment by hdgarrood** [comment] 2016-02-16 01:29
Yep, I agree with @garyb.

**Comment by N-1-c-k-e** [comment] 2016-02-16 01:48
Maybe parenthesized "do" instead of "in" is better.
But how to use do-notation for type synonyms? I mean this example:
```purescript
type Arc = { x :: Number
, y :: Number
, r :: Number
, start :: Number
, end :: Number
}
```

**Comment by user471** [comment] 2016-02-16 05:20
:+1: But, I think replacing commas with indentation would be enough https://github.com/purescript/purescript/issues/1775
There isn't much difference between 
```
x = [in]
  "Functional Programming"
  "JavaScript"
```
and
```
x = [
  "Functional Programming"
  "JavaScript"
]
```

**Comment by N-1-c-k-e** [comment] 2016-02-16 12:26
**user471**, simple commas replacing is half-baked solution:
1) You still have trailing paren.
2) This still looks more like C-syntax.
3) Whole line wasted for trailing paren.
I used dots for "...(in)..." to indicate arbitrary position of unnested list, but I didn't paste good examples. Here it is:
```purescript
modify (\state -> state { events = state.events <> [event] })
-->
modify (\state -> state {in})
    events = state.events <> [event]
```
```purescript
type EventHandler =
  forall eff refs.
    Eff ( props :: React.ReactProps
        , state :: React.ReactState React.ReadWrite
        , refs :: React.ReactRefs refs
        | eff
        ) Unit
-->
type EventHandler =
  forall eff refs.
    Eff ((in) | eff) Unit
        props :: React.ReactProps
        state :: React.ReactState React.ReadWrite
        refs :: React.ReactRefs refs
```

**Comment by zudov** [comment] 2016-02-16 13:41
@N-1-c-k-e How would you write a type which contains more than one enumeration? E.g.: 

```haskell
type EventHandlerThatReturnsAnObject =
  forall eff refs.
    Eff ( props :: React.ReactProps
        , state :: React.ReactState React.ReadWrite
        , refs :: React.ReactRefs refs
        | eff
        (Object (foo :: String, bar :: Int, baz :: Number))
```

**Comment by N-1-c-k-e** [comment] 2016-02-16 14:16
Only one list on each line can be unnested otherwise you need to abuse vertical space:
```purescript
type EventHandlerThatReturnsAnObject =
  forall eff refs.
    Eff
        ((in) | eff)
            props :: React.ReactProps
            state :: React.ReactState React.ReadWrite
            refs :: React.ReactRefs refs
        (Object (in))
            foo :: String
            bar :: Int
            baz :: Number
```

**Comment by hdgarrood** [comment] 2016-03-08 13:48
I vote to close this. Looking at the rationale:

>  Easier to read

Disagree.

> less typing

Not something we should be worrying about for the sake of a few characters.

> looks beautiful

Disagree.

> consistent with language style

I don't think the concept of 'consistency with the language style' is sufficiently well-defined to evaluate this claim properly.

**Comment by AppShipIt** [comment] 2016-03-08 13:58
> I think replacing commas with indentation could be enough #1775

Agree with @user471.

> I vote to close this.

👍

**Comment by N-1-c-k-e** [comment] 2016-03-09 00:01
> I vote to close this. Looking at the rationale:
    > Easier to read
    Disagree.

"Easier to read" is the one of the main reasons for syntax sugar. With unnested lists you remove visual noise (+ less typing) and clearly show your intention to separate some inner part of expression as a block.
You can even think about it in terms of simplified "where"-block:
```purescript
modify (\state -> state {in})
    events = state.events <> [event]
--> pseudocode! -->
modify (\state -> state x)
    where x = {events = state.events <> [event]}
```
As you can see, principle is the same. That's how I define "consistent with language style" concept in _this_ case and such consistency looks beatiful for me.

**Comment by paf31** [comment] 2016-03-10 03:08
Closing as duplicate of #1775.

**Closed by paf31** 2016-03-10 03:08 UTC
Labels: enhancement, syntax
