### ISSUE TITLE
Improve failing tests

### ISSUE THREAD

**Issue by paf31** [purescript/purescript#865] opened 2015-02-12 02:37 UTC
The failing tests right now pass exactly when their code doesn't build, but this might not be for the reason we intended. An improvement would be to assert that the compiler outputs a specific error message.

**Comment by hdgarrood** [comment] 2015-08-02 19:47
Duplicate of #1181 ?

**Comment by paf31** [comment] 2015-08-02 19:53
Looks like it, thanks.

**Closed** 2015-08-02 19:53 UTC
Labels: documentation, enhancement
