### ISSUE TITLE
Can we make exhaustivity checker a little cleverer?

### ISSUE THREAD

**Issue by hdgarrood** [purescript/purescript#1625] opened 2015-11-12 15:52 UTC
I recently wrote this:

```
instance eqFileFlags :: Eq FileFlags where
  eq R R             = true
  eq R_PLUS R_PLUS   = true
  eq RS RS           = true
  eq RS_PLUS RS_PLUS = true
  eq W W             = true
  eq WX WX           = true
  eq W_PLUS W_PLUS   = true
  eq WX_PLUS WX_PLUS = true
  eq A A             = true
  eq AX AX           = true
  eq A_PLUS A_PLUS   = true
  eq AX_PLUS AX_PLUS = true
  eq _ _             = false
```

and the result of this is that the exhaustivity check is abandoned due to too many possible cases, and so I get a warning.

I feel like this is sensible code that ought to be allowed without producing a warning. I don't really know how it works or whether this is a good idea, but perhaps an special case could be added where the last case has every argument as a wildcard? The exhaustivity checker could perhaps start by looking for this &mdash; in such a case, we can know that the definition is exhaustive, without having to do any additional work.

**Comment by garyb** [comment] 2015-11-12 15:56
What version of the compiler are you using? There are only 4096 permutations here I think, so it shouldn't be bailing out there, the limit is 10k - 0.7.5.3 added a fix for this (a missing `nub`).

**Comment by hdgarrood** [comment] 2015-11-12 15:57
`psc --version` outputs `0.7.5`. Should I update?

**Comment by hdgarrood** [comment] 2015-11-12 15:57
Haha, yes, clearly I should. Need to read more diligently, as ever.

**Comment by garyb** [comment] 2015-11-12 16:01
Even if that does fix it I like the idea of special casing when there are all-wildcard-patterns :+1:

**Comment by paf31** [comment] 2015-11-12 17:36
The issue is that you still need to deal with all cases for the redundancy check.

**Comment by garyb** [comment] 2015-11-14 15:21
Ah, of course.

**Comment by paf31** [comment] 2015-11-14 18:10
Can this be closed then? I'm in favour of finding optimizations for exhaustivity checking, but I can't think of any to document right now.

**Comment by garyb** [comment] 2015-11-14 18:25
I think so, yep. Does the later compiler deal with that example as it should @hdgarrood?

**Comment by hdgarrood** [comment] 2015-11-14 19:45
Yes, there are no warnings with 0.7.5.3.

**Closed** 2015-11-15 20:57 UTC
