### ISSUE TITLE
purs produce libtinfo.so.5 error message

### ISSUE THREAD

**Issue by gasacchi** [purescript/purescript#4082] opened 2021-04-27 01:27 UTC
## Description

Purescript compiler working perfectly but some error message make purs ide server not working with [psc-ide-vim](https://github.com/FrigoEU/psc-ide-vim)

## To Reproduce

install purescript with yarn global add purescript
or using binary release (both give same output error message)

`purs --version`

output:
```
purs: /usr/lib64/libtinfo.so.5: no version information available (required by purs)
0.14.1
```

`purs ide server`

output:
```
purs: /usr/lib64/libtinfo.so.5: no version information available (required by purs)

```

## Expected behavior

purs not produce error message

`purs --version`

output:
```
0.14.1
```

`purs ide server`

output:
```


```

## Additional context

I use Void linux
```
uname -a
Linux gsclinux 5.11.16_1 x86_64 GNU/Linux
```

libtinfo already installed
``` 
la /usr/ | grep libtinfo
libtinfo.so -> libncursesw.so.6.2
libtinfo.so.5 -> /usr/lib/libtinfo.so.6
libtinfo.so.6 -> libncursesw.so.6.2
libtinfo.so.6.2 -> libncursesw.so.6.2
```

error message blocking `psc-ide-vim` to send commands/queries to purs ide

## PureScript version

0.14.1

**Comment by f-f** [comment] 2021-04-27 09:02
We dropped the requirement for `libtinfo` in https://github.com/purescript/purescript/pull/4069, so this problem should disappear in `0.14.2`

**Comment by gasacchi** [comment] 2021-04-27 12:11
Thanks for response, hope new release will update soon

**Comment by hdgarrood** [comment] 2021-04-27 13:11
Presumably this message is being printed to stderr? If `purs ide server` and/or `psc-ide-vim` were using stdout/stderr correctly then this wouldn't be an issue, so this perhaps suggests that one or both of them should be changed. When I say "correctly", that is that output that is machine-parseable and expected should be printed to stdout, and diagnostic output (such as this "no version information available" message) should be printed to stderr. So `purs ide server` should stop printing machine-parseable/expected output to `stderr` if it is currently, and `psc-ide-vim` should stop trying to parse anything that comes from the stderr output of `purs ide server`.

**Comment by gasacchi** [comment] 2021-04-28 15:04
i want to make issues on `psc-ide-vim` but seem the repo not currently active, think to fork or rewrite with lua but still don't have time to do it so. :smile:

**Comment by paluh** [comment] 2021-05-25 10:24
@gasacchi I think that fix is [already on the way](https://github.com/FrigoEU/psc-ide-vim/pull/156).

@hdgarrood Thanks a lot for the suggestion!

Of course I can drop this comment if you think that this is not strictly relevant information ;-) Just please let me know.

**Comment by gasacchi** [comment] 2021-05-25 11:55
> @gasacchi I think that fix is [already on the way](https://github.com/FrigoEU/psc-ide-vim/pull/156).

thanks, i'll try it

**Comment by hdgarrood** [comment] 2021-05-29 17:43
Ok, if the issue is due to `psc-ide-vim` attempting to parse stderr output, then I think this can safely be closed as it doesn't appear to be a compiler issue. Thanks!

**Closed by hdgarrood** 2021-05-29 17:43 UTC
Labels: bug
