### ISSUE TITLE
Getting the path / line number of the calling function

### ISSUE THREAD

**Issue by jystic** [purescript/purescript#2757] opened 2017-03-19 08:07 UTC
I'm working on a testing library for PureScript and I'd like the assertion functions to be able to show where they were called from, as part of the test output.

In GHC 8.0 I'm doing this with [HasCallStack](https://hackage.haskell.org/package/base-4.9.1.0/docs/GHC-Stack.html#t:HasCallStack).

Does adding something like this make sense for PureScript? If not are there better ways to achieve the same thing?

I understand that implementing call stacks like this would be a bit odd for a strict language, but perhaps it's easier than mapping a JavaScript call stack back to a PureScript line number? I'm not sure, any ideas appreciated.

**Comment by michaelficarra** [comment] 2017-03-19 14:31
How would we spec this so that it's possible for all backends to implement? Not all languages have the same run time call stack introspection capabilities.

**Comment by hdgarrood** [comment] 2017-03-19 14:52
Would adding macros for the current source file and line number, as suggested in #2297, cover what you want?

**Comment by paf31** [comment] 2017-03-19 16:44
I think this is a duplicate of #2297. I would like for the solution to use the solver, and a new nullary class in `Prim`, something like `HasCallStack`.

**Closed** 2017-03-19 21:15 UTC
Labels: duplicate

**Comment by jystic** [comment] 2017-03-19 21:43
@hdgarrood yeah, as long as a function could request its caller to provide that information (ala `HasCallStack`)

You wouldn't want users to have to put `__LINE__` in their code everywhere
