### ISSUE TITLE
UnknownModule instead of UnknownType

### ISSUE THREAD

**Issue by user471** [purescript/purescript#1837] opened 2016-01-20 13:50 UTC
Foo.purs
```
module Foo where
```
Bar.purs
```
module Bar where
type X = Foo.X
```

```
Error found:
in module Bar
  Unknown module Foo
```

**Comment by hdgarrood** [comment] 2016-01-20 13:53
Possibly a dupe of https://github.com/purescript/purescript/issues/1733? What version of `psc` were you using?

**Comment by zudov** [comment] 2016-01-20 13:54
Syntax `Foo.X` refers to the `X` which is in module qualified as `Foo`. So it's much closer to `UnknownModule` than `UnknownType`. I think it would be nicer if it said "Unknown qualified module name" or something in that way.

**Comment by zudov** [comment] 2016-01-20 13:55
Oh, sorry. I didn't realize that, the `Foo` is indeed a full module name.

**Comment by garyb** [comment] 2016-01-20 13:56
Is this on 0.8?

**Comment by user471** [comment] 2016-01-20 13:57
@hdgarrood it's similar but it isn't the same. #1733 was fixed. This error only occur when you are trying to access nonexistent type from another module
@garyb rc1

**Comment by hdgarrood** [comment] 2016-01-20 13:59
#1733 wasn't opened until after the 0.8 RC was released, though, so the fix is only in master right now. I realise #1733 used a value in the example, and this has a type, but it still seems likely to me that this is the same bug.

**Comment by hdgarrood** [comment] 2016-01-20 14:04
On master, I do get the same error as in the original report here. However, the following does give "unknown type Foo.X" on master:

```
module Bar where
import Foo as Foo
type X = Foo.X

module Foo where
```

I can't remember whether the behaviour was changed so that all imports had to be listed - if it was, then I think that would explain these errors.

**Comment by user471** [comment] 2016-01-20 14:07
>"unknown type Foo.X" on master:

Same with rc1.

**Closed** 2016-01-22 01:33 UTC
Labels: bug, error-message
